### ISSUE TITLE
multiple $param values should only be accepted for SET OQL constructs

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#110]
**Reported by @cristianbogdan on 9 Dec 2002 08:22 UTC**
<mak:object from="general.archive.Document d, d.archives ar" where="d=$document" >

will fail miserably if $document comes from a HTTP parameter with multiple
values (one GET, one POST, or just ?document=aa&document=bb, or even the same
value, ?document=aa&document=aa

this is because org.makumba.view.MultipleAttributeParametrizer generates 
SELECT .... WHERE d=$1, $2
which is invalid OQL

in the first place, the value is multiple due to bug 35. in that case the values
will be the same, so the WORKAROUND is
pageContext.setAttribute("doc", pageContext.getRequest().getParameterValues("do\
cument")[0]);

and then use $doc instead of $document

Migrated-From: http://trac.makumba.org/ticket/232

**Comment by ghost** [comment]
**Comment by farry@best.eu.org on 29 Dec 2003 14:35 UTC**
Had a nice encounter with this 'bug' while trying to help out Wouter... 

situation:
- page attribute 'companyinfo' (contains string representation of ptr to cpy)

- newForm for adding general.company.Message, containing a dropdown selection of
companies

- newForm has action=<%viewVar%> with viewVar defined as 
<mak:object from="general.company.Company cpy" where="cpy=$companyinfo" >
<mak:value expr="cpy" printVar="companyPointer"/>
<% String viewVar="messageList.jsp?companyinfo="+companyPointer; %>

- wouter, not knowing how to automatically select one of the companies adds a
hidden field to the newForm, hoping it would do the selection:
<input type=hidden name=companyinfo value=<mak:value expr="cpy" />>

When submitting the form, the following error is displayed:

Please report to the developers.

line 1:82: unexpected token: ,
	at org.makumba.db.sql.oql.OQLParser.selectExpr(OQLParser.java:669)
	at org.makumba.db.sql.oql.OQLParser.query(OQLParser.java:163)
	at org.makumba.db.sql.oql.OQLParser.queryProgram(OQLParser.java:81)
	at org.makumba.MakumbaSystem.parseQueryFundamental(MakumbaSystem.java:338)
	at org.makumba.MakumbaSystem$1.makeResource(MakumbaSystem.java:322)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:127)
	at org.makumba.MakumbaSystem.getOQLAnalyzer(MakumbaSystem.java:302)
	at
org.makumba.view.AttributeParametrizer$1.makeResource(AttributeParametrizer.java:142)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:127)
	at org.makumba.view.AttributeParametrizer.findAST(AttributeParametrizer.java:150)
	at org.makumba.view.AttributeParametrizer.<init>(AttributeParametrizer.java:89)
	at
org.makumba.view.MultipleAttributeParametrizer$1.makeResource(MultipleAttributeParametrizer.java:102)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:127)
	at
org.makumba.view.MultipleAttributeParametrizer.getAttributeParametrizer(MultipleAttributeParametrizer.java:67)
	at
org.makumba.view.MultipleAttributeParametrizer.execute(MultipleAttributeParametrizer.java:47)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:343)
	at org.makumba.view.jsptaglib.QueryExecution.<init>(QueryExecution.java:111)
	at org.makumba.view.jsptaglib.QueryExecution.getFor(QueryExecution.java:99)
	at org.makumba.view.jsptaglib.QueryTag.doMakumbaStartTag(QueryTag.java:106)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:171)
	at org.apache.jsp.messageList$jsp._jspService(messageList$jsp.java:65)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)


Can't input of form be checked before being to the OQL parser, so these coding
mistakes return a more understandable error message? For a makumba user not
knowing about OQL this message does not hint towards parameter naming violation.

I guess the problem now was having bot a GET and POST parameter with the same
name, right?



After finding what went wrong, I changed the name of the hidden field from
companyinfo to company (mimicking the problem described in original bug report)
which resulted in the following error:

Invalid value for temp17446527#col0: Only java.lang.String and
org.makumba.Pointer are assignable to makumba pointers, given value <[bqs4v6w,
bqs4v6w]> is of type java.util.Vector

Again, perhaps here a more clarifying error message can help novice makumba
users to figure out what they did wrong. The moment you get a vector as input
for a field that is not of set type, you know somehow the makumba user should
either not allow multiple selections (dropdown, checkbox) or not hardcode hidden
fields with the same name as mak:input fields.

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 1 Jul 2010 13:47 UTC**

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 19 Mar 2013 03:28 UTC**
this works OK since some time ago due to better param analysis

parameter cust at position 0  cannot have multiple values 
query: SELECT c AS col1,c.name AS col2 FROM Customer c WHERE c=$cust

**Comment by ghost** [comment]
**Modified by @cristianbogdan on 19 Mar 2013 03:28 UTC**
