### ISSUE TITLE
ClassCastException in oql.QueryAST.writeConditions

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#121]
**Reported by @stefanb on 31 Dec 2002 11:39 UTC**
Farry is trying to make a local makumba work on his laptop, but keeps getting:
-----
Internal Makumba error
Please report to the developers

java.lang.ClassCastException
	at org.makumba.db.sql.oql.QueryAST.writeConditions(QueryAST.java:519)
	at org.makumba.db.sql.oql.QueryAST.writeInSQLQuery(QueryAST.java:560)
	at org.makumba.db.sql.Query.<init>(Query.java:34)
	at org.makumba.db.sql.Query.<init>(Query.java:28)
	at org.makumba.db.sql.Database.prepareQueryImpl(Database.java:166)
	at org.makumba.db.DBConnection$1.makeResource(DBConnection.java:23)
	at org.makumba.util.NamedResourceFactory.makeResource
(NamedResourceFactory.java:38)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:43)
	at org.makumba.util.NameValue.getResource(NameValue.java:29)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:101)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:157)
	at org.makumba.db.DBConnectionWrapper.executeQuery
(DBConnectionWrapper.java:21)
	at org.makumba.db.Database.addTable(Database.java:409)
	at org.makumba.db.Database$3.configureResource(Database.java:439)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:47)
	at org.makumba.util.NameValue.getResource(NameValue.java:29)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:101)
	at org.makumba.db.Database.getTable(Database.java:269)
	at org.makumba.db.sql.oql.QueryAST.getFieldName(QueryAST.java:486)
	at org.makumba.db.sql.oql.IdAST.writeInSQLQuery(IdAST.java:20)
	at org.makumba.db.sql.oql.QueryAST.writeProjection(QueryAST.java:449)
	at org.makumba.db.sql.oql.QueryAST.writeInSQLQuery(QueryAST.java:546)
	at org.makumba.db.sql.Query.<init>(Query.java:34)
	at org.makumba.db.sql.Query.<init>(Query.java:28)
	at org.makumba.db.sql.Database.prepareQueryImpl(Database.java:166)
	at org.makumba.db.DBConnection$1.makeResource(DBConnection.java:23)
	at org.makumba.util.NamedResourceFactory.makeResource
(NamedResourceFactory.java:38)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:43)
	at org.makumba.util.NameValue.getResource(NameValue.java:29)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:101)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:157)
	at org.makumba.db.DBConnectionWrapper.executeQuery
(DBConnectionWrapper.java:21)
	at org.makumba.db.Database.addTable(Database.java:409)
	at org.makumba.db.Database$3.configureResource(Database.java:439)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:47)
	at org.makumba.util.NameValue.getResource(NameValue.java:29)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:101)
	at org.makumba.db.Database.getTable(Database.java:269)
	at org.makumba.db.sql.oql.QueryAST.getFieldName(QueryAST.java:486)
	at org.makumba.db.sql.oql.IdAST.writeInSQLQuery(IdAST.java:20)
	at org.makumba.db.sql.oql.QueryAST.writeProjection(QueryAST.java:449)
	at org.makumba.db.sql.oql.QueryAST.writeInSQLQuery(QueryAST.java:546)
	at org.makumba.db.sql.Query.<init>(Query.java:34)
	at org.makumba.db.sql.Query.<init>(Query.java:28)
	at org.makumba.db.sql.Database.prepareQueryImpl(Database.java:166)
	at org.makumba.db.DBConnection$1.makeResource(DBConnection.java:23)
	at org.makumba.util.NamedResourceFactory.makeResource
(NamedResourceFactory.java:38)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:43)
	at org.makumba.util.NameValue.getResource(NameValue.java:29)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:101)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:157)
	at org.makumba.db.DBConnectionWrapper.executeQuery
(DBConnectionWrapper.java:21)
	at org.makumba.view.AttributeParametrizer.execute
(AttributeParametrizer.java:151)
	at org.makumba.view.MultipleAttributeParametrizer.execute
(MultipleAttributeParametrizer.java:24)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:305)
	at org.makumba.view.jsptaglib.QueryStrategy.doQuery
(QueryStrategy.java:409)
	at org.makumba.view.jsptaglib.RootQueryStrategy.onInit
(RootQueryStrategy.java:62)
	at org.makumba.view.jsptaglib.RootData.setStrategy(RootData.java:43)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:116)
	at org.apache.jsp.mierva_0002dcount$jsp._jspService
(mierva_0002dcount$jsp.java:66)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
----
whenever he makumba tries to make a query, even the most simple ones

the file in qestion
org.makumba.db.sql.oql.QueryAST.writeConditions(QueryAST.java:519)
is being changed in a seperate branch (newController) documented in bug 6

His system seems quite ok (he'll hopefully attach his systemInfo dump here, or 
send us a url for it)

Migrated-From: http://trac.makumba.org/ticket/280

**Comment by ghost** [comment]
**Comment by priit@best.eu.org on 31 Dec 2002 12:30 UTC**
This is the error I get when using a local karambasmall db (you can find it on
devel.best.eu.org/~priit/karambasmall.zip). I see the very nice welcome.jsp
screen, after trying to log in (password xxx) i get the following error:

Error in business logic code

java.lang.ClassCastException
	at org.makumba.db.sql.oql.OQLParser.primaryExpr(OQLParser.java:1956)
	at org.makumba.db.sql.oql.OQLParser.postfixExpr(OQLParser.java:1836)
	at org.makumba.db.sql.oql.OQLParser.unaryExpr(OQLParser.java:1822)
	at org.makumba.db.sql.oql.OQLParser.inExpr(OQLParser.java:1738)
	at org.makumba.db.sql.oql.OQLParser.multiplicativeExpr(OQLParser.java:1663)
	at org.makumba.db.sql.oql.OQLParser.additiveExpr(OQLParser.java:1579)
	at org.makumba.db.sql.oql.OQLParser.relationalExpr(OQLParser.java:1464)
	at org.makumba.db.sql.oql.OQLParser.equalityExpr(OQLParser.java:1358)
	at org.makumba.db.sql.oql.OQLParser.quantifierExpr(OQLParser.java:1282)
	at org.makumba.db.sql.oql.OQLParser.andExpr(OQLParser.java:1216)
	at org.makumba.db.sql.oql.OQLParser.orExpr(OQLParser.java:1181)
	at org.makumba.db.sql.oql.OQLParser.expr(OQLParser.java:707)
	at org.makumba.db.sql.oql.OQLParser.whereClause(OQLParser.java:816)
	at org.makumba.db.sql.oql.OQLParser.selectExpr(OQLParser.java:661)
	at org.makumba.db.sql.oql.OQLParser.query(OQLParser.java:156)
	at org.makumba.db.sql.oql.OQLParser.queryProgram(OQLParser.java:74)
	at org.makumba.MakumbaSystem.parseQueryFundamental(MakumbaSystem.java:283)
	at org.makumba.MakumbaSystem$1.makeResource(MakumbaSystem.java:267)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:43)
	at org.makumba.util.NameValue.getResource(NameValue.java:29)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:101)
	at org.makumba.MakumbaSystem.getOQLAnalyzer(MakumbaSystem.java:247)
	at org.makumba.db.sql.Query.<init>(Query.java:28)
	at org.makumba.db.sql.Database.prepareQueryImpl(Database.java:166)
	at org.makumba.db.DBConnection$1.makeResource(DBConnection.java:23)
	at org.makumba.util.NamedResourceFactory.makeResource(NamedResourceFactory.java:38)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:43)
	at org.makumba.util.NameValue.getResource(NameValue.java:29)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:101)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:157)
	at org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:21)
	at org.eu.best.privatearea.Logic.findMember(Logic.java:36)

THis is the output of localhost:8080/systemInfo.jsp:


System Information
Client:   Browser: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.0.1)
          Gecko/20020823 Netscape/7.0
          Host (IP): localhost (127.0.0.1)
Server:
Initial heap (-Xms):  10MB
Max heap (-Xmx):  70MB
Current heap size:  14 MB
Heap in use:  8 MB
Free heap:  6,1 MB
Server is up since: 31 dec 2002 13:15, last Karamba (re)load: 31 dec 2002 13:15
Active sessions: 1
Server protocol, name and port: http://localhost:8080
Server software: Apache Tomcat/4.1.12
<-- Tip: reload this page to see the memory situation after garbage collection
Makumba:
Property Value
version   makumba-0.5.5.16
Default database name   localhost_mysql_karambasmall
DBSV   100
Number of connections open   10
SQL engine and version   MySQL 3.23.32-debug
JDBC driver and version   Mark Matthews' MySQL Driver 2.0.4
Data definitions parsed 12
Database localhost_mysql_karambasmall per-connection query objects 1
Database localhost_mysql_karambasmall per-connection update objects 0
Database tables and query result structures for localhost_mysql_karambasmall 0
Databases open 1
Handler family classes 23
Handler family methods 1
Handler family redirectors 3
Http controller form responders 0
JSP pages that have mak: tags 2
OQL parsed queries 1
Java Virtual Machine properties
Property Value
java.runtime.name: 

Java(TM) 2 Runtime Environment, Standard Edition

sun.boot.library.path: C:\j2sdk1.4.1_01\jre\bin
java.vm.version: 1.4.1_01-b01
java.vm.vendor: Sun Microsystems Inc.
java.vendor.url: http://java.sun.com/
path.separator: ;
java.vm.name: Java HotSpot(TM) Server VM
file.encoding.pkg: sun.io
java.util.logging.config.file: logging.properties
user.country: BE
sun.os.patch.level: java.vm.specification.name: 
Java Virtual Machine Specification
user.dir: C:\makumba\karamba
java.runtime.version: 1.4.1_01-b01
java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs: C:\j2sdk1.4.1_01\jre\lib\endorsed
os.arch: x86
java.io.tmpdir: ../../temp
line.separator: 
java.vm.specification.vendor: Sun Microsystems Inc.
user.variant: 
java.naming.factory.url.pkgs: org.apache.naming
os.name: Windows XP
sun.java2d.fontpath: 
java.library.path: C:\j2sdk1.4.1_01\jre\bin
                   .
                   C:\WINDOWS\System32
                   C:\WINDOWS
                   C:\makumba\util-win\jdk1.3\bin
                   C:\makumba\util-java\ant\bin
                   C:\makumba\util-win\mysql\bin

                   C:\makumba\util-win\cvs
                   C:\makumba\util-win\jikes
                   C:\WINDOWS\system32
                   C:\WINDOWS
                   C:\WINDOWS\System32\Wbem
                   C:\PROGRA~1\COMMON~1\AUTODE~1

java.specification.name: Java Platform API Specification
java.class.version: 48.0
java.util.prefs.PreferencesFactory: java.util.prefs.WindowsPreferencesFactory
os.version: 5.1
user.home: C:\Documents and Settings\Farry-BEST
org.eu.best.karamba.startupTime: 31 dec 2002 13:15
user.timezone: Europe/Paris
catalina.useNaming: true
java.awt.printerjob: sun.awt.windows.WPrinterJob
java.specification.version: 1.4
file.encoding: 8859_1
catalina.home: ../util-java/tomcat-4.1
user.name: Farry-BEST
java.class.path: C:\makumba\util-java\tomcat-4.1\bin\bootstrap.jar
                 C:\temp
                 C:\j2sdk1.4.1_01\jre\lib\rt.jar
                 C:\j2sdk1.4.1_01\lib\tools.jar
                 C:\makumba\util-java\ant\lib\xml-apis.jar
                 C:\makumba\util-java\ant\lib\xercesImpl.jar
                 C:\makumba\util-jva\ant\lib\optional.jar
                 C:\makumba\util-java\ant\lib\ant.jar
                 C:\makumba\karamba
                 C:\makumba\util-java\lib\mysql.jar
                 C:\makumba\util-java\lib\postgresql.jar
                 C:\makumba\util-java\lib\postgresql2.jar
                 C:\makumba\util-java\lib\swing.jar
                 C:\makumba\util-java\lib\antlr.jar

java.naming.factory.initial: org.apache.naming.java.javaURLContextFactory
java.vm.specification.version: 1.0
sun.arch.data.model: 32
java.home: C:\j2sdk1.4.1_01\jre
java.specification.vendor: Sun Microsystems Inc.
user.language: nl
makumba.long-content: 24576
awt.toolkit: sun.awt.windows.WToolkit
java.vm.info: mixed mode
java.version: 1.4.1_01
java.ext.dirs: C:\j2sdk1.4.1_01\jre\lib\ext
sun.boot.class.path: C:\j2sdk1.4.1_01\jre\lib\rt.jar
                     C:\j2sdk1.4.1_01\jre\lib\i18n.jar
                     C:\j2sdk1.4.1_01\jre\lib\sunrsasign.jar
                     C:\j2sdk1.4.1_01\jre\lib\jsse.jar
                     C:\j2sdk1.4.1_01\jre\lib\jce.jar
                     C:\j2sdk1.4.1_01\jre\lib\charsets.jar
                     C:\j2sdk1.4.1_01\jre\classes

java.vendor: Sun Microsystems Inc.
catalina.base: tomcat
file.separator: \
java.vendor.url.bug: http://java.sun.com/cgi-bin/bugreport.cgi
sun.cpu.endian: little
sun.io.unicode.encoding: UnicodeLittle
sun.cpu.isalist: pentium i486 i386

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 7 Jan 2003 09:43 UTC**
(i am not sure if comment 1 refers to win XP and if comment 0 refers to
karambasmall, below i assume "yes" for both. i also don't know exactly how you
installed, e.g. if you used the bundle properly)

i suspect that the cause of this is a change in the MDDs since the last release
of karambasmall. one quick way to check this is to try to use a full karamba db
on the laptop if diskspace permits. 

if that fails, we have a windows XP incompatibility, which is not unexpected
since we never tested makumba there. before testing the full karamba, i'd try
"ant test" in a makumba checkout. it only needs an empty "makumba" database to
be created. if the basic tests don't pass, there's no point in trying karamba.

if the "MDD change" hypothesis is still plausible, i suggest to look in the MDD
CVS logs and see what changed since the last karambasmall release. to find when
i did the karambasmall release, look for the mail announcing it, or at the date
of the zip, etc.

i think the ClassCast error (confusing indeed, as any runtime exception) is due
to the fact that the OQL translator still has some problems in reporting OQL
programmer errors (see bug 33 for another example)

please try to better summarize the title of the bug, comment 1 has nothing to do
with writeConditions. about the changes in newController, i can assure you that
they have nothing to do with this.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 14 Mar 2003 08:59 UTC**
i suspect that the root of this bug is a data inconsistency, since i guess it 
uses a similar DB to the one at bug 340. 
so if there is no supplementary data about this, i think we should close it

**Comment by ghost** [comment]
**Comment by @stefanb on 14 Mar 2003 09:41 UTC**
Priit mentioned sometime ago, that this was solved after upgrading Tomcat in 
the Farry's bundle. ...so it might not be related to bug 340.

Could Priit or Farry please confirm, so we know what really happened?

**Comment by ghost** [comment]
**Comment by priit@best.eu.org on 22 Mar 2003 00:50 UTC**
No, I think this error was never solved on Farry's laptop, we got stuck here and
gave up (actually, it was because my plane left :)). But the database
inconsistency hypothesis (in relation to bug 340) seems probable since we used
the same DB.

Farry has a new bundle working now and it's impossible to reproduce the error. I
agree on closing the bug, in fact I just did.
