### ISSUE TITLE
mak:form can only have mak:list AFTER, not BEFORE any mak:input

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#132]
**Reported by @frederikhabils on 12 Feb 2003 22:15 UTC**
it seems that inside a <mak:form>, it is not possible to have any <mak:input> 
after any <mak:list>

example offending code:
--------------------------
<mak:form action="<%=thisFile%>" method="post" >

Some input created with mak:list
<select name="lbg">
  <mak:list from="best.internal.Lbg lbg" orderBy="lbg.name">
  <option><mak:value expr="lbg.name" /></option>
  </mak:list>
</select>

some input created with mak:input
<br><mak:input name="filterDate2" dataType="date" value="$now"/>
</mak:form>
---------------------
as seen in: 
http://18080.makumba.org/fred-k/test/BUG_makform_combo_maklist_makinput2.jsp

gives error: 
Internal Makumba error
Please report to the developers

java.lang.NullPointerException	at 
org.makumba.view.jsptaglib.MakumbaTag.getRootQueryBuffer(MakumbaTag.java:337)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:110)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:118)
	at 
org.apache.jsp.BUG_0005fmakform_0005fcombo_0005fmaklist_0005fmakinput2
$jsp._jspService(BUG_0005fmakform_0005fcombo_0005fmaklist_0005fmakinput2
$jsp.java:210)	at org.apache.jasper.runtime.HttpJspBase.service
(HttpJspBase.java:107)	

When you bring the mak:list to be UNDER the mak:input, the problem is not there.
e.g. http://18080.makumba.org/fred-k/test/BUG_makform_combo_maklist_makinput.jsp

Johnny actually has some forms where mak:input and mak:list are combined, but 
luckily the mak:list came last... Today Gwen (and also Priit), and me lost some 
hours trying to figure out why new (search) form in helpdesk didn't work.

Migrated-From: http://trac.makumba.org/ticket/300

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 15 Feb 2003 23:07 UTC**
I have another example of that error coming from trying to improve helpdesk
welcome page on the public website:
http://cvs.makumba.org/cgi-bin/cvsweb.cgi/~checkout~/website/helpdesk/welcome.jsp?rev=2.2&content-type=text/plain

HOWEVER I have also a counter example, with a <mak:input> after a <mak:list>
inside a form (almost exactly the same configuration as the example before) that
is working:
http://cvs.makumba.org/cgi-bin/cvsweb.cgi/~checkout~/karamba/public_html/helpdesk/welcome.jsp?rev=2.3&content-type=text/plain
Stefan developped the latest version of this page. Did you face any NPE error
Stefan? If yes how did you solve it?

Gwen.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 18 Feb 2003 17:00 UTC**
please test all these test cases at 
http://18080.makumba.org/mak-test-k

just to see if newController has similar problems, and how
tnx

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 18 Feb 2003 18:03 UTC**
Couldn't test www.best.eu.org/helpdesk with new settings of course but for the 
rest it has exactly the same behavior/error thrown.
/Gwen.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 20 Feb 2003 17:22 UTC**
thanks a lot for the huge work of isolating this bug!
i have a fix now
http://18080.makumba.org/mak-test-k/test/BUG_makform_combo_maklist_makinput2.jsp

as you can imagine, the fix is deep in the organs of the makumba jsp taglib. 
due to that, it will need regression testing (at mak-test-k) before i can 
publish a new makumba version. maybe not a complete testing, but at least an 
exploration of most form pages.

the problem is that both mak:form and mak:list consider themselves as 
being "root" of the tag structure. this is not very good design, but the excuse 
is that i implemented forms much after i implemented lists. 

in its cleanup operations (at /mak:list), mak:list was removing some data 
structures (RootData) that mak:form tried to use afterwards, hence the NPE 
because the RootData was assumed to be there and it wasn't.

in this fix-version, the mak:list will keep a reference to the RootData created 
by the embedding mak:form, and restore it at the end of the mak:list (sort of 
like pushing into and popping from a stack). 

i tested if it's possible to have mak:input in a mak:list in a mak:form, it 
seems to be ok. 

<mak:form action="<%=thisFile%>" method="post" >
  <mak:list from="best.internal.Lbg lbg" orderBy="lbg.name">
	<mak:input name="name" value="lbg.name"/>
  </mak:list>
<mak:input name="filterDate2" dataType="date" value="$now"/>
</mak:form>

mak:input in a mak:form inside a mak:list works too 

  <mak:list from="best.internal.Lbg lbg" orderBy="lbg.name">
<mak:form action="<%=thisFile%>" method="post" >
	<mak:input name="name" value="lbg.name"/>
</mak:form>
  </mak:list>

i guess i will play more with this when implementing multiple forms.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 21 Feb 2003 00:03 UTC**
nice to see you've pinpointed this deep deep error :-)

i tested 4-5 form pages around johnny & private (new J account, edit 
private/account, edit private/teams, edit private/event) without problems. too 
tired now to continue. maybe later...

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 14 Mar 2003 08:40 UTC**
it seems that there are no problems about this anymore so i close this for now
