### ISSUE TITLE
not working well with JDBC 3

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#133]
**Reported by @stefanb on 13 Feb 2003 08:28 UTC**
----systemInfo:-----
version   makumba-0.5.5.19  
Default database name   localhost_mysql_production  
DBSV   9  
Number of connections open   10  
SQL engine and version   MySQL 4.0.10-gamma  
JDBC driver and version   MySQL-AB JDBC Driver 3.0.5-gamma  
Data definitions parsed  32  
Database localhost_mysql_production per-connection query objects  434  
Database localhost_mysql_production per-connection update objects  5  
Database tables and query result structures for localhost_mysql_production  
739  
Databases open  1  
Handler family classes  99  
Handler family methods  3  
Handler family redirectors  8  
Http controller form responders  47  
JSP attribute parametrizer objects  1163  
JSP composed queries  333  
JSP mak:list root tags  125  
JSP pages that have mak: tags  95  
OQL parsed queries  561  

-----stacktrace-------
Error in business logic code
java.sql.SQLException: No operations allowed after connection closed	at 
com.mysql.jdbc.Connection.checkClosed(Connection.java:2336)	at 
com.mysql.jdbc.Connection.prepareStatement(Connection.java:1260)	at 
com.mysql.jdbc.Connection.prepareStatement(Connection.java:1240)	at 
org.makumba.db.sql.SQLDBConnection.getPreparedStatement(SQLDBConnection.java:23)
	at org.makumba.db.sql.Query.execute(Query.java:50)	at 
org.makumba.db.DBConnection.executeQuery(DBConnection.java:157)	at 
org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:21)
	at org.eu.best.privatearea.Logic.findMember(Logic.java:36)	
------/stacktrace-------

This occurs after some time (cca 1hr?) after working quite nice in stressfull 
production environment (peak hours before the application deadline).

At first it only affects some pages, while some still do work, but after a 
while no page that requires DB access works anymore.

Migrated-From: http://trac.makumba.org/ticket/301

**Comment by ghost** [comment]
**Comment by @frederikhabils on 13 Feb 2003 10:22 UTC**
i don't know if to blame mysql-jdbc 3.0.5-gamma  or the new MySQL 4.0.10-gamma.

anyway, here is some excerpts from CHANGELOG of mysql-jdbc 3
http://mysql.belnet.be/downloads/api-jdbc-dev.html (belgian mirror)

2002-11-18 - Version 3.0.3 Beta
- Check for connection closed in more Connection methods (createStatement, 
prepareStatement, setTransactionIsolation, setAutoCommit). 

2002-09-21 - Version 3.0.1 Beta
- Connection.isClosed() no longer "pings" the server 
- Connection.close() issues rollback() when getAutoCommit() == false 

2002-07-31 - Version 3.0.0 Beta
- Better checking for closed connections in Statement and PreparedStatement.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 13 Feb 2003 10:54 UTC**
it looks like jdbc3 is more strict with using "closed" connections. this may be
a makumba bug then (makumba calling connection.close() and then trying to use
the connection). BUT makumba never calls close() on a java.sql.Connection, it
simply de-references it and waits for its finalizer to perform the closure. 

it may just as well be a jdbc3 bug in implementing Connection.isClosed().
according to the spec, isClosed() is guaranteed to return true only if close()
has been called (i.e. not if the connection has been closed by the sql server).
but this smells like "connection not used for 1h, therefore closed by mysqld".
so increasing the mysqld connection timeout may help. is mysqld configured not
to close the connections automatically, or with a big timeout? 

i remember that we had timeout problems before. many of them were solved when i
added this to org.makumba.db.sql.Database:
      if(connectionConfig.get("autoReconnect")==null)
	connectionConfig.setProperty("autoReconnect", "true");

autoreConnect is a flag we send to jdbc:mysql. but maybe something changed in
that configuration between jdbc2 and jdbc3?

i think we should take advantage of these peak times to look for a solution to
this. or we can simply configure this in a trial server and wait 1h, then make
lots of accesses.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 17 Feb 2003 21:37 UTC**
with respect to the prev. comments, i looked at the Connector.java sources of 
this jdbc v3.0.5 found at 
http://www.mysql.com/downloads/api-jdbc-dev.html (sources in the zip)

from that i would conclude:

- checkClosed() is just: if (this.isClosed) throw new SQLException("No 
operations allowed after connection closed", "08003");

- isClosed() = return this.isClosed

- object variable this.isClosed, starts as TRUE, and then gets assigned FALSE 
during constructor execution. After that, only the close() and the cleanup() 
will set it back to FALSE. cleanup is only called during finalize, and in some 
catch exception blocks in constructor, before re-throwing an SQLException out.

........
So the only reason for isClose()==TRUE, IMO is that the call comes before the 
constructor finishes, or if connector is close()'d manually or by finalise().
........
any chance that the connection are used before constructor can finish?? 
Especially in heavily optimised code, multiprocessor system, we may have to be 
more careful?

--
about autoReconnect: (11-08-02 - Version 3.0.2-dev)
    - Failover and autoReconnect only work when the connection is in a 
      autoCommit(false) state, in order to stay transaction safe
... I'm under the impression that autoCommit it True by default.

Apart from that, i can't find much info that i can make sense of, on these 
issues.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 18 Feb 2003 16:50 UTC**
nice source research Fred! 
one idea is to compile a JDBC driver that prints a stacktrace in cleanup(). then
we will know for sure which code invokes the cleanup... i will try to do that,
and install it in production.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 18 Feb 2003 20:48 UTC**
in the last 8 hours, there's been no less than 28 connections that were closed 
and reconnected by the new feature in makumba 0.5.5.20!

So i'm really curious who kills those connections! I re-did above mentions 
source research, still with the same conclusions. 
The only place that instance variable isClose=true [isClosed()](==) is before 
constructor runs, after "private cleanup()" [only if constructor fails](called) 
and after "public close()".

I would recommend to print stacktraces both on cleanup() and close(). 

there is a comment on Connection.close saying:
     * <B>Note:</B> A Connection is automatically closed when it is
     * garbage collected.  Certain fatal errors also result in a closed
     * connection.

I was puzzled by what that means, and checked thru all the java files in the 
connector/J-3 package for code that would call Connection.close(), but couldn't 
find any.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 19 Feb 2003 13:22 UTC**
Fred:
>      * <B>Note:</B> A Connection is automatically closed when it is
>      * garbage collected.  Certain fatal errors also result in a closed
>      * connection.
> I was puzzled by what that means, and checked thru all the java files in the 
> connector/J-3 package for code that would call Connection.close(), but couldn't 
> find any. 

well, when they talk about garbage collection you have to look for the
finalize() method, which is the standard (as per Java language spec) method
called when an object is garbage collected. 

Connection.finalize() calls cleanup(), which is also called by close()

**Comment by ghost** [comment]
**Comment by @frederikhabils on 19 Feb 2003 14:19 UTC**
Great to have the Connection patched... curious for the resulting new info :-)

Note, when I said that I was puzzled, i meant i was puzzled by 
  > Certain fatal errors also result in a closed connection.

and not by 
>      * <B>Note:</B> A Connection is automatically closed when it is
>      * garbage collected.  

that's why i went searching in the package for other code that could (in case 
of 'certain fatal errors') call Connection.close(). But couldn't find any. As a 
matter of pride, i can mention that I've seen Java fundamentals, including 
finalize() :-)


> Connection.finalize() calls cleanup(), which is also called by close()

to put the dots on the i... 
finalize() calls cleanup(), and cleanup (usually) calls close() :-) [the 
3.0.5 version, didn't see 3.0.6](in)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 19 Feb 2003 14:42 UTC**
shit. the connections are closed due to garbage collection.

the mistery now is: how can they be garbage collected when they are still
_referred_ by org.makumba.db.sql.SQLDBConnection??? we know that they are
refered because... their prepareStatement method is invoked later on (at the
point where the old exceptions used to arise, and where now the new connection
is created)... how can an object be finalized when it's still referred??? i am
puzzled...

java.lang.Throwable: connection closing at Wed Feb 19 15:08:03 CET 2003
        at com.mysql.jdbc.Connection.close(Connection.java:1044)
        at com.mysql.jdbc.Connection.cleanup(Connection.java:2004)
        at com.mysql.jdbc.Connection.finalize(Connection.java:1139)
        at java.lang.ref.Finalizer.invokeFinalizeMethod(Native Method)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:83)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:14)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:160)


for further experiments, i copied a jdbc 3.0.6 in
tequila:~karamba/sources/mysql-connector-3.0.6-stable
i also copied ~karamba/util-java/lib/junit.jar to
~karamba/sources/mysql-connector-3.0.6-stable/lib-nodist

from there you can compile with "ant"
then, to put it in production:
cd ~karamba/sources/karamba

cp
../build-mysql-jdbc/mysql-connector-java-3.0.6-stable/mysql-connector-java-3.0.6-stable-bin.jar
../../util-java/tomcat-4.1/common/lib/

ant stopTomcat
nohup ant tomcat &

i also made it print stacktrace when connection _opens_ (didn't have the
patience to wait for close :). the traces show that connections are declared
open at Connection.java:1595

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 19 Feb 2003 17:40 UTC**
i am off this issue for now

i made a custom makumba version that prints a message at the finalization of
every connection-related object. the idea is that the _only_ class whose objects
should be finalized is org.makumba.db.DBConnectionWrapper. so these messages are
_expected_ 
FINALIZE called for org.makumba.db.DBConnectionWrapper@1367e28, already closed

sometimes there will be messages like
FINALIZE called for org.makumba.db.DBConnectionWrapper@1367e28 wrapping connection 5
in that case, connection 5 will be given to the system 

as i said, i cannot understand why Connections are finalized, but the only
plausible hypothesis is that the objects that refer them
(org.makumba.db.sql.SQLDBConnection) are dead as well. in that case we _might_
see FINALIZE messages printed for them, like 
FINALIZE called for connection 5

the custom makumba also prints "connection 5 uses
com.mysql.jdbc.Connection@1243ef", so we can make a clear association between
SQLDBConnections and com.mysql.jdbc.Connection, whose address is printed at
opening (when stacktraces are not printed anymore, they are useless, we know
that opening is done around Connection:1595) and closing (when stacktraces are
still printed)

so, follow the logs...
grep -A4 "closing " tomcat/logs/server-output.txt
will show the latest connection closures...

a hypothesis: may be due to the large heap allocated, the finalization takes a
long time. that may mean that the Connection is still available even after its
finalize() has ran... not sure... that still doesn't explain why finalize runs
in the first place

**Comment by ghost** [comment]
**Comment by @frederikhabils on 19 Feb 2003 20:14 UTC**
i looked at the logs, but apart from a headache, I'm not getting too much of 
it...

As it is, I think I don't know enough of the class collaboration diagram of the 
classes involved, to understand the previous comments (and the effect of one 
finalizing to the other...).  Maybe if i have energy, I'll try to construct it 
from the sources. 

-----

one of the parts puzzling me above:

> sometimes there will be messages like
> FINALIZE called for org.makumba.db.DBConnectionWrapper at 1367e28 wrapping 
connection 5
> in that case, connection 5 will be given to the system 

what does this "given back to the system" mean? Does it mean that by finalizing 
the wrapper, there's nobody referencing DBConnection, so that the system is at 
liberty to garbageCollect and finalize it at any time it likes?

----

Also, I need to look up: when an object finalises, isn't it supposed to first 
run finalise on all of it's internal Objects? or is finalising done in a total 
unsynchronised manner?

----

There are +700 lines 
FINALIZE called for org.makumba.db.DBConnectionWrapper@407166 wrapping 
org.makumba.db.ClosedDBConnection@18a8ce2

what are those?

----

looking at the recent logs, there's not been so much happening, apart from what 
you indicated as expected. Only: 

FINALIZE called for org.makumba.db.DBConnectionWrapper@b9dc79 wrapping 
connection 7
FINALIZE called for org.makumba.db.DBConnectionWrapper@10e3a00 wrapping 
connection 7

but no "reconnection" (by the makumba.db.DBConnection), no "closing connection" 
(by the com.mysql.jdbc.Connection)


I would think that adding the FINALIZE printouts (on classes that previously 
did not have finalize() ?) can have changed the garbage collection process (as 
i think i read that objects with finalize() are slower to be finalized and 
recovered)...

----
BTW, I'm sort of "shaken" in my understanding of OO languages w/ runtime GC : 
what happens if you use an object that has been finalized and garbage collected 
(what of course is supposed to be impossible)... i guess that you will try to 
read the memory location previously in use, for getting the object variables... 
so as long as the object's space is not reused, you can still "use" a garbage 
collected object, if you still have a reference to it ["impossible"]... 
fascinating :-)

So how come these objects are GC'd and finalised when they are referenced 
still... good question :-)

**Comment by ghost** [comment]
**Comment by @frederikhabils on 19 Feb 2003 22:29 UTC**
i have registered a specific hypothesis about why connections are finalized, as 
bug 314.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 19 Feb 2003 22:34 UTC**
i found following command more useful for checking the logs now (there's a lot 
of printouts now)

grep -f patterns server-output.txt | grep -v "already closed" | tail -60

where patterns is a file with content: 
--
FINALIZE
uses
reconnect
closing
opens at
--

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 20 Feb 2003 12:41 UTC**
before this gets completely forgotten, some responses to Fred, mostly due to
imprecise wording of mine

> what does this "given back to the system" mean? Does it mean that by finalizing 
> the wrapper, there's nobody referencing DBConnection, so that the system is at 
> liberty to garbageCollect and finalize it at any time it likes?

it means "given back to the resource pool" as you already discovered.

> Also, I need to look up: when an object finalises, isn't it supposed to first 
> run finalise on all of it's internal Objects? or is finalising done in a total 
> unsynchronised manner?

unfortunately yes, finalization is done completely unorderly. see JLS
