### ISSUE TITLE
strange NPE with mysql 4

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#135]
**Reported by @cristianbogdan on 17 Feb 2003 16:33 UTC**
there was a NPE that confused ITD for some days

i ran the server with -Xint and finally saw the stacktrace. it may be that the
problem is "session already closed", which appears with jdbc3, also on
SQLDBConnection.getPreparedStatement()

we ran the server with JDK 1.4 for 1 day, there was no problem. when running
with 1.4.1, it appeared in some minutes. this may denote a 1.4.1 problem but we
can't be sure.

since we didn't see this problem on tallinn, i tend to think that it's related
to mysql4

java.lang.NullPointerException
	at com.mysql.jdbc.PreparedStatement.<init>(Unknown Source)
	at com.mysql.jdbc.jdbc2.PreparedStatement.<init>(Unknown Source)
	at com.mysql.jdbc.jdbc2.Connection.prepareStatement(Unknown Source)
	at com.mysql.jdbc.jdbc2.Connection.prepareStatement(Unknown Source)
	at org.makumba.db.sql.SQLDBConnection.getPreparedStatement(SQLDBConnection.java:23)
	at org.makumba.db.sql.Query.execute(Query.java:50)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:157)
	at org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:21)
	at org.makumba.view.AttributeParametrizer.execute(AttributeParametrizer.java:151)
	at
org.makumba.view.MultipleAttributeParametrizer.execute(MultipleAttributeParametrizer.java:24)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:305)
	at org.makumba.view.jsptaglib.QueryStrategy.doQuery(QueryStrategy.java:409)
	at org.makumba.view.jsptaglib.RootQueryStrategy.onInit(RootQueryStrategy.java:62)
	at org.makumba.view.jsptaglib.RootData.setStrategy(RootData.java:43)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:116)
	at org.apache.jsp.personalBox$jsp._jspService(personalBox$jsp.java:72)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

Migrated-From: http://trac.makumba.org/ticket/307

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 20 Feb 2003 12:44 UTC**
this is most probably a finalization problem due to bug 314

makumba 0.5.5.21 should work with jdbc 2, with both mysql 3 and 4 without this
bug surfacing. it will also work with jdbc 3, since bug 301 is solved too by the
fix to bug 314

*** This bug has been marked as a duplicate of 314 ***
