### ISSUE TITLE
[jasper2] maxCountVar is null if loop is not done

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#137]
**Reported by @cristianbogdan on 18 Feb 2003 16:29 UTC**
Gwen says:

2/ Archive and events, while trying to open a doc or an event, return 
errors like:

URL: http://devel.best.eu.org/events/event.jsp?event=7cvxglu

java.lang.NullPointerException
	at org.apache.jsp.event_jsp._jspService(event_jsp.java:174)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
...

I fixed the error by a null check but it seems that maxCountVar should be 0 if
no looping is done.

This error does not appear with Jasper1

Migrated-From: http://trac.makumba.org/ticket/310

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 17 Mar 2003 11:44 UTC**
we may have to re-open this when more use of jasper2 is made, but my tests were
succesful. this seems to be a jasper2 bug but i worked it around
(org.makumba.view.jsptaglib.CountTEI revision 1.3)
