### ISSUE TITLE
mak:input chooser for int set {} dataType becomes textbox if value= is given

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#14]
**Reported by @frederikhabils on 17 Oct 2002 21:01 UTC**
noticed with the an mdd field (canEmail) of type: int{"No"=0, "Yes"=1 }

in editForm: <mak:input name="canEmail"/> is a dropdown, with default = No

trying to set default to Yes by doing:
<mak:input name="canEmail" value="\"Yes\""/>
or 
<mak:input name="canEmail" value="1"/>

changes the edit control in a textbox (with the requested preset value) instead 
of keeping a dropdown select.

--
It becomes more bizarre:
putting more input controls next to each other

<mak:input name="canEmail" value="1" /> 
<mak:input name="canEmail" value="\"Yes\""/> 
=> 2x _textbox_ with default: 1, Yes  ==> NOK!

<mak:input name="canEmail"  />
<mak:input name="canEmail" value="\"Yes\""/> 
=> 2x _dropdown_ with default: No, No ==> NOK!

<mak:input name="canEmail"  />
<mak:input name="canEmail" value="1"/> 
=> 2x _dropdown_ with default: blank, No    ==> OK!

<mak:input name="canEmail"  />
<mak:input name="canEmail" value="1" /> 
<mak:input name="canEmail" value="\"Yes\""/> 
=> 3x dropdown with default: No, Yes, No    ==> NOK

possible WORKAROUND under test:
<mak:input name="canEmail" display="false" /><mak:input name="canEmail" 
value="1" /> 

(still need to test if the submit will be ok... don't have the response page 
ready to do so)

Migrated-From: http://trac.makumba.org/ticket/17

**Comment by ghost** [comment]
**Comment by @stefanb on 17 Oct 2002 21:48 UTC**
A possible workaround is to reverse the order of enumeration in MDD, with 
keeping the values, so that:
canEmail=int{"No"=0, "Yes"=1 } 
becomes
canEmail=int{"Yes"=1, "No"=0 }

But will be looked into more thoroughly, because it might be needed for other 
fields that might require logical ordering with default value somewhere in the 
middle (eg T-shirt size would have default L, but ordered XS,S,M,L,XL,XXL)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 9 Jun 2003 12:02 UTC**
about "trying to set the default" (comment 0), why would you set a default in an
editForm? in editForm, value should clearly show what is edited, unless the
thing is null... or? i guess what you are asking here is some kind of support
for "default in case of null"?

for the rest, i think that changing the control to textbox is a bug due to badly
determined type, so more page analysis should be used

**Comment by ghost** [comment]
**Comment by @frederikhabils on 10 Jun 2003 13:55 UTC**
> why would you set a default in an editForm? 

- indeed, most of the time it will be for value-in-case-of null.

- in the case here, I used it to force the default answer to "can BEST email 
you ..." to Yes. Actually, I prob. wanted the "yes" only to be forced if value 
is Nil, but I forced it on all editing (as I said, probably by mistake).
 cvs:/karamba/public_html/johnny/student/general/personalDataEdit.jsp

- it should be checked if this error only occurs in editForm (or also in 
newForm, addForm).

- but this is also used in my try-out documented in bug 281 comment 1, which 
does: form submits to itself; if the validation fails, the editForm is not 
using the values from the db, but the input fields are preset to the values 
that were submitted before. 


Summarizing: 
forcing values on input fields in editForm is not frequent, but can happen.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 10 Jun 2003 19:50 UTC**
i've made some test cases, in fred-k/test
(this also in regard to bug 451 comment 6)

https://parade.best.eu.org/fred-k/test/bug17edit.jsp
https://parade.best.eu.org/fred-k/test/bug17add.jsp
https://parade.best.eu.org/fred-k/test/bug17new.jsp
(note: comment text in these files refers to results in 0.5.8.6)

they make use the general.Country mdd to try out intEnum editing.
https://parade.best.eu.org/fred-k/dataDefinitions/general.Country


Conclusions for 0.5.8.6
-----------------------
<mak:input name="intEnumField"  value="1" />
   addForm : will be a textbox instead of chooser (*)
   editForm: will be a textbox instead of chooser (*)
   newForm : will NOT compile (NPE)

<mak:input name="intEnumField" value="$defaultVal" />
   addForm : will work OK 
   editForm: will NOT compile (cannot determine input type...)
   newForm : will work OK 

(*) with workaround as mentioned in comment 0


Conclusions for 0.5.5.29 (demo-k)
------------------------
<mak:input name="intEnumField"  value="1" />
   addForm : will be a textbox instead of chooser (*)
   editForm: will be a textbox instead of chooser (*)
   newForm : will NOT compile

<mak:input name="intEnumField" value="$defaultVal" />
  editForm,addForm,newForm: will NOT compile (cannot determine input type...)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 10 Jun 2003 23:01 UTC**
i don't think i agree on having value= to set a default. value= means that
whatever there is in the db, you're forcing another value in the form

so i propose a new attribute, defaultValue=...

i think the problem with this bug and with bug 451 is that i never thought that
somebody will try forcing another value than the one in the db. ok, i agree that
that should be supported (in which case, the value from the db will not even be
read), but i think that is a different case from having a default value.

does this make sense? i wonder which is the more frequent need: the default
value if null, or forcing another value?

**Comment by ghost** [comment]
**Comment by @frederikhabils on 22 Jun 2003 10:06 UTC**
the WORKAROUND for this bug, mentioned in comment 0 and comment 4, 
does NO longer work in makumba 0.5.9

as witnessed in 
https://parade.best.eu.org/mak-test-k/test/bug17edit.jsp (0.5.9)
https://parade.best.eu.org/fred-k/test/bug17edit.jsp (0.5.8.8)

this workaround is used in production pages:
https://parade.best.eu.org/mak-test-
k/johnny/student/general/personalDataEdit.jsp
(where it is actually not doing what I intended (=defaultVar), see comment 3, 
but anyway)

... and maybe other pages... dunno by heart. 

___

Answer to comment 5: 
defaultVar is definitely good enhancement. Forcing another value is needed 
very rarely. I've only found one real use for it: the case described in bug 
281 comment 1. (Even so, I think it should work correctly)

**Comment by ghost** [comment]
**Comment by @frederikhabils on 26 Jun 2003 21:40 UTC**
i tested performance of 0.5.9.3 for this bug, using testfiles mentioned in
comment 4 (but then used in mak-test-k)

... and the behaviour has changed again compared to previous tests. Reminds me
of a yoyo I had when I was a kid... Yoyo was more fun though.


Conclusions for 0.5.9.3
-----------------------
<mak:input name="intEnumField"  value="1" />
   addForm : will not compile [  editForm: will not compile [err2](err1]
)
   newForm : will not compile [=> ???

<mak:input name="intEnumField" value="$defaultVal" />
   addForm : works OK 
   editForm: works OK
   newForm : works OK 

-> so, extra points for consistency at least :-)


[err1](err3])
computed type for INPUT is different from the indicated dataType: INPUT
name=status value=1 dataType=null has dataType indicated to intEnum type
computed is int

[type for INPUT is different from the indicated dataType: INPUT
name=inSchengen value=1 dataType=null has dataType indicated to intEnum type
computed is int


[err3](err2]
computed) => this seems to be sth very different

org.makumba.MakumbaError: unknown query for key null
	at
org.makumba.view.jsptaglib.MakumbaJspAnalyzer$PageCache.getQuery(MakumbaJspAnalyzer.java:70)
	at org.makumba.view.jsptaglib.ValueComputer.getValueComputer(ValueComputer.java:22)
	at org.makumba.view.jsptaglib.InputTag.doStartAnalyze(InputTag.java:89)
	at
org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.addTag(MakumbaJspAnalyzer.java:108)
	at
org.makumba.view.jsptaglib.MakumbaJspAnalyzer.simpleTag(MakumbaJspAnalyzer.java:186)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:350)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:292)
	at org.makumba.util.JspParseData.parse(JspParseData.java:205)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 27 Jun 2003 08:31 UTC**
ok, this seems to be drawing to a close
i copied the test cases to my machine, will investigate

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 30 Jun 2003 07:42 UTC**
fixed in 0.5.9.4

"$something", "1", "nil", "'Yes'" are now all accepted as values. see also bug 375
