### ISSUE TITLE
all-zero dates are returned as null

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#151]
**Reported by @cristianbogdan on 14 Mar 2003 13:51 UTC**
 

Migrated-From: http://trac.makumba.org/ticket/342

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 14 Mar 2003 13:59 UTC**
an OQL like 
SELECT p.birthdate as theDate FROM general.Person p WHERE p.birthdate<>nil 
will generate a Dictionary with no "theDate" key (as if p.birthdate would be
null) _if_ the date is stored in mysql as 0000-00-00 00:00:00

this is pretty confusing. such data should not appear in mysql anyway, but when
it does, this is what we have.

plus, if the thing happens at JDBC level, it's pretty hard to overcome it... it
may be a jdbc driver bug in the ResultSet.wasNull() method.  would be nice to
know if this happens with the old JDBC driver.

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 6 Jun 2009 13:20 UTC**
with the current JDBC connector, querying for a timestamp that is '0000-00-00 00:00:00' leads to an exception:

org.makumba.commons.RuntimeWrappedException: org.makumba.DBError: java.sql.SQLException: Cannot convert value '0000-00-00 00:00:00' from column 1 to TIMESTAMP.
	at org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:112)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:174)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:874)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
	at java.lang.Thread.run(Thread.java:613)
Caused by: org.makumba.DBError: java.sql.SQLException: Cannot convert value '0000-00-00 00:00:00' from column 1 to TIMESTAMP.
	at org.makumba.db.makumba.sql.Query.goThru(Query.java:166)
	at org.makumba.db.makumba.sql.Query.execute(Query.java:137)
	at org.makumba.db.makumba.DBConnection.executeQuery(DBConnection.java:193)
	at org.makumba.db.makumba.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:79)
	at org.makumba.devel.DataQueryServlet.doGet(DataQueryServlet.java:117)
	at org.makumba.devel.DataToolsControllerHandler.beforeFilter(DataToolsControllerHandler.java:51)
	at org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:90)
	... 14 more
Caused by: java.sql.SQLException: Cannot convert value '0000-00-00 00:00:00' from column 1 to TIMESTAMP.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1321)
	at com.mysql.jdbc.ByteArrayRow.getTimestampFast(ByteArrayRow.java:124)
	at com.mysql.jdbc.ResultSetImpl.getTimestampInternal(ResultSetImpl.java:6617)
	at com.mysql.jdbc.ResultSetImpl.getTimestamp(ResultSetImpl.java:5943)
	at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:4901)
	at org.makumba.db.makumba.sql.TableManager.get_dateTime_Value(TableManager.java:990)
	at org.makumba.db.makumba.sql.TableManager.getValue(TableManager.java:875)
	at org.makumba.db.makumba.sql.TableManager.fillResult(TableManager.java:831)
	at org.makumba.db.makumba.sql.Query.goThru(Query.java:161)
	... 20 more
Caused by: java.sql.SQLException: Value '[B@c8331b' can not be represented as java.sql.Timestamp
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.ResultSetRow.getTimestampFast(ResultSetRow.java:1027)
	... 28 more


I dont't think that this exception should be fetched and dealt with by Makumba other than this is now (i.e. thrown further to the programmer as DBError). Also, I do not see in which situation we should have such "zero timestamps".

So I am closing this bug, feel free to object.
