### ISSUE TITLE
browsing for mdds under "/dataDefinitions" fails

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#152]
**Reported by @cristianbogdan on 14 Mar 2003 15:00 UTC**
http://private.best.eu.org/dataDefinitions/general.survey.Response works
http://private.best.eu.org/dataDefinitions/ fails
http://private.best.eu.org/dataDefinitions  fails

i think this has to do with the fix to bug 173, in the sense that some mddLinker
code was relying on the bug 173 to discover MDD directory names

this bug manifests differently on windows and unix. if the server runs on linux,
there will be a 404. if it runs on windows, empty pages are served

the linux stacktrace (seen in server-output) is like this:

java.io.FileNotFoundException: /
        at org.makumba.devel.LineViewer.readFromURL(LineViewer.java:49)
        at org.makumba.devel.mddViewer.<init>(mddViewer.java:44)
        at org.makumba.devel.SourceViewServlet.doGet(SourceViewServlet.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:740)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)

Migrated-From: http://trac.makumba.org/ticket/343

**Comment by ghost** [comment]
**Comment by @stefanb on 14 Mar 2003 18:16 UTC**
now mddViewer is calling RecordParser.findDataDefinitionOrDirectory(), which is
as it was before fixing bug 173 (except for the name).
Of course now there is another RecordParser.findDataDefinition(), which calls
the above and returns null if it is a directory (ends with '/')

**Comment by ghost** [comment]
**Comment by stefanba on 15 Nov 2010 16:45 UTC**
(In [76]) fixed bug 343 (browsing for mdds under "/dataDefinitions" fails)
