### ISSUE TITLE
NullPointerException at org.makumba.db.sql.ParameterAssigner.assignParameters ?

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#158]
**Reported by @frederikhabils on 20 Mar 2003 20:21 UTC**
Farry discovered that the page http://private.best.eu.org/groups/group.jsp
was throwing this error, for every tried ?team=ptr :

Internal Makumba error
Please report to the developers

java.lang.NullPointerException
	at org.makumba.db.sql.ParameterAssigner.assignParameters
(ParameterAssigner.java:63)
	at org.makumba.db.sql.Query.execute(Query.java:75)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:180)
	at org.makumba.db.DBConnectionWrapper.executeQuery
(DBConnectionWrapper.java:44)
	at org.makumba.view.AttributeParametrizer.execute
(AttributeParametrizer.java:174)
	at org.makumba.view.MultipleAttributeParametrizer.execute
(MultipleAttributeParametrizer.java:47)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:328)
	at org.makumba.view.jsptaglib.QueryStrategy.doQuery
(QueryStrategy.java:432)
	at org.makumba.view.jsptaglib.RootQueryStrategy.onInit
(RootQueryStrategy.java:85)
	at org.makumba.view.jsptaglib.RootData.setStrategy(RootData.java:66)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:146)
	at org.apache.jsp.group$jsp._jspService(group$jsp.java:624)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

The problem disappeared after a Karamba reload. No ideas what it was. Karamba 
had been reloaded a few times today, as far as I could tell.

Migrated-From: http://trac.makumba.org/ticket/354

**Comment by ghost** [comment]
**Comment by @frederikhabils on 30 Jun 2003 12:18 UTC**
Nobody has seen this since, so I suggest to invalidate this bug, by lack of
cases to study.
