### ISSUE TITLE
Wrong handler function is executed for mak:form because of identical jsp filenames

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#164]
**Reported by @frederikhabils on 24 Mar 2003 23:06 UTC**
We discovered that bug 361 is caused by the fact that, after a reload, Makumba 
has started to use the wrong handler function (same function name, wrong 
class).

password recovery feature in PATS and in JohnnyTS are +-identical : same 2 
step procedure, same mak:form's, same file names, same handler function name. 
Only difference: files are in different folders, and handler functions 
(executing different queries) are in different classes (and different 
packages). 

PATS:
http://private.best.eu.org/forgotPass.jspx
http://private.best.eu.org/forgotPassResponse.jspx
http://private.best.eu.org/classes/org.eu.best.privatearea.ForgotLogic#19

Johnny:
http://private.best.eu.org/johnny/student/register/forgotPass.jspx
http://private.best.eu.org/johnny/student/register/forgotPassResponse.jspx
http://private.best.eu.org/classes/org.eu.best.johnny.StudentLogic#340

Yet still, after a karamba reload, Makumba started to use the PATS handler 
function for the Johnny forgotPass.jsp mak:form.

This is the related output on the log, showing that the BL lookup went ok, but 
then wrong function gets executed. 

- - - - - - > 
Found class org.eu.best.johnny.StudentRegisterLogic
Mar 23, 2003 10:51:04 AM org.makumba.view.jsptaglib.MakumbaTag response
INFO: logic exception
org.makumba.LogicException: Password recovery failed. Go back and correct: No 
existing account is matching this username and date of birth.
        at org.eu.best.privatearea.ForgotLogic.passwordRecovery
(ForgotLogic.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:324)
        at org.makumba.abstr.Logic.doOp(Logic.java:331)
        at org.makumba.view.jsptaglib.SimpleFormResponder.respondTo
(FormTagBase.java:168)
        at org.makumba.view.jsptaglib.MakumbaTag.response(MakumbaTag.java:241)
        at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:133)
        at org.apache.jsp.forgotPassResponse$jsp._jspService
(forgotPassResponse$jsp.java:72)
< - - - - - -

bug 361 will be solved (hopefully) by changing the function name.

Migrated-From: http://trac.makumba.org/ticket/362

**Comment by ghost** [comment]
**Comment by @frederikhabils on 25 Mar 2003 18:47 UTC**
bug 361 has reappeared, in spite of renaming the handler functions. So we dig 
deeper for the makumba problem.

I have collected new and interesting evidence though in parade

it seems that PATS and Johnny password recovery can not coexist:

after a reload:

- if PATS-forgotPass.jsp is visited first, 
  then johnny-forgotPass.jsp response will be the PATS handler function
- and vice versa... if Johnny-forgotPass.jsp is visited first, 
  then PATS forgotPass.jsp response will call the johnny handler function.

(note: i'm only visiting the XXX-forgotPass.jsp, not even submitting the form)

==> 

in the stacktrace I mentioned above, the handler function to call, is 
identified in this step:
        at org.makumba.view.jsptaglib.MakumbaTag.response(MakumbaTag.java:241)

in this function, it gets the __makumba__responder__ value 
from the form, and then executes the method that was associated 
(by the form) to that value. 
So the error would be in the form page somehow, that is 
constructing wrong responder IDs.

==> so lets compare the forms themselves:

- same file name, different folders
- almost identical mak:form, with BL in different classes, function 
differently named (passwordRecovery vs. johnnyPasswordRecovery)
- _both_ are translated by jsp compiler to
     org.apache.jsp.forgotPassResponse$jsp 
  (in different location in karamba/tomcat/work/Standalone/localhost/_/)
        ...
	package org.apache.jsp;
	public class forgotPass$jsp extends HttpJspBase {
        ...

So, I'm wondering if the fact that the 2 jsp result in java class 
with "identical" name, can fool the makumba formResponder identification ?

**Comment by ghost** [comment]
**Comment by @frederikhabils on 25 Mar 2003 18:52 UTC**
when i said above:
> So the error would be in the form page somehow, that is 
> constructing wrong responder IDs.

i meant: 
the error would be that makumba is assigning the wrong handler to the 
responderID that is sent along with the form.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 25 Mar 2003 20:24 UTC**
indeed, identical class names are generated by tomcat for identical jsp file names
now that's a Jasper (JSP compiler) problem i would guess. not a makumba problem

you might want to search in tomcat's bugzilla, at jasper1, which is i think
deprecated by now, but we still use it due to problems with jasper2

ant tomcatJ2 will start a standalone karamba (like private:11666) with jasper2.
so you might want to try if the bug occurs with jasper2 too

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 25 Mar 2003 21:05 UTC**
Fred asked me if the identical class names can influence makumba

for one thing, i have problems (at this late hour) understanding how a
classloader can load classes with identical names generated from different pages...

for another thing, i remember vaguely that makumba composes some caching keys
based on the class name (i remember assuming that the class name would not only
based on the JSP name but on the complete URI). now i know that that assumption
is wrong, but it was made a very long ago (2001) and it didn't yet hit back :).
it probably does now.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 25 Mar 2003 22:35 UTC**
i can confirm that changing the filename of one of the 2 conflicting forms, 
has taken away the handler mixup described in detail in comment 1. 

To solve the bug 361 i did:
copy forgotPass.jsp to recoverPass.jsp
edit forgotPass.jsp : <jsp:forward page="recoverPass.jsp" />

that way i didn't have to change any links.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 25 Mar 2003 23:17 UTC**
about comment 4:
a very quick search turned up this related discussion: 

http://w6.metronet.com/~wjm/tomcat/2001/Feb/msg00293.html
http://w6.metronet.com/~wjm/tomcat/2001/Feb/msg00298.html

which says, among other things:
--
There is no need for all this complexity to generate a package name
in the new Jasper.  The way jasper now loads jsp pages, each page is
completely isolated from all other pages.  Every jsp page compiled 
could be a class named "org.apache.jsp.MyJSP" without
any concern whatsoever about conflicts because each individual page
has its own class loader.  I will modify the current jasper class loader
to support putting the jsp pages in a package, but this is just to comply
with the JSP 1.2 spec.
--

**Comment by ghost** [comment]
**Comment by @stefanb on 22 May 2003 17:08 UTC**
Now that we have a controller filter (bug 6) done.... 
..is the good sideeffect of it that this one got fixed as well?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 22 May 2003 18:50 UTC**
> Now that we have a controller filter (bug 6) done.... 
> ..is the good sideeffect of it that this one got fixed as well?

hmmm, unfortunatey not. separating the controller is mostly a refactoring, i.e.
the system behaves generally the same way. the only real problem solved is
"first makumba tag" i.e. logic is not found/called at first makumba tag, but
before the page starts

i think the problem is something like:
QueryTag.java:66:			 (pageContext.getPage().getClass())), 

i.e. a caching after a page class name, which (as confirmed in comment 5) can
coincide for two pages...

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 24 May 2003 00:45 UTC**
my example in comment 8 is not good. pageContext.getPage().getClass() will be 
different for pages with the same name. however, pageContext.getPage().getClass
().getName() will be identical. so the solution to this bug may still be 
somewhere along these lines.


aaaah, i found it: in org.makumba.view.jsptaglib.FormTagBase revision 1.2 (part 
of makumba-0.5.5.22), line 63, there is

  public String getFormKey(){ return 
action+method+name+message+enclosingLabel+pageContext.getPage().getClass(); }

getPage.getClass() concatenated in a string will result in getPage().getClass
().toString() => identical results

the method is called by org.makuma.view.jsptaglib.FormResponder revision 1.2, 
method responderKey(), line 97... in turn, the hash code of the responderKey() 
is the value written at __makumba__responder__ (comment 1, comment 2). since 
responder keys are indentical, their hash will be identical => the wrong 
responder is invoked

this bug is not any more in 0.5.7.x (so comment 7 is right), because the 
responder key computation was changed
(org.makumba.controller.html.FormResponder, 
org.makumba.controller.http.Responder) and is only depdendent on the form 
structure and BL class. since the BL class is definitely different for the two 
forms, there will be no more colision
