### ISSUE TITLE
Stricter type checking by mak 0.5.7 in case of intEnum and use of dataType="..."

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#171]
**Reported by @frederikhabils on 27 Mar 2003 22:52 UTC**
while testing 0.5.7, i encountered error on 
https://parade.best.eu.org/fred-k/helpdesk/welcome.jspx

org.makumba.InvalidValueException: computed type for INPUT is different from 
the indicated dataType: INPUT name=status value=$unsolved dataType=int has 
dataType indicated to int type computed is intEnum , value known is 0

	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:120)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:141)
	at org.apache.jsp.welcome$jsp._jspService(welcome$jsp.java:133)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

line 24 seems to be the offending code:
<mak:input type="hidden" name="status" value="$unsolved" dataType="int"/>

helpdesk.Request#status is of type intEnum. The dataType in the tag seems to 
be conflicting (unlike for mak 0.5.5.x)

Probably to be classified as "not a makumba bug, correct the application".

Migrated-From: http://trac.makumba.org/ticket/371

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 28 Mar 2003 09:16 UTC**
yes, 0.5.7's InputTag has recently got a more strict type check, though i didn't
intend the effect you report (which seems to be correct, nevertheless). this is
one of the reasons that i tended to put all my changes in 0.5.7 which is further
away from production and more prone to be tested.

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 30 Mar 2003 18:31 UTC**
Trying to change dataType from "int" to "intEnum" 
(https://parade.best.eu.org/fred-k/helpdesk/welcome.jspx, line 24), I got the 
following error:

java.lang.NullPointerException
	at org.makumba.abstr.intEnumHandler.checkValueImpl
(intEnumHandler.java:64)
	at org.makumba.abstr.FieldHandler.checkValue(FieldHandler.java:61)
	at org.makumba.abstr.FieldInfo.checkValue(FieldInfo.java:138)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:127)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:141)
	at org.apache.jsp.welcome$jsp._jspService(welcome$jsp.java:133)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

Neither int nor intEnum datatypes do throw errors with 0.5.5.27
Maybe a mak bug at the end?

**Comment by ghost** [comment]
**Comment by @frederikhabils on 30 Mar 2003 21:52 UTC**
Actually, there seems to just have been a type mismatch in the value that was 
pre-set to the field Request#status, which is int{"New"=0, ...}

The old code was (accepted by mak 0.5.5.27 but not by 0.5.7:

pageContext.setAttribute("unsolved",(String)"0"); 
[...]
<mak:input type="hidden" name="status" value="$unsolved" dataType="int"/>

Correct code is
pageContext.setAttribute("unsolved", new Integer(0) ); 
<mak:input type="hidden" name="status" value="$unsolved" />

or alternatively

pageContext.setAttribute("unsolved", "New" ); 
<mak:input type="hidden" name="status" value="$unsolved" />

--
So there is just no need to specify dataType="..." at all, this is known from 
the MDD. And the preset value must be of appropriate type.


It just seems that older makumba was more lenient in accepting mixed up types. 

As from what I remember from software engineering classes: loose-type checking 
makes it easy to write, strict-type checking makes it easy to detect bugs 
early :-)

**Comment by ghost** [comment]
**Comment by @frederikhabils on 30 Mar 2003 22:24 UTC**
"interestingly" the code in comment 3 doesn't work in makumba .5.5.27, where 
it insists on having dataType="int" in the tag, to work.

Finally, i discovered that the much simpler 

<mak:input type="hidden" name="status" value="0" />

... is acceptable for both 0.5.5 and 0.5.7

**Comment by ghost** [comment]
**Comment by @stefanb on 30 Mar 2003 23:04 UTC**
just want to remind you that such code exists also on public website
http://www.best.eu.org/helpdesk/welcome.jspx

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 31 Mar 2003 00:11 UTC**
public website: actually waiting for 0.5.5.27 in production for the fix to be 
working there..

Correction comment 4: acceptable for both 0.5.5.27 and 0.5.7

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 31 Mar 2003 00:42 UTC**
comment 4:
> "interestingly" the code in comment 3 doesn't work in makumba .5.5.27, where 
> it insists on having dataType="int" in the tag, to work.

this is why i introduced the stricter type check in the first place. the
dataType should not be supplied when it is available from the MDD. 

the NPE in comment 2 is indeed a bug but i already fixed that in my work to fix
this and bug 372

i am glad that you also seem to believe that stricter type checking is better. i
hope there won't be many things to fix in karamba due to this change. you will
see that during testing.
