### ISSUE TITLE
mak:input fails for fields of type "external set" in mak:editForm, OK in mak:add/newForm

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#172]
**Reported by @frederikhabils on 27 Mar 2003 23:19 UTC**
mak:input seems to fail for fields that are external sets "fieldA = set TypeB-
ptr" (usually shown as a multiple select box)

The error is:

Internal Makumba error
Please report to the developers

java.lang.NullPointerException
	at org.makumba.InvalidValueException.<init>
(InvalidValueException.java:41)
	at org.makumba.abstr.ptrIndexHandler.checkValueImpl
(ptrIndexHandler.java:43)
	at org.makumba.abstr.setHandler.checkValueImpl(setHandler.java:54)
	at org.makumba.abstr.FieldHandler.checkValue(FieldHandler.java:61)
	at org.makumba.abstr.FieldInfo.checkValue(FieldInfo.java:138)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:127)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:141)
	at org.apache.jsp.edit_0005fwork2$jsp._jspService(edit_0005fwork2
$jsp.java:251)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

This can be evidenced at 
https://parade.best.eu.org/fred-k/minerva/student/mycv/edit_work2.jsp#start
-> best.Student#interests = set general.ActivityField ;Professional interests
https://parade.best.eu.org/fred-k/dataDefinitions/best.Student#31

and also at
https://parade.best.eu.org/fred-k/events/coordinator/eventEdit.jsp?
event=7bhzhp3
-> organisers= set general.Person
-> organisingLBGs= set best.internal.Lbg; Organising LBG

Migrated-From: http://trac.makumba.org/ticket/372

**Comment by ghost** [comment]
**Comment by @frederikhabils on 27 Mar 2003 23:22 UTC**
another example, same deal
https://parade.best.eu.org/fred-k/groups/admin/groupEdit.jsp?team=ehabgr8

**Comment by ghost** [comment]
**Comment by @frederikhabils on 27 Mar 2003 23:51 UTC**
I've discovered that the this problem with mak:input for external sets, 
appears in mak:editForm, 
but NOT in mak:addForm / newForm

Evidence of working in addForm:
https://parade.best.eu.org/fred-
k/johnny/student/general/personalDataEditSets.jsp?
action=add&education=null#startEd
(adding education to the personal info in Johnny)

Evidence of working in newForm:
https://parade.best.eu.org/fred-k/events/coordinator/eventAnnounce.jspx
12:	<br>Organising LBGs: <mak:input field="organisingLBGs"/>


Have not yet been able to test in mak:form

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 31 Mar 2003 01:35 UTC**
the test cases work now 
fixed in org.makumba.view.jsptaglib.InputTag revision 1.1.1.1.2.5

**Comment by ghost** [comment]
**Comment by cristian_bogdan on 15 Nov 2010 16:46 UTC**
(In [117]) fixed bug 372, improved type checking
