### ISSUE TITLE
mak:input value syntax

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#174]
**Reported by @cristianbogdan on 31 Mar 2003 00:51 UTC**
it should be mentioned in the doc that the syntax of the value of a <mak:input>
should be in OQL. as such:
- "new" means the OQL label "new". if the mak:input is not inside a
mak:list/object, this makes no sense
- "$new" is an attribute (not really OQL syntax, but makumba JSP-OQL syntax). 
- "\'new\'" is a string constant
- "\'2003-03-28\'" is a date constant. never tried this one
- "0" is an integer constant

as per bug 371, the value should strictly be of the type required by the input data

Migrated-From: http://trac.makumba.org/ticket/375

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 30 Jun 2003 07:40 UTC**
some more things here (supported in 0.5.9.4)

"nil" is the OQL nil, assignable to any type (except for set maybe?)
"'aString'" is a string but may be assignable to an intEnum (see bug 17). note
that the string ' quotes need not necessarily be escaped (as in comment 0)

**Comment by ghost** [comment]
**Comment by @frederikhabils on 30 Jun 2003 14:31 UTC**
comment 1 says "nil" is assignable to any dataType

I tried assigning it to intEnum and setIntEnum, and both failed

 <mak:input name="letter" value="nil" dataType='int{"A"=0, "B"=1, "C"=2}'/>
 <mak:input name="letter" value="nil" dataType='set int{"A"=0, "B"=1, "C"=2}'/>


java.sql.SQLException: Syntax error or access violation,  message from server:
"You have an error in your SQL syntax.  Check the manual that corresponds to
your MySQL server version for the right syntax to use near '' at line 1"
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1651)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:889)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:956)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:1874)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1538)
	at org.makumba.db.sql.Query.execute(Query.java:85)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:180)
	at org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:44)
	at org.makumba.view.AttributeParametrizer.execute(AttributeParametrizer.java:174)
	at
org.makumba.view.MultipleAttributeParametrizer.execute(MultipleAttributeParametrizer.java:47)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:332)
	at org.makumba.view.jsptaglib.QueryExecution.<init>(QueryExecution.java:88)
	at org.makumba.view.jsptaglib.QueryExecution.getFor(QueryExecution.java:76)
	at org.makumba.view.jsptaglib.FormTagBase.doMakumbaStartTag(FormTagBase.java:128)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:171)


mmm, should we make a technical (instead of doc-) bug for this?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 30 Jun 2003 15:09 UTC**
> comment 1 says "nil" is assignable to any dataType

well, it should be "any non-set data type"...

not sure how to indicate values for sets but there's no such thing as a nil set.

i will have to look into this. see bug 505, which goes on my list. for now the
doc should just say "non-set type" for all values (not only nil)

**Comment by ghost** [comment]
**Comment by @frederikhabils on 2 Jul 2003 10:41 UTC**
i hope i wasn't fooled by bug 504 when I did testing of comment 2...

but I also got this error on intEnum. Is intEnum a set-type?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 22 Aug 2003 11:43 UTC**
> but I also got this error on intEnum. Is intEnum a set-type?

no, that's probably a bug, please reproduce and fill in

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Apr 2016 12:17 UTC**
value="OQL expression" is what happens today.
OQL constants are recognized for char, int, but not for date (though that may work as well)

whatever works should be tested and documented.
