### ISSUE TITLE
ArrayIndexOutOfBonds FirstLoadError

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#176]
**Reported by @cristianbogdan on 15 Apr 2003 17:24 UTC**
A code like this (don't mind the non-best data structures, you can see them at 
http://velox.nada.kth.se:8080/dataDefinitions)

<%@ taglib uri="http://www.makumba.org/presentation" prefix="mak" %>
<mak:list from="nomad.Reference r" >
<mak:list from="nomad.Document d" where="d.responseTo=r.base">
<mak:value expr="r.url" var="url" />
<mak:value expr="d.base.submitter.nickname"/>
</mak:list>
</mak:list>

will provoke the error below. what happens is:
- the var="url" correcly provokes a reload
- at the reload, r.url projection is already known and it will be computed by a 
db query, say qURL
- however, after that, a new projection is discovered (d.base.submitter...) 
during the training loop, which makes qURL to gain one more projection (d). 
- the mistake is that qURL is not executed again, so the old qURL result is not 
compatible anymore with the latest qURL version, it is too "narrow" (misses the 
d projection) so there is an ArrayIndexOutOfBonds like below.

i have seen this error many times at the first load. i was never able to 
reproduce it and always thought it's due to the var and printVar, so now i was 
able to separate it from them.

i will document the fix below.

java.lang.ArrayIndexOutOfBoundsException: 2
	at org.makumba.view.jsptaglib.QueryStrategy.getProjectionValue
(QueryStrategy.java:513)
	at org.makumba.view.jsptaglib.QueryStrategy.formatProjection
(QueryStrategy.java:312)
	at org.makumba.view.jsptaglib.QueryStrategy.insertEvaluation
(QueryStrategy.java:277)
	at org.makumba.view.jsptaglib.ValueTag.displayIn(ValueTag.java:130)
	at org.makumba.view.jsptaglib.ValueTag.doStart(ValueTag.java:123)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:141)
	at org.apache.jsp.rw$jsp._jspService(rw$jsp.java:109)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

Migrated-From: http://trac.makumba.org/ticket/384

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 15 Apr 2003 17:31 UTC**
fixed in org.makumba.view.jsptaglib.QueryStrategy revision 1.1.1.1.2.3 

the fix is sensitive, needs regression test
