### ISSUE TITLE
FLE on InputTag: type detection problems?

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#183]
**Reported by @frederikhabils on 19 Apr 2003 10:05 UTC**
testing 0.5.7.2 i got this FLE sequence (only correct after 5 reloads or so)
https://parade.best.eu.org/mak-test-k/lbg/member/memberEdit.jsp?person=hhi4y8a

--- first time:

org.makumba.view.InvalidValueException: Invalid value for 
expression 'bestInvolvement': invalid format parameter 'rows'
	at org.makumba.view.FieldFormatter.checkParam(FieldFormatter.java:77)
	at org.makumba.controller.html.FieldEditor.checkParam
(FieldEditor.java:22)
	at org.makumba.view.FieldFormatter.checkParams(FieldFormatter.java:67)
	at org.makumba.view.RecordFormatter.format(RecordFormatter.java:58)
	at org.makumba.controller.html.FormResponder.format
(FormResponder.java:46)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:132)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:141)
	at org.apache.jsp.memberEdit$jsp._jspService(memberEdit$jsp.java:1017)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	

--- second time:

org.makumba.view.InvalidValueException: Invalid value for 
expression 'student.person.allergies': invalid format parameter 'rows'
	at org.makumba.view.FieldFormatter.checkParam(FieldFormatter.java:77)
	at org.makumba.controller.html.FieldEditor.checkParam
(FieldEditor.java:22)
	at org.makumba.view.FieldFormatter.checkParams(FieldFormatter.java:67)
	at org.makumba.view.RecordFormatter.format(RecordFormatter.java:58)
	at org.makumba.controller.html.FormResponder.format
(FormResponder.java:46)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:132)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:141)
	at org.apache.jsp.memberEdit$jsp._jspService(memberEdit$jsp.java:882)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

--- third time

org.makumba.view.InvalidValueException: Invalid value for 
expression 'bestStarted': invalid format parameter 'format'
	at org.makumba.view.FieldFormatter.checkParam(FieldFormatter.java:77)
	at org.makumba.controller.html.FieldEditor.checkParam
(FieldEditor.java:22)
	at org.makumba.view.FieldFormatter.checkParams(FieldFormatter.java:67)
	at org.makumba.view.RecordFormatter.format(RecordFormatter.java:58)
	at org.makumba.controller.html.FormResponder.format
(FormResponder.java:46)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:132)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:141)
	at org.apache.jsp.memberEdit$jsp._jspService(memberEdit$jsp.java:989)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	

--- 4th time

org.makumba.view.InvalidValueException: Invalid value for 
expression 'bestInvolvement': invalid format parameter 'rows'
	at org.makumba.view.FieldFormatter.checkParam(FieldFormatter.java:77)
	at org.makumba.controller.html.FieldEditor.checkParam
(FieldEditor.java:22)
	at org.makumba.view.FieldFormatter.checkParams(FieldFormatter.java:67)
	at org.makumba.view.RecordFormatter.format(RecordFormatter.java:58)
	at org.makumba.controller.html.FormResponder.format
(FormResponder.java:46)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:132)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:141)
	at org.apache.jsp.memberEdit$jsp._jspService(memberEdit$jsp.java:1017)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	

-- 5th time the page was rendered correctly.

Migrated-From: http://trac.makumba.org/ticket/395

**Comment by ghost** [comment]
**Comment by @frederikhabils on 19 Apr 2003 10:11 UTC**
strictly related or not, I don't know...

i just noticed that when, after 5 times the edit page is ok... and then I 
submit it, i get this error. It does not seem to go away, even after 
submitting page 5 times, still same error:


org.makumba.InvalidValueException: Invalid value for 
best.internal.Student#alumniMessage: Required Java type:java.lang.String ; 
given value: did the world change overnight? of type org.makumba.Text
	at org.makumba.abstr.FieldHandler.normalCheck(FieldHandler.java:74)
	at org.makumba.abstr.charHandler.checkValueImpl(charHandler.java:41)
	at org.makumba.abstr.FieldHandler.checkValueImpl(FieldHandler.java:68)
	at org.makumba.abstr.FieldHandler.checkValue(FieldHandler.java:61)
	at org.makumba.abstr.FieldHandler.checkUpdate(FieldHandler.java:96)
	at org.makumba.abstr.RecordHandler.checkUpdate(RecordHandler.java:490)
	at org.makumba.db.DataHolder.checkUpdate(DBConnection.java:385)
	at org.makumba.db.DBConnection.update(DBConnection.java:81)
	at org.makumba.db.DBConnectionWrapper.update
(DBConnectionWrapper.java:53)
	at org.makumba.controller.Logic.doEdit(Logic.java:346)
	at org.makumba.controller.http.Responder$3.respondTo
(Responder.java:258)
	at org.makumba.controller.http.Responder.response(Responder.java:206)
	at org.makumba.controller.http.ControllerFilter.doFilter
(ControllerFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)
[...]

**Comment by ghost** [comment]
**Comment by @frederikhabils on 19 Apr 2003 10:16 UTC**
sorry, CORRECTION to comment 0 

the first error message was :

org.makumba.AttributeNotFoundException: attribute not found: 
makumba.eval.buffer
	at org.makumba.controller.jsp.PageAttributes.getAttribute
(PageAttributes.java:60)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:100)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:141)
	at org.apache.jsp.memberEdit$jsp._jspService(memberEdit$jsp.java:317)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	


I am also getting that error (only the first, not all 4) on newForm, e.g.
https://parade.best.eu.org/mak-test-k/lbg/admin/memberNew.jsp?lbginfo=ge

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 19 Apr 2003 12:48 UTC**
fixed in 0.5.7.3

the reason for this one was that i asked makumba not to do FLE-protection when
the var name is "makumba.eval.buffer" which is the internal variable used by
makumba for <mak:input ...>. FLE-protection is not needed since the eval-buffer
is sure not tobe used in a java scriplet, so not having a correct value during
the training loop is no problem, it will have a correct value in the next loop

there seems to be a bug in the BL of member edit, both
https://parade.best.eu.org/demo-k/lbg/member/memberEdit.jsp?person=fih0wy1
and
https://parade.best.eu.org/mak-test-k/lbg/member/memberEdit.jsp?person=fih0wy1
will give as result
Another person already has your shortname - Please go back and choose another one!
please investigate this.
the other form submission indicated by Fred works, i created a dummy-dummy
member of LBG Gent

**Comment by ghost** [comment]
**Comment by @frederikhabils on 19 Apr 2003 14:14 UTC**
karamba bug described in comment 3 is fixed 

When you edit a person... the BL checks if the shortname chosen is unique... 

previously, it checked in the DB if there is 
_any_person_other_than_logged_in_user, who has that shortname

the check should do:
is there any person other_than_the_user_being_edited... who has that shortname

see version 2.1 of
http://cvs.makumba.org/cgi-bin/cvsweb.cgi/karamba/public_html/WEB-
INF/classes/org/eu/best/privatearea/LbgMemberMemberEditLogic.java

0.5.7.3 seems to be free from the problems reported originally.
