### ISSUE TITLE
IE https: FLE on multipart form submit : no answer

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#185]
**Reported by @frederikhabils on 20 Apr 2003 14:37 UTC**
I haven't found the cause, or pattern, but it seems that:

the following sequence happen:

reload app (e.g. demo-k)
view any official document
click edit link
submit the form (the main one)
  -> there is no answer whatsoever, nothing appearing on log !?!?!?!
submit the same form again -> responds fast.

(the same happens when you edit with the bug-testing page mentioned in bug 275 
comment 2)

Migrated-From: http://trac.makumba.org/ticket/397

**Comment by ghost** [comment]
**Comment by @frederikhabils on 20 Apr 2003 14:58 UTC**
i was suspecting perhaps sth with the docURLhandler or so because the response 
action to this form is "doc/<doc-Nr>"

but changing the action to "document.jsp?document=<doc-ptr>" does not appear 
to change the behaviour.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 20 Apr 2003 20:32 UTC**
interesting bug, but note the version, it's 0.5.5
i'm happy proud to see the FLE protection doing its job in this case :)
we should remember to mark this bug "fixed" when we pass to 0.5.7

**Comment by ghost** [comment]
**Comment by @frederikhabils on 21 Apr 2003 00:29 UTC**
actually, I was unprecise before... I set this to version 0.5.5 just because 
it's also in 0.5.5, not new for 0.5.7. But it IS also occurring in 0.5.7.3

Secondly, I was waiting a bit longer this time, couple of minutes... finally 
after some time, the following error (see below) appeared on the logs, while 
the screen showed a HTTP 500 error (Cannot Find Server)

The same thing is happening to the code that i developped tonight for the 
member-profile images, now with general.Image. While the archive upload has 
the "extra complication" of having a response that is /archive/doc/... and 
thus needs an extra filter to pass, the image upload page has a "normal" 
response page. So the only special thing here seems to be the multipart form. 



StandardWrapperValve[Servlet.service() for servlet ArchiveDoc 
threw exception
javax.servlet.ServletException: Filter execution threw an exception
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:235)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
   at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
   at org.eu.best.tools.TriggerFilter.doFilter(TriggerFilter.java:58)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
   at org.apache.catalina.core.StandardWrapperValve.invoke
(StandardWrapperValve.java:260)
   at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNe
xt(StandardPipeline.java:643)
   at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
   at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
   at org.apache.catalina.core.StandardContextValve.invoke
(StandardContextValve.java:191)
   at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNe
xt(StandardPipeline.java:643)
   at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
   at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
   at org.apache.catalina.core.StandardContext.invoke
(StandardContext.java:2396)
   at org.apache.catalina.core.StandardHostValve.invoke
(StandardHostValve.java:180)
   at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNe
xt(StandardPipeline.java:643)
   at org.apache.catalina.valves.ErrorDispatcherValve.invoke
(ErrorDispatcherValve.java:170)
   at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNe
xt(StandardPipeline.java:641)
   at org.apache.catalina.valves.ErrorReportValve.invoke
(ErrorReportValve.java:172)
   at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNe
xt(StandardPipeline.java:641)
   at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:469)
   at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNe
xt(StandardPipeline.java:641)
   at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
   at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
   at org.apache.catalina.core.StandardEngineValve.invoke
(StandardEngineValve.java:174)
   at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNe
xt(StandardPipeline.java:643)
   at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
   at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
   at org.apache.coyote.tomcat4.CoyoteAdapter.service(CoyoteAdapter.java:223)
   at org.apache.coyote.http11.Http11Processor.process
(Http11Processor.java:405)
   at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnecti
on(Http11Protocol.java:380)
   at org.apache.tomcat.util.net.TcpWorkerThread.runIt
(PoolTcpEndpoint.java:508)
   at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run
(ThreadPool.java:533)
   at java.lang.Thread.run(Thread.java:536)
----- Root Cause -----
org.makumba.MakumbaError: attempt to read the multipart stream twice during 
one request
   at org.makumba.controller.http.MultipartHttpParameters.<init>
(MultipartHttpParameters.java:29)
   at org.makumba.controller.http.RequestAttributes.makeParameters
(RequestAttributes.java:65)
   at org.makumba.controller.http.RequestAttributes.getParameters
(RequestAttributes.java:57)
   at org.makumba.controller.http.Responder.getResponderCodes
(Responder.java:169)
   at org.makumba.controller.http.Responder.response(Responder.java:190)
   at org.makumba.controller.http.ControllerFilter.doFilter
(ControllerFilter.java:33)
   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
   at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
   at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)
[...](ArchiveDoc]:)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 21 Apr 2003 08:52 UTC**
Fred, you didn't mention "upload a file" in the steps-to-reproduce

since this is not a regression bug, i might not fix it now

**Comment by ghost** [comment]
**Comment by @frederikhabils on 21 Apr 2003 10:50 UTC**
it is not necessary to actually upload a file, to reproduce this error. Just 
that the only pattern I found is that this bug appears on First Submit of a 
multipart form (even with the file upload input empty).

it doesn't appear to be regression, it's in 0.5.5 and 0.5.7 according to my 
tests.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 21 Apr 2003 11:40 UTC**
i could not reproduce this in mak-test-k (0.5.7), maybe it only manifests for
certain documents? or for certain browsers? i use mozilla...

in demo-k (0.5.5), i saw a NPE FLE at 
https://parade.best.eu.org/demo-k/archive/officialDocumentEdit.jsp?document=ekr9k26
but could not reproduce afterwards. 
i could not reproduce this bug in demo-k either

**Comment by ghost** [comment]
**Comment by @frederikhabils on 21 Apr 2003 21:32 UTC**
based on your last comment 6, I also compared this behaviour for IE6 and NS7. 
And, lo and behold, NS7 does not have this behaviour at all. 

so, from a fresh reload, loading 

https://parade.best.eu.org/fred-k/archive/doc/20-P-BC-BRD-102
-> click edit
-> submit (no changes to the input fields)

==> NS7 gives immediate response
==> IE6 gives no response, until some 5 minutes later: cannot find server + on 
the serverlog: "org.makumba.MakumbaError: attempt to read the multipart stream 
twice during one request"


Netscape 7:
[1000](21/Apr/2003:23:10:02) 
"GET /fred-k/archive/doc/20-P-BC-BRD-102 HTTP/1.1" 200 -
[1000](21/Apr/2003:23:10:35) 
"GET /fred-k/archive/officialDocumentEdit.jsp?document=aqkvrgk HTTP/1.1" 200 -
[1000](21/Apr/2003:23:10:57) 
"POST /fred-k/archive/doc/cwliq06 HTTP/1.1" 200 -

IE6:
[1000](21/Apr/2003:23:15:16) 
"GET /fred-k/archive/doc/20-P-BC-BRD-102 HTTP/1.1" 200 -
[1000](21/Apr/2003:23:16:18) 
"GET /fred-k/archive/officialDocumentEdit.jsp?document=aqkvrgk HTTP/1.1" 200 -
[1000](21/Apr/2003:23:21:58) 
"POST /fred-k/archive/doc/cwliq06 HTTP/1.1" 500 -

I don't want to go too deep in this, but a quick search on google reveiled 
e.g. http://www.faqchest.com/msdn/IE-HTML/script-03/script-
0302/script03021717_26999.html


It doesn't seem to be the exact same thing, but all the above suggests an IE 
bug, possibly only in an https connection.

**Comment by ghost** [comment]
**Comment by @stefanb on 22 Jul 2003 13:03 UTC**
http://www.google.com/search?q=%22Cannot+Find+Server%22+secure+https+IE
IE has number of problems dealing with https connections
http://www.generation.net/~hleboeuf/canotofd.htm
(look for "https" or "secure")

This is not a Makumba, but IE bug. 
Marking it invalid.
