### ISSUE TITLE
Date as urlParam is only parsed in case of Form (responder action)

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#186]
**Reported by @frederikhabils on 20 Apr 2003 17:16 UTC**
I guess this has been in Makumba for ever. 

It seems impossible to pass a date value thru URL, if makumba is not expecting 
this date, as part of a form. 

e.g. the search page for helpdesk, is trying to filter by date. This works 
fine if the date is set by the mak:form, submit action. 

but (bug 328) the sorting of that table, as on all similar pages, works by 
clicking the link on top of the column to sort. For that to work, this link 
includes all the url parameters that the form would produce... And then it 
doesn't work. 
(error at the bottom)

Basically, if you submit the form, and then remove the 
__makumba__responder__=... from the url and try to get that... you get this 
error.

So conclusion: a date is only properly parsed if it is part of a responder 
action.

What I did for bug 328, is to add the last known __makumba__responder__=... to 
the URL that is set on the sortby links on the column headers. That way, the 
sorting works again.
Problems:
- you can't cut/paste that URL and send it to someone else
- how long does a responder value stay valid? don't know?

seems to me that the calendar/month.jsp page is also working around this, on 
the links to next/prev month.

----
Below is the error that you get when passing the date without the 
makumba__responder action.

Actually, because of additional code, if the passed in dates are not good, the 
page will revert to default dates (today-1 month)-(today), instead of this 
error. 
cfr:    pageContext.setAttribute("Date1", date1);

java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:389)
	at org.makumba.view.MultipleAttributeParametrizer.rewriteAttributes
(MultipleAttributeParametrizer.java:165)
	at org.makumba.view.MultipleAttributeParametrizer$1.makeResource
(MultipleAttributeParametrizer.java:102)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:124)
	at 
org.makumba.view.MultipleAttributeParametrizer.getAttributeParametrizer
(MultipleAttributeParametrizer.java:67)
	at org.makumba.view.MultipleAttributeParametrizer.<init>
(MultipleAttributeParametrizer.java:59)
	at org.makumba.view.ComposedQuery.prepare(ComposedQuery.java:342)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:327)
	at org.makumba.view.jsptaglib.QueryStrategy.doQuery
(QueryStrategy.java:480)
	at org.makumba.view.jsptaglib.RootQueryStrategy.doQueries
(RootQueryStrategy.java:155)
	at org.makumba.view.jsptaglib.QueryStrategy.doRootAfter
(QueryStrategy.java:190)
	at org.makumba.view.jsptaglib.RootQueryStrategy.doAfter
(RootQueryStrategy.java:106)
	at org.makumba.view.jsptaglib.MakumbaBodyTag.doAfterBody
(MakumbaBodyTag.java:57)
	at org.apache.jsp.search$jsp._jspService(search$jsp.java:1016)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

Migrated-From: http://trac.makumba.org/ticket/399

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 20 Apr 2003 20:44 UTC**
makumba never supported anything but strings and pointers (not even ints!) for
passing by URL. 

when not in a form, there's no way for makumba to know that the parameters
X_year, X_month etc are actually to be interpreted together as a single parameter

in bug 40 i suggested a way to declare this, which would be good for both type
checking and for this kind of cases. basically a <mak:attribute dataTpe= var= >
can do.

i'd like to get an idea of the urgency of this problem, i would really like to
avoid more workarounds in the applications.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 17 May 2003 15:35 UTC**
mmm, I worked on bug 328 some more. I had a vision that it should be possible 
to pass a date thru URL's query string (pref'bly as one param, not 3+), and be 
able to use it easily. The {parse|format}QueryStringDate() functions in 
DateUtils should go a long way in that direction

http://cvs.makumba.org/cgi-bin/cvsweb.cgi/karamba/public_html/WEB-
INF/classes/org/eu/best/util/DateUtils.java

used in:
http://cvs.makumba.org/cgi-
bin/cvsweb.cgi/karamba/public_html/helpdesk/private/search.jsp

mmm, dunno if this is what Cristi means with "workaround in application?"

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 22 May 2003 13:55 UTC**
about comment 2: by "workaround in application" i mean that i prefer a new
makumba feature to 10 workarounds for it in the application

so, in this case, i like the solution proposed, to pass dates as one single
parameter instead of more. but that will have to be an alternative to the
existent 3+ passing, which is needed in classic date form inputs

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 10:01 UTC**
