### ISSUE TITLE
configuration file not found: MakumbaDatabase.properties

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#188]
**Reported by @cristianbogdan on 23 Apr 2003 06:34 UTC**
bug 351 comment 3 tells the story of makumba behaving erratically ("dying") due
to too many connections, then "coming back to life" after a while

the story is not complete, the system dies with an error message, which is a
wrong one, it says

>> org.makumba.ConfigFileError: Configuration file not found: 
>> MakumbaDatabase.properties
>>         at org.makumba.db.Database.findDatabaseName(Database.java:207)

for the programmer/administrator this is pretty confusing, the actual problem
seems to be that a Database object is not being given back to the system by
db.close(). once a db.close() is added, everything comes back to normal

this is hard to reproduce and hard to fix (i might work on it though), but it's
good to know

Migrated-From: http://trac.makumba.org/ticket/403

**Comment by ghost** [comment]
**Comment by @frederikhabils on 23 Apr 2003 08:03 UTC**
Cristi wrote in mail: 

--- QUOTE
this is very likely to occur when there are lots of accesses (summer 
application) so you better find that findDatabase() that has no db.close()...

check what did fred submit to CVS lately in the johnny JSPs and BLs. see 
if it's updated in production

> otherwise do a grep for findDatabase()

recursive grep in JSP and BL... for each findDatabase() add

db=findDatabase(...);
try{
the rest of the stuff up until db is not needed anymore
}finally( db.close(); }

--- UNQUOTE


1/ there is nothing in CVS from me that is not in production
2/ I did a search for a findDatabase during Easter weekend, and added db.close
() everywhere.

3/ Unfortunately, I didn't do it in the best way... i did:
      db = findDatabase()
      ...
      db.close()

So any exception in the (...) would lead to no db.close(). The try block 
suggested by Cristi is better coding.

Finally, when I noticed the 120x "MakumbaDatabase.properties" not found last 
night, the # of open connections was normal (10 or so). 

So why did this error occur? Why did makumba not just create more connections 
in the pool?

FYI: starting at 13:00 I will be REALLY offline, now at the office.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 28 Apr 2003 16:01 UTC**
the only experience i have is this
- i had a JSP that was accessed by the driver of some hardware boxes which were
sending sensor events via HTTP/TCP every 5 seconds or so
- the JSP was opening the db, examining it, determine if the events needed be
registered in the db, and finishing
- when the JSP had no db.close() the "config file not found" error was up after
some time (1-2 h? not sure) and the users were unable to access the site, though
some accesses which still succeded
- once i added db.close(), the problem was solved

so currently i tend to link "lack of db.close()" to the "config file not found"
error. however, questions remain
- first, why does makumba report the "file not found" error? my guess was "too
many files open" in unix (i was on solaris, not on linux) which was somehow
provoked by the db connection (i.e. sockets, not files really). but this is
still dubious. TODO: investigate how the exception is thrown, look at
stacktraces, etc
- Fred: " Why did makumba not just create more connections in the pool?". good
question, when i had the problem, i saw more than 10 connections, which is not
the case for Fred...
- finally, i tried to reproduce this by insistently reloading a simple JSP that
opens a connection and never closes it, but i didn't manage. it seems very
difficult to reproduce. maybe re-connecting a hardware box to the system i was
working on and removing the close() is a way to go on... still, waiting for 1-2h
for the error to appear (or not) while trying  to fix, is not a very promising
perspective :)

**Comment by ghost** [comment]
**Comment by @stefanb on 27 May 2003 13:18 UTC**
it is quite quiet period (64 active sessions, 10 DB connections, 83MB free 
heap) but i still got the error again and all next accesses was working just 
fine (tried several fast reloads).

root cause mentions http://private.best.eu.org/classes/org.eu.best.KarambaLogic
which also seems fine to me.

stacktrace:
------
javax.servlet.ServletException: Configuration file not found: 
MakumbaDatabase.properties
	at org.apache.jasper.runtime.PageContextImpl.handlePageException
(PageContextImpl.java:463)
	at org.apache.jsp.header$jsp._jspService(header$jsp.java:238)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at org.apache.jasper.servlet.JspServlet$JspServletWrapper.service
(JspServlet.java:202)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile
(JspServlet.java:382)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:474)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at org.apache.catalina.core.ApplicationDispatcher.invoke
(ApplicationDispatcher.java:684)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude
(ApplicationDispatcher.java:575)
	at org.apache.catalina.core.ApplicationDispatcher.include
(ApplicationDispatcher.java:498)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include
(JspRuntimeLibrary.java:819)
	at org.apache.jsp.welcome$jsp._jspService(welcome$jsp.java:74)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at org.apache.jasper.servlet.JspServlet$JspServletWrapper.service
(JspServlet.java:202)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile
(JspServlet.java:382)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:474)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.StandardWrapperValve.invoke
(StandardWrapperValve.java:260)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.catalina.core.StandardContextValve.invoke
(StandardContextValve.java:191)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.catalina.core.StandardContext.invoke
(StandardContext.java:2415)
	at org.apache.catalina.core.StandardHostValve.invoke
(StandardHostValve.java:180)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at org.apache.catalina.valves.ErrorDispatcherValve.invoke
(ErrorDispatcherValve.java:170)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at org.apache.catalina.valves.ErrorReportValve.invoke
(ErrorReportValve.java:172)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at org.apache.catalina.valves.AccessLogValve.invoke
(AccessLogValve.java:509)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.catalina.core.StandardEngineValve.invoke
(StandardEngineValve.java:174)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.coyote.tomcat4.CoyoteAdapter.service
(CoyoteAdapter.java:223)
	at org.apache.coyote.http11.Http11Processor.process
(Http11Processor.java:432)
	at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnectio
n(Http11Protocol.java:386)
	at org.apache.tomcat.util.net.TcpWorkerThread.runIt
(PoolTcpEndpoint.java:534)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run
(ThreadPool.java:530)
	at java.lang.Thread.run(Thread.java:536)


root cause 

org.makumba.ConfigFileError: Configuration file not found: 
MakumbaDatabase.properties
	at org.makumba.db.Database.findDatabaseName(Database.java:207)
	at org.makumba.MakumbaSystem.getDefaultDatabaseName
(MakumbaSystem.java:47)
	at org.apache.jsp.header$jsp._jspService(header$jsp.java:153)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at org.apache.jasper.servlet.JspServlet$JspServletWrapper.service
(JspServlet.java:202)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile
(JspServlet.java:382)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:474)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at org.apache.catalina.core.ApplicationDispatcher.invoke
(ApplicationDispatcher.java:684)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude
(ApplicationDispatcher.java:575)
	at org.apache.catalina.core.ApplicationDispatcher.include
(ApplicationDispatcher.java:498)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include
(JspRuntimeLibrary.java:819)
	at org.apache.jsp.welcome$jsp._jspService(welcome$jsp.java:74)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at org.apache.jasper.servlet.JspServlet$JspServletWrapper.service
(JspServlet.java:202)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile
(JspServlet.java:382)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:474)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.StandardWrapperValve.invoke
(StandardWrapperValve.java:260)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.catalina.core.StandardContextValve.invoke
(StandardContextValve.java:191)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.catalina.core.StandardContext.invoke
(StandardContext.java:2415)
	at org.apache.catalina.core.StandardHostValve.invoke
(StandardHostValve.java:180)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at org.apache.catalina.valves.ErrorDispatcherValve.invoke
(ErrorDispatcherValve.java:170)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at org.apache.catalina.valves.ErrorReportValve.invoke
(ErrorReportValve.java:172)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at org.apache.catalina.valves.AccessLogValve.invoke
(AccessLogValve.java:509)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.catalina.core.StandardEngineValve.invoke
(StandardEngineValve.java:174)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke
(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.coyote.tomcat4.CoyoteAdapter.service
(CoyoteAdapter.java:223)
	at org.apache.coyote.http11.Http11Processor.process
(Http11Processor.java:432)
	at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnectio
n(Http11Protocol.java:386)
	at org.apache.tomcat.util.net.TcpWorkerThread.runIt
(PoolTcpEndpoint.java:534)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run
(ThreadPool.java:530)
	at java.lang.Thread.run(Thread.java:536)

--------------------------------------------------------------------------------
Apache Tomcat/4.1.18

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 8 Jun 2003 00:13 UTC**
Frederik Habils wrote:
> For instance, it seems that every findDatabase() etc. does a file-read 
> on the MakumbaDatabase.properties. ->
> 
> - isn't it enough to read MakumbaDatabase.properties just once (after 
> start and reload)

shit. i remember i counted on the class loader to open the file only once
(because class loaders normally load classes only once). but then i forgot about
that and, in org.makumba.util.ClassResources i got a URL, and open the stream
myself (org.makumba.db.Database:206, revision 2.0)... which i never close. it's
surely closed by the garbage collector, but if finalization is late, resources
are consumed. also, i think i counted on Properties.load() to close the stream,
but i just looked in the JDK source and it doesn't close it...

i fixed this in org.makumba.db.Database, revision 2.1. MakDb.prop is read only
once, and the stream is closed afterwards

now we need to tag some versions. for 0.5.7.7 that's easy. for 0.5.5.28, we'd
have to publish the jar manually because publishJar and tagJar only tag the head
of a branch 

to use publishJar, we'd have to make a branch at 0.5.5.27 with db.Database
revision 2.1, i think that's better, because it can accomodate future bugfixes

# copy tag .27 to .28
cvs rtag -r makumba-0_5_5_27 makumba makumba-0_5_5_28

# move .28 tag of db.Database.java to the head
cvs co makumba
cd makumba
cvs tag -F makumba-0_5_5_28 classes/org/makumba/db/Database.java
cd ..
rm -rf makumba

#branch
cvs rtag -r makumba-0_5_5_28 -b 0_5_5-bugfix makumba

#publishJar the head of the branch
cvs co -r 0_5_5-bugfix makumba
cd makumba
ant -dtag=makumba-0_5_5_28 publishJar

for 0.5.8.6, the only way is to copy the class on that branch... 

so, which should we do? i guess 0.5.5.28 and 0.5.8.6 will be enough?

**Comment by ghost** [comment]
**Comment by @frederikhabils on 8 Jun 2003 07:08 UTC**
yes, it seems to me enough to have a correction on 0.5.5 and 0.5.8 version 
lines.
Interesting to see some of the related cvs commands. They remain a very gray 
area to me.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 8 Jun 2003 09:58 UTC**
now you can get 0.5.5.28 with getMakumba
you can get 0.5.8.6 according to bug 376 comment 6

actually cvs commands were:
# copy tag .27 to .28
cvs rtag -r makumba-0_5_5_27 makumba-0_5_5_28 makumba

# move tag .28 to the head (revision 2.1) only for the changed file
cvs rtag -F -r 2.1 makumba-0_5_5_28 makumba/classes/org/makumba/db/Database.java

# make a branch
cvs rtag -r makumba-0_5_5_28 -b makumba-0_5_5-bugfix makumba

#publish the head of the branch
cvs co -r makumba-0_5_5-bugfix makumba
cd makumba
ant -Dtag=makumba-0_5_5_28 publishJar

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 26 Jun 2003 12:28 UTC**
this should be fixed
