### ISSUE TITLE
FLE in AddTag

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#189]
**Reported by @stefanb on 29 Apr 2003 13:56 UTC**
Editing any team 
(eg: https://parade.best.eu.org/mak-test-k/groups/admin/groupEdit.jsp?team=6l5v8wj )
for the first time after webapp was installed throws:
---
Internal Makumba error
Please report to the developers.
java.lang.NullPointerException
	at org.makumba.view.jsptaglib.AddTag.computeTypeFromEnclosingQuery(AddTag.java:45)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:110)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:141)
	at org.apache.jsp.groupEdit$jsp._jspService(groupEdit$jsp.java:585)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	
Makumba developer support, version: 0.5.7.4
---
This behaviour is not experienced with 0.5.5.27
https://parade.best.eu.org/demo-k/groups/admin/groupEdit.jsp?team=6l5v8wj

Migrated-From: http://trac.makumba.org/ticket/416

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 1 May 2003 13:38 UTC**
fixed in 0.5.7.5
