### ISSUE TITLE
non-integer agregating result leads to error

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#193]
**Reported by @stefanb on 13 May 2003 09:46 UTC**
Results of agregating functions can have non-integer results, but makumba throws
error in such cases.
I experienced this while averaging image size with avg(i.length) as seen in test
case:
https://parade.best.eu.org/stefan-k/test/avgBug.jspx 
(this testcase is also in CVS)

the error reported is:
---------
Internal Makumba error 
Please report to the developers.

java.sql.SQLException: Bad format for number '6156.3500' in column 3(.col3).
	at org.gjt.mm.mysql.ResultSet.getLong(ResultSet.java:408)
	at org.gjt.mm.mysql.ResultSet.getInt(ResultSet.java:366)
	at org.makumba.db.sql.intManager.getValue(intManager.java:44)
	at org.makumba.db.sql.RecordManager.fillResult(RecordManager.java:655)
	at org.makumba.db.sql.Query.goThru(Query.java:107)
	at org.makumba.db.sql.Query.execute(Query.java:93)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:180)
	at org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:44)
	at org.makumba.view.AttributeParametrizer.execute(AttributeParametrizer.java:174)
	at
org.makumba.view.MultipleAttributeParametrizer.execute(MultipleAttributeParametrizer.java:47)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:328)
	at org.makumba.view.jsptaglib.QueryStrategy.doQuery(QueryStrategy.java:432)
	at
org.makumba.view.jsptaglib.RootQueryStrategy.doQueries(RootQueryStrategy.java:154)
	at org.makumba.view.jsptaglib.QueryStrategy.doRootAfter(QueryStrategy.java:184)
	at org.makumba.view.jsptaglib.RootQueryStrategy.doAfter(RootQueryStrategy.java:105)
	at org.makumba.view.jsptaglib.MakumbaBodyTag.doAfterBody(MakumbaBodyTag.java:57)
	at org.apache.jsp.imageList$jsp._jspService(imageList$jsp.java:693)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	
--------------------------------------------------------------------------------
Makumba developer support, version: 0.5.5.27 

----
the question remains what type of variable should be returned in case of using
it like:
<mak:value expr="avg(x.someIntField)" var="bla" />

So far we only used sum() and count(), which always return integer. 

WORKAROUND: the numbers can be averaged manually with 
sum(x.someIntField)/count(x)
but this is a dirty workaround for basic functionality.

Migrated-From: http://trac.makumba.org/ticket/429

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 13 May 2003 14:34 UTC**
this is similar to bug 359 (fixed only on the 0.5.7 branch as it's a major
change in the OQL parser) so the basic support for fixing this is in place

besides, there is the problem that makumba doesn't have a float type (bug 430)
once that type is there, we just have to tell
org.makumba.db.sql.oql.AggregateAST that avg applied to an int expression
returns makumba float.

**Comment by ghost** [comment]
**Comment by @stefanb on 21 May 2003 09:48 UTC**
interesting, for some reason
http://private.best.eu.org/test/avgBug.jsp
  reports a rounded to int number: "Average image length: 6457"
  even if 1168830 bytes / 181 images would give an average of 6457,624.. bytes
  (as reported by http://private.best.eu.org/admin/imageList.jsp?order=title)

https://parade.best.eu.org/stefan-k/test/avgBug.jsp
  reports an error:
  java.sql.SQLException: Bad format for number '6156.3500' in column 1(.col1).

both webapps are using makumba 0.5.5.27 and they are both using DB on tequila, 
so SQL engine is the same so there is a catch somewhere...

http://private.best.eu.org/systemInfo.jsp reports:
  JDBC driver and version   MySQL-AB JDBC Driver 3.0.6-stable ( $Date: 
  2003/02/17 17:01:34 $, $Revision: 1.27.2.13 $ )  
while https://parade.best.eu.org/stefan-k/systemInfo.jsp reports:
  JDBC driver and version   Mark Matthews' MySQL Driver 2.0.4 

Did JDBC spec or just implementation change from version 2 to 3 regarding this?

**Comment by ghost** [comment]
**Comment by @stefanb on 21 May 2003 09:58 UTC**
correction of my comment 2:
6457 is _not_rounded_ 6457,624.. it is just truncated (decimals are cut off) 
or floored (rounded down to nearest int) which is different from truncate for 
negative numbers)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 21 May 2003 10:13 UTC**
makumba uses ResultSet.getInt and i think the correct interpretation is to
actually convert to integer, since the API user (programmer) asked for it. if it
would have been getNumber and then ClassCastException inside makumba, it would
have been a bug

there isn't much about this in the javadoc
http://java.sun.com/j2se/1.4.1/docs/api/java/sql/ResultSet.html#getInt(java.lang.String)

i think the later JDBC implementation is correct, in which case this is not a
bug (but please test with 0.5.7.x before resolving it).

**Comment by ghost** [comment]
**Comment by @stefanb on 21 May 2003 14:28 UTC**
https://parade.best.eu.org/fred-k/test/avgBug.jsp
uses makumba 0.5.7.6 with Mark Matthews' MySQL Driver 2.0.4 
result:

java.sql.SQLException: Bad format for number '6156.3500' in column 1(.col1).
	at org.gjt.mm.mysql.ResultSet.getLong(ResultSet.java:408)
	at org.gjt.mm.mysql.ResultSet.getInt(ResultSet.java:366)
	at org.makumba.db.sql.intManager.getValue(intManager.java:44)
...
now only needs to be tested with JDBC 3 driver on 0.5.7.6 to see how it behaves 
there.

How do we deal with it if it is JDBC driver bug?
Will makumba depreciate "Mark Matthews' MySQL Driver 2.0.4" and start yelling 
during startup if such buggy driver is used? or should we make a generic 
workaround for such cases, manually (inside makumba guts) making sure that 
result will be int?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 22 May 2003 14:08 UTC**
> How do we deal with it if it is JDBC driver bug?

i think makumba should simply ignore the 2.0.x drivers. we simply write in the
doc (SQLEngines.html) that we support 3.x

so if this works with 0.5.7 and jdbc 3.x, i propose to close this bug

**Comment by ghost** [comment]
**Comment by @stefanb on 5 Feb 2004 09:42 UTC**
While working on real type (bug 430)
http://cvs.makumba.org/classes/org/makumba/db/sql/oql/AggregateAST.java
got me puzzled a bit

If I understand the code correctly it supports some bizzare aggregation
combinations:
- max(textField)
- min(ptrField)
- max(char)
...it probably leaves it up to the jdbc driver / sql engine to deal with this.

But more importantly it defines that avg(intField) returns an int result.
If we change that to "real" will this bug be solved?

**Comment by ghost** [comment]
**Comment by @stefanb on 5 Feb 2004 09:45 UTC**
bummer, only now i managed to read cristi's comment 1 :)

**Comment by ghost** [comment]
**Comment by @stefanb on 7 Feb 2004 21:51 UTC**
This was fixed when real data type was introduced (bug 430)
avg(...) now correctly returns real (double) instead of integer
