### ISSUE TITLE
dataType not determined on editForm mak:input with value="$bla"

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#210]
**Reported by @frederikhabils on 28 May 2003 23:03 UTC**
this is very similar symptoms as bug 346, but seems to be present in 0.5.5 as 
well as 0.5.7. 

I want to do (simplified to its essence):

<mak:object from="best.internal.Student ins, ins.student.person p" where="p=
($person)" >

  <% pageContext.setAttribute("value", someString ); %>

  <mak:editForm object="ins" action="blabla.jsp" method="post"> 
    Email:<td><mak:input field="student.person.email"  value="$value" /> 
  </mak:editForm>
</mak:object>

but the result is: 

org.makumba.InvalidValueException: cannot determine input type: INPUT 
name=student.person.email value=$value dataType=null value known: something . 
Please specify the type using dataType=...

	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:123)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:148)
	at org.apache.jsp.bugNew$jsp._jspService(bugNew$jsp.java:128)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

I wanted to use this in an application-specific try-out of a form that 
responds to itself, and redisplays the inputted values if the validation code 
resulted in LogicException

Migrated-From: http://trac.makumba.org/ticket/451

**Comment by ghost** [comment]
**Comment by @frederikhabils on 28 May 2003 23:11 UTC**
example of the bug is at (0.5.5 and 0.5.7)
https://parade.best.eu.org/demo-k/test/bug451.jsp?person=hhi4y8a
https://parade.best.eu.org/fred-k/test/bug451.jsp?person=hhi4y8a

also noteworthy is that with the following input control, it does work fine:

  Email:<td><mak:input field="student.person.email"  value="'bla@dummy.be'" /> 

as though the type of string constant could be determined, and the type of 
$value not...

also this works fine:

  Email:<td><mak:input field="student.person.email"  value="$value" 
dataType="char[255]" /> 

(but I don't like to be forced to specify the type)


Isn't it the point that the dataType of field="student.person.email" for 
editForm on object="ins" is already determined, so the only thing that makumba 
should attempt, is to cast $value into the appropriate dataType ?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 29 May 2003 07:11 UTC**
> (but I don't like to be forced to specify the type)

i know, but please use it as a workaround before we get this fixed

> Isn't it the point that the dataType of field="student.person.email" for 
> editForm on object="ins" is already determined, so the only thing that makumba 
> should attempt, is to cast $value into the appropriate dataType ?

no, i never intended casting. i just meant dataType to specify a type when the
type cannot be determined from previous makumba queries, types of $attributes, etc

the source for this is in org.makumba.view.jsptaglib.InputTag. give it a look,
maybe you can spare me some effort :)

**Comment by ghost** [comment]
**Comment by @frederikhabils on 29 May 2003 08:53 UTC**
I don't understand the last comment 2

> no, i never intended casting. i just meant dataType to specify a type when
> the type cannot be determined from previous makumba queries, types of 
> $attributes, etc

I don't get it:

in the following code, makumba can figure out the dataType from the MDD

 <mak:editForm object="ins" action="blabla.jsp" > 
    Email:<td><mak:input field="student.person.email" /> 
 </mak:editForm>

and in the following code, it can't?

 <mak:editForm object="ins" action="blabla.jsp" > 
    Email:<td><mak:input field="student.person.email"  value="$value" /> 
 </mak:editForm>

the workaround is ok for types that are stable as "char[100]" but not so ok 
for types that are more prone to changes, like int{ "optionTxt=optionNr, ... }

I'll see if the inputTag code makes me any wiser

**Comment by ghost** [comment]
**Comment by @frederikhabils on 29 May 2003 09:51 UTC**
just found out that the workaround (adding dataType=...) does NOT help if the 
type is intEnum.

without the dataType, the error is as comment 0

with dataType specified, the error is this:

java.lang.NullPointerException
	at org.makumba.abstr.FieldInfo.checkValue(FieldInfo.java:138)
	at org.makumba.view.jsptaglib.InputTag.doStart(InputTag.java:130)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:141)
	at org.apache.jsp.bug451intEnum$jsp._jspService
(bug451intEnum$jsp.java:125)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)


btw, also the bug 13 is still in 0.5.7 (it shows if you change
  <mak:input field="student.person.gender"  value="$value" dataType="int
{\"Male\"=0,\"Female\"=1}" /> 

to 

  Email:<td><mak:input field="student.person.gender"  value="1" dataType="int
{\"Male\"=0,\"Female\"=1}" /> 

example file at:
https://parade.best.eu.org/fred-k/test/bug451intEnum.jsp

**Comment by ghost** [comment]
**Comment by @frederikhabils on 29 May 2003 09:53 UTC**
CORRECTION to comment 4: also the __bug 17__ is still in 0.5.7 ... (instead of 
bug 13)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 9 Jun 2003 11:58 UTC**
clearly org.makumba.view.jsptaglib.InputTag needs a bit of review. the root
problem is that the class does a bit of type guessing, because it was not
possible to know the type just from the attributes of the mak:input

with page analysis, determining the type should be easier. also, if the type
clearly comes from an OQL expression (like in this case and in bug 17), there
should be no problem with knowing the type.

in 0.5.8 i changed some things in InputTag, so maybe this is already fixed there?

in any case, i'll mark both this and bug 17 as dependent on page analysis (bug
447), though they are fixable before page analysis will be "static". i think
0.5.9 is a good milestone for this. if that will not fly, they should be fixable
in 0.5.8

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 21 Jun 2003 14:26 UTC**
i hope the mak:input type detection is better in 0.5.9. it is certainly more 
readable, so hopefully we'll be able to get it working together

i think we should introduce defaultValue= after the pre-regression tests work. 
then we can close this bug and bug 17

**Comment by ghost** [comment]
**Comment by @frederikhabils on 26 Jun 2003 21:59 UTC**
as already reported in bug 17 comment 7, this is solved in 0.5.9.3 (while bug 17
is not).

I suggest to close this bug, and keep an eye on it as bug 17 evolves. 

The difference between this bug and bug 17, was originally

 17               |    451
 ----------------------------------
 dataType char    |    intEnum
 value="1"        |    value="$val" 

But the issues are so related, that we can keep just one bug open.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 26 Jun 2003 22:01 UTC**
sorry, forgot to mark as RESOLVED at previous submittal.
