### ISSUE TITLE
error in MakumbaJspAnalyzer : "tag closed incorrectly" when there is <mak:list ... />

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#212]
**Reported by @frederikhabils on 1 Jun 2003 09:50 UTC**
I'm getting an error when trying to view
https://parade.best.eu.org/mak-test-k/groups/myGroups.jsp

this is the error on first load :

java.lang.RuntimeException: tag closed incorrectly: object should have got 
class org.makumba.view.jsptaglib.ObjectTag and it was class 
org.makumba.view.jsptaglib.QueryTag
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.end
(MakumbaJspAnalyzer.java:95)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.endTag
(MakumbaJspAnalyzer.java:138)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:275)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:254)
	at org.makumba.util.JspParseData.parse(JspParseData.java:189)
	at org.makumba.util.JspParseData.getAnalysisResult
(JspParseData.java:44)
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:144)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:162)
	at org.apache.jsp.myGroups$jsp._jspService(myGroups$jsp.java:95)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

where doStartTag at org.apache.jsp.myGroups$jsp._jspService
(myGroups$jsp.java:95)
refects https://parade.best.eu.org/mak-test-k/groups/myGroups.jspx#14

on later load, the error changes to:

java.lang.ClassCastException
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:144)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:162)
	at org.apache.jsp.myGroups$jsp._jspService(myGroups$jsp.java:95)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

That page is working fine in 0.5.7 and 0.5.5. 

The only "interesting" thing I can see, is that it contains a nested 
<mak:list ... /> (that is, a single tag construction, instead of open + close)

Migrated-From: http://trac.makumba.org/ticket/455

**Comment by ghost** [comment]
**Comment by @frederikhabils on 1 Jun 2003 10:47 UTC**
same error on 

https://parade.best.eu.org/mak-test-
k/johnny/lbg/applying/organiser/applicant.jsp?student=gzlut3s&activity=6hlgoov

which also has a single-tag <mak:list ... /> on line 214

https://parade.best.eu.org/mak-test-
k/johnny/lbg/applying/organiser/applicant.jspx#214

**Comment by ghost** [comment]
**Comment by @frederikhabils on 1 Jun 2003 11:04 UTC**
idem 
https://parade.best.eu.org/mak-test-
k/johnny/lbg/participating/organiser/participantsTo_old.jsp?activity=adfs1hl

**Comment by ghost** [comment]
**Comment by @frederikhabils on 1 Jun 2003 11:08 UTC**
I guess this will be the same thing...
https://parade.best.eu.org/mak-test-
k/johnny/lbg/evaluating/organiser/evaluationsTo.jsp?activity=6hlgoov

the error message is different (on first load + later:)

java.lang.RuntimeException: could not find cache for 
org.makumba.view.jsptaglib.QueryTag {}
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:164)
	at org.apache.jsp.evaluationsTo$jsp._jspService
(evaluationsTo$jsp.java:292)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)


the difference in the source code, is that the single <mak:list /> is not 
nested tag, but is a root tag.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 1 Jun 2003 15:54 UTC**
fixed in MakumbaJspAnalyzer, it was not taking into account <mak:list ../> tags

**Comment by ghost** [comment]
**Comment by cristian_bogdan on 15 Nov 2010 16:47 UTC**
(In [165]) fixed bug 455
