### ISSUE TITLE
mak:input on "set"-type in editForm gives OQL error

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#213]
**Reported by @frederikhabils on 1 Jun 2003 11:22 UTC**
https://parade.best.eu.org/mak-test-k/groups/admin/groupEdit.jsp?team=6l5v8wj

has this very deep error in 0.5.8, and works ok in 0.5.7 / 0.5.5:
(unfortunately, it's a very complicated page, so I have no clue as to what's 
wrong, for the moment)

error is the same on every load...

java.lang.ClassCastException
	at org.makumba.db.sql.oql.QueryAST.getFieldName(QueryAST.java:509)
	at org.makumba.db.sql.oql.IdAST.writeInSQLQuery(IdAST.java:43)
	at org.makumba.db.sql.oql.QueryAST.writeProjection(QueryAST.java:472)
	at org.makumba.db.sql.oql.QueryAST.writeInSQLQuery(QueryAST.java:569)
	at org.makumba.db.sql.Query.<init>(Query.java:57)
	at org.makumba.db.sql.Query.<init>(Query.java:51)
	at org.makumba.db.sql.Database.prepareQueryImpl(Database.java:188)
	at org.makumba.db.DBConnection$1.makeResource(DBConnection.java:46)
	at org.makumba.util.NamedResourceFactory.makeResource
(NamedResourceFactory.java:61)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:124)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:180)
	at org.makumba.db.DBConnectionWrapper.executeQuery
(DBConnectionWrapper.java:44)
	at org.makumba.view.AttributeParametrizer.execute
(AttributeParametrizer.java:174)
	at org.makumba.view.MultipleAttributeParametrizer.execute
(MultipleAttributeParametrizer.java:47)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:328)
	at org.makumba.view.jsptaglib.QueryStrategy.doQuery
(QueryStrategy.java:367)
	at org.makumba.view.jsptaglib.RootQueryStrategy.onInit
(RootQueryStrategy.java:86)
	at org.makumba.view.jsptaglib.RootData.setStrategy(RootData.java:69)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:170)
	at org.apache.jsp.groupEdit$jsp._jspService(groupEdit$jsp.java:77)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

Migrated-From: http://trac.makumba.org/ticket/456

**Comment by ghost** [comment]
**Comment by @frederikhabils on 1 Jun 2003 11:24 UTC**
idem 
https://parade.best.eu.org/mak-test-k/events/coordinator/eventEdit.jsp?
event=b869mpy

**Comment by ghost** [comment]
**Comment by @frederikhabils on 1 Jun 2003 13:15 UTC**
this error seems to be caused by having a field in editForm that is of 
type "set"

the error occurs also on 
https://parade.best.eu.org/mak-test-
k/helpdesk/private/admin/solvers/solverEdit.jsp?s=asq98vn

and the error disappeared, if removing 
https://parade.best.eu.org/mak-test-
k/helpdesk/private/admin/solvers/solverEdit.jspx#17

which says: <p><b>Types:</b> <mak:input field="types"/>

types is defined as types = set best.helpdesk.RequestType
https://parade.best.eu.org/mak-test-k/dataDefinitions/best.helpdesk.Solver#7

btw, the stacktrace is similar to the one reported in bug 33

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 1 Jun 2003 15:57 UTC**
the problem is indeed with set <mak:input />s

it will be much easier to fix after i refactor the jsptaglib a bit (before, 
mak:input was using a mak:value internally to do its job, now i removed that, 
but forgot that "set" mak:value's are different beasts).  

if i won't have time for the refactoring, will fix this in the current structure

i guess it doesn't impede testing too much, does it?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 2 Jun 2003 03:05 UTC**
fixed in 0.5.8.2, mainly org.makumba.view.jsptaglib.InputTag revision 2.0.4.3

this brought quite a number of other changes in view.jsptaglib comparing to 
0.5.8.1: removing fields and replacing them with method calls, removing methods 
and replacing them with calls to other existing methods, moving some data 
around. especially the latter (see MakumbaTag->QueryTag) may introduce 
regressions, but i think it's pretty much under control

if no other major bugs occur, the next refactoring will be pretty spectacular, 
removing a large number of classes (reducing complexity as a result of page 
analysis)

**Comment by ghost** [comment]
**Comment by @stefanb on 2 Jun 2003 08:03 UTC**
All pages that Fred reported not working are now ok in mak-test-k, but i found 
another example of non-working page.

Both production (0.5.5.22) and 0.5.7.6 at
https://parade.best.eu.org/fred-k/admin/countryEdit.jsp?cntry=er78i3j
shows the list of countries nicely, but
0.5.8.2 at
https://parade.best.eu.org/mak-test-k/admin/countryEdit.jsp?cntry=er78i3j
is missing the list totally (there is no trace of it in the generated page)

the code seems ok and source is as:
<mak:object from="general.Country c" where="c=$cntry">
  <mak:editForm object="c" action="countryList.jsp?option=name" method="post">
      <mak:input field="noVisaCitizens" size="30"/>
  </mak:editForm>
</mak:object>

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 2 Jun 2003 14:30 UTC**
works with 0.5.8.3 (InputTag, SetValueStrategy, both revision 2.0.4.4). i sort
of re-simulated the simulated <mak:value .../> that existed in 0.5.5/7
<mak:input value= .../>

there was a wrong action at submit, had to update countryEdit from CVS.

the fix is pretty messy, looking forward for a better structure, that will
separate tag behavior from value/type pre-computing (analysis), value-computing
 and from value formatting. InputTag and SetValueStrategy sort of mix all of
these, plus they are mixed toghether due to the simulated mak:value 

of course, the new structure will be just re-arranging of present code (like the
present one is in respect to 0.5.7) so regression bugs should be of small magnitude.
