### ISSUE TITLE
problem in org.makumba.util.JspParseData.fill

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#214]
**Reported by @frederikhabils on 1 Jun 2003 11:33 UTC**
https://parade.best.eu.org/mak-test-k/archive/upload.jsp

first load:

java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor191.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.makumba.util.JspParseData.fill(JspParseData.java:353)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.simpleTag
(MakumbaJspAnalyzer.java:125)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:286)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:254)
	at org.makumba.util.JspParseData.parse(JspParseData.java:189)
	at org.makumba.util.JspParseData.getAnalysisResult
(JspParseData.java:44)
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:144)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:162)
	at org.apache.jsp.upload$jsp._jspService(upload$jsp.java:96)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

and later:

java.lang.ClassCastException
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:144)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:162)
	at org.apache.jsp.upload$jsp._jspService(upload$jsp.java:96)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

Migrated-From: http://trac.makumba.org/ticket/457

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 1 Jun 2003 15:58 UTC**
the problem was actually in MakumbaJspAnalyzer. fixed in 0.5.8.1
