### ISSUE TITLE
better makumba parser message if JSP tags are nested incorrectly

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#216]
**Reported by @frederikhabils on 1 Jun 2003 21:46 UTC**
this is resemblant to bug 455, but i guess different. 

page
https://parade.best.eu.org/mak-test-k/archive/documentAdd.jsp?document=h2fff8x

shows first : 
java.lang.RuntimeException: tag closed incorrectly: object should have got 
class org.makumba.view.jsptaglib.ObjectTag and it was class 
org.makumba.view.jsptaglib.NewTag
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.end
(MakumbaJspAnalyzer.java:105)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.endTag
(MakumbaJspAnalyzer.java:148)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:300)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:265)
	at org.makumba.util.JspParseData.parse(JspParseData.java:199)
	at org.makumba.util.JspParseData.getAnalysisResult
(JspParseData.java:44)
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:144)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:162)
	at org.apache.jsp.documentAdd$jsp._jspService(documentAdd$jsp.java:120)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

and later :
java.lang.ClassCastException
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:144)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:162)
	at org.apache.jsp.documentAdd$jsp._jspService(documentAdd$jsp.java:120)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

Anyway, I think the mak-coding in the page is to blame. Simplified, it does:

<mak:object ...>
 <mak:newForm ...>
</mak:object>
 </mak:newForm>

I would take it that such unsound code does not need to be supported (yet it 
seems every makumba version till now has supported it).

Migrated-From: http://trac.makumba.org/ticket/460

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 1 Jun 2003 23:23 UTC**
yes, i was not aware that JSP actually allows such stuff. indeed, makumba should
tell the programmer that something is wrong

**Comment by ghost** [comment]
**Comment by @frederikhabils on 2 Jun 2003 23:04 UTC**
slightly different, yet similar in nature:
https://parade.best.eu.org/mak-test-k/minerva/student/privacy_select.jspx

on line 40, there is a closing </mak:list> without corresponding opening tag.

- surprised it passed earlier makumba versions...
- the error (on first load) reported is reasonably on the ball:

java.lang.RuntimeException: tag closed incorrectly: list should have got class 
org.makumba.view.jsptaglib.QueryTag and it was class 
org.makumba.view.jsptaglib.ObjectTag
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.end
(MakumbaJspAnalyzer.java:105)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.endTag
(MakumbaJspAnalyzer.java:148)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:304)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:260)
	at org.makumba.util.JspParseData.parse(JspParseData.java:202)
	at org.makumba.util.JspParseData.getAnalysisResult
(JspParseData.java:47)
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:136)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:154)
	at org.apache.jsp.privacy_0005fselect$jsp._jspService
(privacy_0005fselect$jsp.java:66)

**Comment by ghost** [comment]
**Comment by @frederikhabils on 3 Jun 2003 18:54 UTC**
i'll just copy here the result of mailing list activity:

https://parade.best.eu.org/mak-test-k/challenge/forum/myTeamPosted.jsp
has a problem (and stacktrace) much like comment 2: there are closing tags for 
which there are no opening tags. 

in particular, between line 30-40, there are 
<mak:list /> ...
</mak:list> 

note that the "starting tags" are "single tags" = closed... so the (extra)
closing tags are not balanced

summarizing so far:
comment 0 and comment 1 = mismatch of tag sequence: <x> <y> </x> </y>
comment 2 and comment 3 = closing tag without opening tag: </z>

All these should be solved in the karamba page source code. 

The question for makumba is if it can offer a more accurate error 
message: "(open|closing) tag ... on line ... is not balanced". I wouldn't call 
it a prio for me personally, but it seems to be useful to ease learning 
frustrations.

As it happens, I can mention that the error in case a (root) tag is opened but 
not closed, is thrown by JSP/tomcat and sounds like:

org.apache.jasper.compiler.ParseException: End of content reached while more 
parsing required: tag nesting error?
	at org.apache.jasper.compiler.JspReader.popFile(JspReader.java:293)
	at org.apache.jasper.compiler.JspReader.hasMoreInput
(JspReader.java:337)
	at org.apache.jasper.compiler.Parser.parse(Parser.java:1109)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Jun 2003 10:47 UTC**
i suggest to make a separate karamba bug, or fix the karamba pages that have 
this problem right away

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Jun 2003 23:27 UTC**
fixed in 0.5.8.5. now an org.makumba.ProgrammerError is thrown. all data for 
the nice error message (and others) was there, but a bit of refactoring was 
needed to get it out... :

i separated the collection of syntax points set for a certain source file in 
classs org.makumba.util.SourceSyntaxPoints. the class will need more utility 
methods ("get an iterator through all the syntax points", "get source text 
between syntax points A and B", etc), we'll write them as need arises

org.makumba.util.SyntaxPoint now knows its line and column (not only character 
position) within the original source file

org.makumba.util.JspParseData$TagData now knows its start and end syntax 
points, its JspParseData (which can give away its SyntaxPoint collection), etc

org.makumba.view.jsptaglib.MakumbaTag now knows which TagData it came from, so 
all errors produced by a tag will ultimately be nicely printable

finally org.makumba.view.jsptaglib.MakumbaJspAnalyzer makes the nice error 
message, with the help of a specialized function from JspParseData (which will 
probably be moved around), showing the line with a ^ marker below.

**Comment by ghost** [comment]
**Comment by @stefanb on 5 Jun 2003 05:24 UTC**
https://parade.best.eu.org/mak-test-k/minerva/student/privacy_select.jsp
from comment 2 throws a decieving error message:
---
Body tag nesting error:
tag "mak:object" at line 2:
<mak:object from="best.minerva.Student ms, ms.student s" where="s=$student" 
header="header.jsp?title=privacy"> 
^

got incorrect closing "mak:list" at line 40:
      </mak:list>
      ^
---
suggesting to change "</mak:list>" in line 40 to "</mak:object>"
While it should just say sth like:
---
closing "mak:list" at line 40 without opening it:
      </mak:list>
      ^
---
when the tags are of different type (eg here it was opening <mak:object...>, 
but closing was </mak:list>)

same goes for case in comment 3
https://parade.best.eu.org/mak-test-k/challenge/forum/myTeamPosted.jsp

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 5 Jun 2003 05:37 UTC**
please help in making it less deceiving. 
org.makumba.view.jsptaglib.MakumbaJspAnalyzer

you are welcome to change the formulation (what it suggests, etc)

if you think the information about the opening tag should be taken out 
altogether, so be it. maybe the information about the un-opened tag is more 
important, so it should come first, and then something like "the tag that 
should be closed here is...". or whatever. 

i'll be happy to help, please ask questions. but i won't do more on this alone.

**Comment by ghost** [comment]
**Comment by @stefanb on 5 Jun 2003 07:37 UTC**
while trying to improve the messages thrown i wanted a simple test case and 
variations:

https://parade.best.eu.org/mak-test-k/test/bug460-overlapingObjectNew.jspx

but for some reason already JSP compiler reports:
org.apache.jasper.compiler.ParseException: /test/bug460-overlapingObjectNew.jsp
(4,0) Unterminated user-defined tag: ending tag </mak:object> not found or 
incorrectly nested

which makes me wonder why this was not reported in our real-life test cases.
bad synopsis maybe? does jasper fail to detect problems in some more 
complicated cases, but it detects them in this simple test case?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 5 Jun 2003 08:00 UTC**
about comment 8: i think jasper is buggy with this

but we never tested this bug with jasper2 (see bug 184). it may be that jasper2
detects all such cases, in which case trying to report them better from the
makumba analyzer is useless, the makumba analyzer never runs if jasper rejects
the  page

as per bug 184, jasper2 is ready to run, albeit without jikes (using normal
javac for java->class compilation). so i think a test with jasper2 should be
made for all test cases pointed at this bug

about comment 6: check jasper's error. it refers to the first tag (the unclosed
one), not to the second (the unopened)...

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 5 Jun 2003 10:20 UTC**
ok, i checked with jasper2, and it still doesn't see the nesting errors at 
archive/documentAdd.jsp?document=h2fff8x

so i guess it pays to put a bit more work into this, but not much. bug 465 is 
much more important for going into regression testing and production with 0.5.8

**Comment by ghost** [comment]
**Comment by @frederikhabils on 5 Jun 2003 19:50 UTC**
in reply to comment 8 (and 9, 10...)

true, the synopsis of comment 0 was a bit wrong:

the actual tag outline of the documentAdd page is:

<mak:object>
  <mak:newForm>
</mak:object>
  </mak:newForm>
</mak:object>
 
And, I've tested with simple change to ...
https://parade.best.eu.org/mak-test-k/test/bug460-overlapingObjectNew.jspx

... that indeed, tomcat jsp parser does not complain about this sequence of 
tags.


it's an interesting coincidence that we found a number of patterns that the 
jsp parser let through... 

on the whole, we might conclude to limit the extra efforts in trying to make 
makumba's message super clear, cfr also comment 10

**Comment by ghost** [comment]
**Comment by @frederikhabils on 22 Jun 2003 13:50 UTC**
the error message that cristi reported in comment 5, did not cover the case of 
a closing tag at root level... 

this is what you got as error

java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:508)
	at java.util.ArrayList.get(ArrayList.java:320)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.end
(MakumbaJspAnalyzer.java:127)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.endTag
(MakumbaJspAnalyzer.java:192)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:345)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:292)
	at org.makumba.util.JspParseData.parse(JspParseData.java:205)


I solved this in MakumbaJspAnalyzer.java 1.1.4.4 (which is on the 
refactorTaglib branch). Did not make a new 0.5.9.1 version just for this small 
change, though. Also not copied to 0.5.8 branch. Not worth the effort?

Now it says:

Error: Closing tag never opened:
tag "mak:object" at line 20:
</mak:object>
^

cfr. https://parade.best.eu.org/fred-k/test/bug491.jsp

note: this bug was REOPENED as per comment 6. Personally, I can work with that 
imperfection, and I would close this bug.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 23 Jun 2003 10:48 UTC**
> I solved this in MakumbaJspAnalyzer.java 1.1.4.4 (which is on the 
> refactorTaglib branch). Did not make a new 0.5.9.1 version just for this small 
> change, though. Also not copied to 0.5.8 branch. Not worth the effort?

well, MakumbaJspAnalyzer changed quite a lot from 0.5.8 to 0.5.9 so it's good
that you didn't copy there

i suggest to close this. is the comment 6 author OK with that ? :)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 26 Jun 2003 09:12 UTC**
we've done enough on this, will suggest to generalise a bit of this work in bug 464
