### ISSUE TITLE
lack of proper whitespace in mak:tag fools parser, error message way off

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#217]
**Reported by @frederikhabils on 1 Jun 2003 22:13 UTC**
https://parade.best.eu.org/mak-test-k/events/coordinator/applicantList.jsp?
event=b869mpy

is giving this error

org.makumba.view.jsptaglib.MakumbaJspException: VALUE tag should always be 
enclosed in a LIST or OBJECT tag
in tag: VALUE expr=null parameters: {}
	at org.makumba.view.jsptaglib.ValueTag.canBeRoot(ValueTag.java:92)
	at org.makumba.view.jsptaglib.MakumbaTag.setParent(MakumbaTag.java:66)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.addTag
(MakumbaJspAnalyzer.java:59)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.simpleTag
(MakumbaJspAnalyzer.java:137)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:305)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:257)
	at org.makumba.util.JspParseData.parse(JspParseData.java:199)
	at org.makumba.util.JspParseData.getAnalysisResult
(JspParseData.java:44)
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:144)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:162)
	at org.apache.jsp.applicantList$jsp._jspService
(applicantList$jsp.java:72)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	

with some patience, I managed to figure out that the root cause is this line:
23:	<mak:list from="best.internal.EventApplication ea, ea.participant p" 
where="ea.event=$event"orderBy="p.name, p.surname">

there is NO space just before the orderBy parameter. This seems to seriously 
fool the parser. The error it's reporting, is referring to another mak:object 
tag that starts and end before the root cause.

Again, this is a case of perhaps not needing to support such unsound coding. A 
more appropriate error message would be nice :-)

Migrated-From: http://trac.makumba.org/ticket/461

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 1 Jun 2003 23:26 UTC**
again, i was not aware that JSP allows this

but it's easy for makumba to support it. actually, it's easier to support it
than to detect the actual place of the error. 

well, makumba could look for tags that "may or may not" have spaces between
attributes, then see if they actually contain the "programmatically sound but
lexically not needed" spaces. if not, should there be an error, or a warning on
the log?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Jun 2003 10:50 UTC**
fixed in 0.5.8.4, JspParseData, minor change \s+ -> \s* in the tag attribute 
pattern
