### ISSUE TITLE
position of mak-taglib declarator can fool parser, error message way off

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#218]
**Reported by @frederikhabils on 1 Jun 2003 22:41 UTC**
https://parade.best.eu.org/mak-test-
k/johnny/student/applying/applicationCreate.jsp?season=6a4oggj&activity=ceosukz

gives this errror

org.makumba.view.jsptaglib.MakumbaJspException: VALUE tag should always be 
enclosed in a LIST or OBJECT tag
in tag: VALUE expr=null parameters: {}
	at org.makumba.view.jsptaglib.ValueTag.canBeRoot(ValueTag.java:92)
	at org.makumba.view.jsptaglib.MakumbaTag.setParent(MakumbaTag.java:66)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.addTag
(MakumbaJspAnalyzer.java:59)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.simpleTag
(MakumbaJspAnalyzer.java:137)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:305)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:265)
	at org.makumba.util.JspParseData.parse(JspParseData.java:199)
	at org.makumba.util.JspParseData.getAnalysisResult
(JspParseData.java:44)
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:144)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:162)
	at org.apache.jsp.applicationCreate$jsp._jspService
(applicationCreate$jsp.java:108)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

message looks very similar to bug 461. 

In this case I found that the error disappears when changing the top of the 
source file:

-- from --
<%@ page import="org.eu.best.privatearea.BestCalendar" %>
<%@ page import="org.eu.best.johnny.*" %>
<%@ page import="org.eu.best.util.StringUtils" %>
<%@ page import="org.makumba.Pointer" %>
<%@ page import="java.util.*" %>

<%@ taglib uri="http://www.makumba.org/presentation" prefix="mak" %>

<%
   String thisFile="applicationCreate.jsp";
   Activity activ = null;
%>

-- into --

<%@ taglib uri="http://www.makumba.org/presentation" prefix="mak" %>

<%@ page import="org.eu.best.privatearea.BestCalendar" %>
<%@ page import="org.eu.best.johnny.*" %>
<%@ page import="org.eu.best.util.StringUtils" %>
<%@ page import="org.makumba.Pointer" %>
<%@ page import="java.util.*" %>

<%
   String thisFile="applicationCreate.jsp";
   Activity activ = null;
%>

Now, that's kinda bizarre ?
I've never heard of any rules regarding the position of the taglib declaration:
<%@ taglib uri="http://www.makumba.org/presentation" prefix="mak" %>

... apart from the obvious that it should appear before any usage of makumba 
tags.

Migrated-From: http://trac.makumba.org/ticket/462

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 1 Jun 2003 23:07 UTC**
pretty strange one...
i don't think the fix has to do with the position, but with other peculiarities
of the page. will look into it (in comparison, bug 460, bug 461 and bug 463 are
pretty obvious matters; still, they are very important, very good work Fred!)

**Comment by ghost** [comment]
**Comment by @frederikhabils on 3 Jun 2003 19:49 UTC**
this is extremely puzzling bug... 

I think there is something 'funny' in the parser's expectations about the 
position of 

<%@ page import="..." %> vs. <%@ taglib uri=... prefix="mak" %>

I boiled this down to:
https://parade.best.eu.org/mak-test-k/test/bug462.jsp?activity=ceosukz
--
<%@ page import="org.makumba.Pointer" %>
<%@ page import="org.eu.best.johnny.Activity" %>
<%@ page import="org.eu.best.privatearea.BestCalendar" %>
<%@ page import="org.eu.best.util.StringUtils" %> 
<%@ page import="java.util.*" %> 
 
<%@ taglib uri="http://www.makumba.org/presentation" prefix="mak" %>
  
<mak:object from="best.johnny.Activity ja" where="ja=$activity">
  <mak:value expr="ja.name"/>
</mak:object>
--

which results in 
  --
  Error in JSP Java scriplet or servlet container 
  java.lang.NullPointerException
  --
... and on the log: 
  --
  Jun 3, 2003 9:40:40 PM org.makumba.devel.TagExceptionServlet shortTrace
   SEVERE: servlet call not found in stacktrace
  --


Now, if I remove the first 3 lines (so remove 3 of the 5 page imports), then 
the error turns into:
--
Internal Makumba error 
Please report to the developers.

java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:508)
	at java.util.ArrayList.get(ArrayList.java:320)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.end
(MakumbaJspAnalyzer.java:101)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.endTag
(MakumbaJspAnalyzer.java:148)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:304)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:268)
	at org.makumba.util.JspParseData.parse(JspParseData.java:202)
	at org.makumba.util.JspParseData.getAnalysisResult
(JspParseData.java:47)
	at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:136)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:154)
	at org.apache.jsp.bug462$jsp._jspService(bug462$jsp.java:75)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
--
and java.lang.ClassCastException on repeated loads.


Removing all "page import" lines, or moving the mak-declarator to the top, 
removes the error entirely.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Jun 2003 10:54 UTC**
fixed in 0.5.8.4, JspParseData revision 1.1.2.6-8

the problem is that system tags and normal tags are parsed in parallel, and 
they have separate patterns. this was a problem in intercalating the patterns 
(after each system tag, the parser was looking for the next ordinary tag, and 
vice versa). this probably lead to some mak: tags being found before the taglib 
was encountered...

a more elegant solution would be to use a common pattern for the system tags 
and normal tags, and just check afterwards if < is followed by %@

**Comment by ghost** [comment]
**Comment by cristian_bogdan on 15 Nov 2010 16:48 UTC**
(In [190]) fixed bug 462, there was a problem in the logic that intercalated system tags and tags
