### ISSUE TITLE
empty query leads to RunTimeException

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#219]
**Reported by @frederikhabils on 1 Jun 2003 22:54 UTC**
https://parade.best.eu.org/mak-test-k/johnny/student/general/accountEdit.jspx

gives the error

java.lang.RuntimeException: Empty query?
	at org.makumba.view.jsptaglib.QueryStrategy.doRootStart
(QueryStrategy.java:101)
	at org.makumba.view.jsptaglib.RootQueryStrategy.doStart
(RootQueryStrategy.java:101)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:172)
	at org.apache.jsp.accountEdit$jsp._jspService(accountEdit$jsp.java:181)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

now, there is in this page only a few mak tags:

there is around the whole page :

<mak:object from="best.johnny.Student js, js.student s, s.person p" 
where="js=$student">
<mak:form ...>

</mak:form>
</mak:object>

but no mak values... 

so, as far as I see it now, the mak:object really does nothing but ensure that 
there is a student logged in (already done by BL also) and that he has a 
best.Student and a general.Person properly linked (not needed to check)...

I guess that the mak:object was put there by mistake, or there might have been 
a mak:value, later removed. 

The question is: do we accept this "difference" between 0.5.8 and the earlier 
versions?

Migrated-From: http://trac.makumba.org/ticket/463

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 1 Jun 2003 23:15 UTC**
i don't remember if the empty query actually has some default projections or
not. if not, it will not lead to a valid query (but to SELECT FROM ....WHERE,
i.e. no projections) so we can't leave it like that. i think makumba 0.5.5/7
looks whether the query has any projections, and if not, it simply skips it... 

so i don't think the mak:object in this particular page ever leads to a query,
though the body of the tag is executed due to trying to train a loop. can you
check if a query is executed or not in 0.5.5? (by org.makumba.db logs?)

maybe the $student check was obsoleted by some checkAttributes call and nobody
noticed that $student is never checked?

finally, it doesn't seem correct to me to allow such cases in page analysis...
it will be also hard to implement, because there's no training loop code (that
would simply skip the query but execute the tag body) left around.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 2 Jun 2003 08:37 UTC**
I can't check the things of comment 1 before this evening, but I had some vague 
assumption that in previous makumba versions, the "this" pointer (self, 
identity, ... whatever the proper name) of the data-object was added as default 
projection. 


-> About the question whether empty queries make sense:

I believe it can make sense as test whether certain user should see certain bit 
of page...
example, the http://private.best.eu.org/boxes/helpdeskBox.jspx

a simple version of it could be written as:

<mak:object from="best.helpdesk.Solver sol, sol.solver bis" where="bis=$member">
Hello Solver, have a look at the <a ...>private area for helpdeskers</a>!
</mak:object>

  => using an empty query to determine if proper message should be shown...

another way of writing this:

<mak:object from="best.helpdesk.Solver sol, sol.solver bis" where="bis=$member" 
maxCountVar="mcv">
<% if (mcv.intValue()==1) { out.print(...) } %>


-> WHICH ACTUALLY brings on the question if bug 455 is also solved for single 
tag <mak:object />

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 2 Jun 2003 13:25 UTC**
comment 2:
> but I had some vague 
> assumption that in previous makumba versions, the "this" pointer (self, 
> identity, ... whatever the proper name) of the data-object was added as default 
> projection. 

i think that only happens if the list has embedded lists

> -> WHICH ACTUALLY brings on the question if bug 455 is also solved for single 
> tag <mak:object />
should be, the code i fixed treats all tags equally (MakumbaJspAnalyzer, check
the latest CVS revisions)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 2 Jun 2003 15:34 UTC**
as per bug 25, something is selected if there are no projections
so i guess the code should just ignore that no specific <mak:value > projections
exist?

**Comment by ghost** [comment]
**Comment by @frederikhabils on 2 Jun 2003 19:49 UTC**
about comment 1: I made a test in 0.5.7.6

fred-k/test//bug463.jsp 
--
<%@ taglib uri="http://www.makumba.org/presentation" prefix="mak" %>

<mak:object from="best.johnny.Season ssn" where="ssn.name = $season" >
  there is a season with that name!
</mak:object>
--

produces following output (first with 'summer', then with 'summer03' as 
$season)

"GET /fred-k/test/bug463.jsp?season=summer"

==> /home/projects/parade/server/parade/tomcat/logs/server-output.txt <==
 Jun 2, 2003 9:34:33 PM org.makumba.db.sql.Query execute
 FINE: org.gjt.mm.mysql.jdbc2.PreparedStatement@124588d: 'summer'
 Jun 2, 2003 9:34:33 PM org.makumba.db.sql.Query execute
 FINE: 9 ms SELECT ssn.Season_ AS col1 FROM best_johnny_Season_ ssn WHERE ( 
ssn.name_ = ?)
 Jun 2, 2003 9:34:33 PM org.makumba.view.Grouper <init>
 FINE: grouping 0 ms
 Jun 2, 2003 9:34:33 PM org.makumba.db.sql.Query execute
 FINE: org.gjt.mm.mysql.jdbc2.PreparedStatement@131d024: 'summer'
 Jun 2, 2003 9:34:33 PM org.makumba.db.sql.Query execute
 FINE: 8 ms SELECT ssn.Season_ AS col1 FROM best_johnny_Season_ ssn WHERE ( 
ssn.name_ = ?)
 Jun 2, 2003 9:34:33 PM org.makumba.view.Grouper <init>
 FINE: grouping 0 ms


"GET /fred-k/test/bug463.jsp?season=summer03 HTTP/1.1" 200 -

==> /home/projects/parade/server/parade/tomcat/logs/server-output.txt <==
 Jun 2, 2003 9:35:11 PM org.makumba.db.sql.Query execute
 FINE: org.gjt.mm.mysql.jdbc2.PreparedStatement@157f347: 'summer03'
 Jun 2, 2003 9:35:11 PM org.makumba.db.sql.Query execute
 FINE: 6 ms SELECT ssn.Season_ AS col1 FROM best_johnny_Season_ ssn WHERE ( 
ssn.name_ = ?)
 Jun 2, 2003 9:35:11 PM org.makumba.view.Grouper <init>
 FINE: grouping 0 ms


-- Conclusions: --
1/ the object's id is added as default projection, in case of empty query.
2/ if the query returns 0 elements, it seems to be execute TWICE. -> Why?



I also changed the page to have a non empty query:
--
<mak:object from="best.johnny.Season ssn" where="ssn.name = $season" >
  there is a season with that name: <mak:value expr="ssn.name"/>
</mak:object>
--

"GET /fred-k/test/bug463.jsp?season=summer HTTP/1.1" 200 -

 Jun 2, 2003 9:45:09 PM org.makumba.db.sql.Query execute
 FINE: org.gjt.mm.mysql.jdbc2.PreparedStatement@1a39fdc: 'summer'
 Jun 2, 2003 9:45:09 PM org.makumba.db.sql.Query execute
 FINE: 9 ms SELECT ssn.name_ AS col1 FROM best_johnny_Season_ ssn WHERE ( 
ssn.name_ = ?)
 Jun 2, 2003 9:45:09 PM org.makumba.view.Grouper <init>
 FINE: grouping 0 ms
 Jun 2, 2003 9:45:09 PM org.makumba.db.sql.Query execute
 FINE: org.gjt.mm.mysql.jdbc2.PreparedStatement@1544942: 'summer'
 Jun 2, 2003 9:45:09 PM org.makumba.db.sql.Query execute
 FINE: 8 ms SELECT ssn.name_ AS col1 FROM best_johnny_Season_ ssn WHERE ( 
ssn.name_ = ?)
 Jun 2, 2003 9:45:09 PM org.makumba.view.Grouper <init>
 FINE: grouping 0 ms



"GET /fred-k/test/bug463.jsp?season=summer00 HTTP/1.1" 200 -

 Jun 2, 2003 9:45:39 PM org.makumba.db.sql.Query execute
 FINE: org.gjt.mm.mysql.jdbc2.PreparedStatement@17fd60d: 'summer00'
 Jun 2, 2003 9:45:39 PM org.makumba.db.sql.Query execute
 FINE: 7 ms SELECT ssn.name_ AS col1 FROM best_johnny_Season_ ssn WHERE ( 
ssn.name_ = ?)
 Jun 2, 2003 9:45:39 PM org.makumba.view.Grouper <init>
 FINE: grouping 0 ms


-- Conclusions --
1/ only the requested projection (ssn.name) is put in the Query
2/ again, the query appears to be executed twice when the resultSet is empty.



I didn't do this for 0.5.5, but I guess there's no need. 


I believe empty queries (=without projections) are useful, and properly 
addressed in 0.5.7, so I suggest to keep it that way.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 2 Jun 2003 19:57 UTC**
btw, about my last comment and the double execution of 0-resultSet queries: I 
should add that I ran the query multiple times, so it doesn't seem to be 
related to the self-reloads that 0.5.7 is doing on first execution (in case of 
var/printVar; which there are not anyway).

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 3 Jun 2003 09:09 UTC**
with the test code at comment 5, removing the exception throw lead to no query
being executed (and no complaint about the $season not being found), so this bug
is not trivial
while looking at fixing it, i found that there are still assumptions left in the
code about training loops, so more cleanup is needed
it's interesting how apparently insignificant bugs lead to so important
observations :)

**Comment by ghost** [comment]
**Comment by priit@best.eu.org on 3 Jun 2003 10:23 UTC**
Sometimes the mak:list is only called to get the number of matching rows in the
table. Despite the speed/resource expence issues, I have noticed that (perhaps
unwantedly) people still tend to use 
<mak:list from="..." where="..." maxCountVar="bla"/><%= bla %>
instead of the suggested 
<mak:list from="..." where="..."><mak:value="count(*)"></mak:list>

(cfr www welcome page, some pages in business challenge forum)

While fixing this bug it might be good to make the empty query that wants the 
number of returned rows be executed with "SELECT COUNT(*) FROM ..."
(AFAIK at the moment the query is executed without SELECT COUNT(*) and the size of 
the returned Vector is counted)

**Comment by ghost** [comment]
**Comment by @stefanb on 3 Jun 2003 12:34 UTC**
What Priit described in his comment 8 is also covered by bug 25

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Jun 2003 10:57 UTC**
fixed in 0.5.8.4, org.makumba.view.jsptaglib.QueryStrategy 2.0.4.4-5

i also removed some dead training loop code from QueryStrategy, 
RootQueryStrategy, NullableValueStrategy
