### ISSUE TITLE
newline in tag parameter value not accepted by 0.5.8 parser

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#224]
**Reported by @frederikhabils on 11 Jun 2003 22:23 UTC**
Unlike earlier makumba, 0.5.8(.6) doesn't like it when there is a newline 
INSIDE a tag parameter value. This can happen sometimes when the where clause 
is really long, and you want to keep some clearer layout of the lines, by 
linebreaking in the middle of the WHERE="... \n ..."

example:

<mak:list from="general.Country c" 
where="c.iso2LetterCode = NIL or                       <-- newline at the end
       c.iso2LetterCode IN SET ('be', 'se', 'fr')" >
 Country: <mak:value expr="c.name" /><br>
</mak:list>

java.lang.RuntimeException: could not find cache for 
org.makumba.view.jsptaglib.QueryTag {}
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:161)
	at org.apache.jsp.bug479$jsp._jspService(bug479$jsp.java:65)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
	

found 2 (similar pages in Johnny with this error so far). 

Test case at 
https://parade.best.eu.org/fred-k/test/bug479.jsp

We may decide to not support this new line, but we need to decide either way.

Migrated-From: http://trac.makumba.org/ticket/479

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 11 Jun 2003 23:19 UTC**
i have a hunch that in this case we are dealing with differences in the way
newline is encoded by the JspParseData and by jasper. they both call
QueryTag.setWhere, QueryTag.setFrom, etc. out of a combination of the parameters
that they transmit to these methods, a key is made. the key is used at runtime
to find the cache made at analysis time for the same key, i.e. for the same tag.
in this case, the two keys seem not to match...

maybe it's just an extra \n or \r here and there. i guess that would be
discovered by a call to String.length() ?

adding a println in QueryTag.setWhere to see what length and value does the
"where" string have may be a way to investigate

**Comment by ghost** [comment]
**Comment by @frederikhabils on 18 Jun 2003 21:43 UTC**
i'll try to get deeper, but here are those print outs (cfr comment 1)


setWhere = c.iso2LetterCode = NIL
  or c.iso2LetterCode IN SET ('be', 'se', 'fr')
setWhere string length = 72
java.lang.Throwable
       at org.makumba.view.jsptaglib.QueryTag.setWhere(QueryTag.java:117)
       at org.apache.jsp.bug479$jsp._jspService(bug479$jsp.java:63)
       at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)
       at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)


setWhere = c.iso2LetterCode = NIL
setWhere string length = 24
java.lang.Throwable
       at org.makumba.view.jsptaglib.QueryTag.setWhere(QueryTag.java:117)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
       at java.lang.reflect.Method.invoke(Method.java:324)
       at org.makumba.util.JspParseData.fill(JspParseData.java:397)
       at org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.addTag
(MakumbaJspAnalyzer.java:60)
       at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.simpleTag
(MakumbaJspAnalyzer.java:150)
       at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.startTag
(MakumbaJspAnalyzer.java:155)
       at org.makumba.util.JspParseData.treatTag(JspParseData.java:324)
       at org.makumba.util.JspParseData.treatTags(JspParseData.java:264)
       at org.makumba.util.JspParseData.parse(JspParseData.java:204)
       at org.makumba.util.JspParseData.getAnalysisResult
(JspParseData.java:130)
       at org.makumba.view.jsptaglib.MakumbaTag.getTagCache
(MakumbaTag.java:138)
       at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:159)
       at org.apache.jsp.bug479$jsp._jspService(bug479$jsp.java:65)


so i guess we can assume that the parser is not handling multiline attribute 
values very well.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 19 Jun 2003 00:27 UTC**
i found a problem with JspParseData.java, specifically in this code :

...
// we use a streamtokenizer to do the complicated parsing 
of "...\"\t ...\n...."
StreamTokenizer st= new StreamTokenizer(new StringReader(val));
char quote=val.charAt(0);
st.quoteChar(quote);
try{
	  if(st.nextToken()!=quote)
	    throw new RuntimeException("quoted string expected, found "+val);
}catch(java.io.IOException ioe) { throw new RuntimeWrappedException(ioe);}
String attName= attr.substring(0, n).trim();
ret.put(attName, st.sval);
...

I don't understand the working of StreamTokenizer... it seems to be used to 
replace \" by "

I wrote other code that does the same, and the error is no longer present in 
https://parade.best.eu.org/fred-k/test/bug479.jsp


It needs a bit more of regression testing, because I don't know what (if any) 
other purpose there was to the use of StreamTokenizer above.

Not committed yet, see changes in fred-m.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 19 Jun 2003 13:30 UTC**
comment 3:
indeed, StreamTokenizer is used to replace a \" with ". 

i think StreamTokenizer can be told how to treat newlines in the input (i guess
what happens is that it returns a separate token for the newline, or so)

but if you think the \" -> " problem is simple enough (e.g. \\" is actually \",
and the string must end!), i've nothing against having handmade java code instead

good work!

**Comment by ghost** [comment]
**Comment by @frederikhabils on 21 Jun 2003 00:54 UTC**
this should be fixed together with bug 486 fixing.
=> makumba 0.5.8.8
