### ISSUE TITLE
multipart forms don't work in 0.5.9 : "attribute not found: XYZ_filename"

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#228]
**Reported by @frederikhabils on 22 Jun 2003 09:10 UTC**
found all tested cases of multipart forms (with file upload) to fail in 0.5.9

e.g.
https://parade.best.eu.org/mak-test-k/lbg/member/memberEditPhoto.jsp?
person=fgt3ck0
https://parade.best.eu.org/mak-test-k/archive/officialDocumentEdit.jsp?
document=ej3bzpa
https://parade.best.eu.org/mak-test-k/archive/upload.jsp

stacktrace

org.makumba.AttributeNotFoundException: attribute not found: bytes_filename
	at org.makumba.controller.http.RequestAttributes.getAttribute
(RequestAttributes.java:123)
	at 
org.eu.best.privatearea.LbgMemberMemberEditPhotoLogic.uploadPersonPhoto
(LbgMemberMemberEditPhotoLogic.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.makumba.controller.Logic.doOp(Logic.java:331)
	at org.makumba.controller.http.Responder$4.respondTo
(Responder.java:296)
	at org.makumba.controller.http.Responder.response(Responder.java:229)
	at org.makumba.controller.http.ControllerFilter.doFilter
(ControllerFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)

Migrated-From: http://trac.makumba.org/ticket/490

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 23 Jun 2003 11:31 UTC**
fixed in 0.5.9.1

the form was mistakenly not set as multipart. once that was fixed, everything works.
