### ISSUE TITLE
response handler mixup if dataType changes

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#236]
**Reported by @frederikhabils on 30 Jun 2003 14:54 UTC**
https://parade.best.eu.org/fred-k/test/bug503.jsp (makumba 0.5.9.4)

illustrates a mixup in form response. Suppose you have code

 <mak:form action="#" >
    <mak:input name="foo" dataType="int"/>
    <input type=submit>
 </mak:form>

... and you've submitted the form

then you change the code and change dataType="int" to dataType="char[10]"

reload the form (make absolutely sure to have the updated page, and not
browser-cache)

fill in "abc"
and submit again => error

org.makumba.view.InvalidValueException: Invalid value for expression 'foo':
invalid integer: abc
	at org.makumba.controller.html.FieldEditor.toInt(FieldEditor.java:102)
	at org.makumba.controller.html.intEditor.readFrom(intEditor.java:47)
	at org.makumba.controller.html.RecordEditor.readFrom(RecordEditor.java:49)
	at org.makumba.controller.html.FormResponder.getHttpData(FormResponder.java:45)
	at org.makumba.controller.http.Responder$4.respondTo(Responder.java:296)
	at org.makumba.controller.http.Responder.response(Responder.java:229)
	at org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:56)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:213)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:193)
	at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)

This bug is most likely to complicate developement and testing of other bugs,
not to cause problems in "genuine" use of makumba

Migrated-From: http://trac.makumba.org/ticket/504

**Comment by ghost** [comment]
**Comment by @frederikhabils on 30 Jun 2003 14:55 UTC**
mmm, stefan stole number 503 under my nose :-), so I'll move the example code to 
https://parade.best.eu.org/fred-k/test/bug504.jsp

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Feb 2010 10:58 UTC**
i was struck by a variant of this bug. this is very serious for people who want to adopt makumba because it makes it difficult to change a form while developing. the  dummyName#dummyName error message is terribly fun.

when changing from 

<mak:input dataType='int{ ...}' >

to

<mak:input dataType='set int{ ...}' >

(where both sets are the same, though i don't think that matters)

or when changing the other way around (as was the case in the error below), 

then you get

Makumba invalid value error
/Users/cristi/Documents/itcwork/eclipse_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/webapps/dox/index.jsp

While executing inside this body tag, but most probably *not* due to the tag:/index.jsp:39:1:39:84

<mak:form action="index.jsp" clientSideValidation="false" method="post" message="">
^

Invalid value for dummyName#dummyName: int enumerators only accept values of type Integer or http://java.sun.com/j2se/1.4.2/docs/api/java/lang/String.html" title="java.lang.String">String. Value supplied ([20]) is of type java.util.Vector

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Feb 2010 11:01 UTC**
btw the solution to this is to clean the work dir. you can do it in
eclipse/Server/right-click on the webapp

since it requires work/ clean, it is really serious for development

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 18 May 2010 23:40 UTC**
Basically, the responder key computation would need to take this into account. currently, it includes (in org.makumba.forms.responder.FormResponder):

public String responderKey() {
    return "" + fieldNames + fieldParameters + super.responderKey();
}

with

Hashtable<String, Dictionary<String, Object>> fieldParameters = new Hashtable<String, Dictionary<String, Object>>();

Hashtable<String, String> fieldNames = new Hashtable<String, String>();


one would need to add the DataDefinition of the form additionally, or maybe the editor, as that is already a global field:

editor = new RecordEditor(dd, fieldNames, database, operation.equals("search"), formIdentifier);

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 1 Jul 2010 13:48 UTC**

**Comment by ghost** [comment]
**Modified by @cristianbogdan on 4 Apr 2016 12:20 UTC**
