### ISSUE TITLE
providing set values for mak:input

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#237]
**Reported by @cristianbogdan on 30 Jun 2003 15:06 UTC**
since there is a possibility to provide values for all non-set types and
dataType=set... is supported, there should be a way to also provide values for
such mak:inputs (see bug 375 comment 2, bug 375 comment 3)

Migrated-From: http://trac.makumba.org/ticket/505

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 30 Jun 2003 15:14 UTC**
the OQL way to express sets is SET (OQLConstant1, OQLConstant2), in which case
an empty SET would be SET(). but i'm not sure that is accepted in projections.
certainly makumba doesn't know how to read that.

probably the way to support it is to parse the OQLConstant1...N list...

as a workaround, $value, where value is a (possibly empty) vector computed in
java should work

the fix of this bug should also provide a more meaningful error than the
stacktrace that Fred found, which i copy here:

 <mak:input name="letter" value="nil" dataType='int{"A"=0, "B"=1, "C"=2}'/>
 <mak:input name="letter" value="nil" dataType='set int{"A"=0, "B"=1, "C"=2}'/>


java.sql.SQLException: Syntax error or access violation,  message from server:
"You have an error in your SQL syntax.  Check the manual that corresponds to
your MySQL server version for the right syntax to use near '' at line 1"
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1651)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:889)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:956)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:1874)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1538)
	at org.makumba.db.sql.Query.execute(Query.java:85)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:180)
	at org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:44)
	at org.makumba.view.AttributeParametrizer.execute(AttributeParametrizer.java:174)
	at
org.makumba.view.MultipleAttributeParametrizer.execute(MultipleAttributeParametrizer.java:47)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:332)
	at org.makumba.view.jsptaglib.QueryExecution.<init>(QueryExecution.java:88)
	at org.makumba.view.jsptaglib.QueryExecution.getFor(QueryExecution.java:76)
	at org.makumba.view.jsptaglib.FormTagBase.doMakumbaStartTag(FormTagBase.java:128)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:171)

**Comment by ghost** [comment]
**Comment by @frederikhabils on 30 Jun 2003 15:32 UTC**
> as a workaround, $value, where value is a (possibly empty) vector computed in
> java should work

in
https://parade.best.eu.org/fred-k/johnny/superuser/studentApplicationsAll.jspx#425
I have recorded that in my experience, and tested on the makumba version then in
use (0.5.5 something, or perhaps even earlier)

pageContext.setAttribute("filterFinal",vFilterF);
<mak:list where="bjap.finalStatus IN set($filterFinal)" ... >

requires that vFilterF is a NON-EMPTY Vector.

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 10:06 UTC**
