### ISSUE TITLE
int{} - "deprecated" values,

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#24]
**Reported by @cristianbogdan on 20 Oct 2002 17:08 UTC**
when the options of char{} get deprecated or need to be renamed, one discovers
that the typs is extremely inflexible. thus it should be deprecated, and (few)
existing instances should be transformed to int{}

int{} options should allow deprecation in notations like

"blabla"=1 deprecated, ...

which would still allow the values in the db, but no new values from input, etc

Migrated-From: http://trac.makumba.org/ticket/28

**Comment by ghost** [comment]
**Comment by @stefanb on 2 Jul 2003 20:35 UTC**
char{} is only used in 2 MDDs in karamba:
$ fgrep -n 'char{' `find . -name '*dd'`
best/johnny/Activity.mdd:40:type=char{"Learning Event - Technological 
Course", "Learning Event - Language Course", "Learning Event - Career Related 
Skill Course", "Event on Education - IBS", "Event on Education - 
IBS+", "Leisure Event", "Engineering Competition", "Promotion-only Event", "----
- Below : old, not to be used types -----",  "Academic", "Non-
academic", "Summer Course", "Short Intensive Training", "Language 
Course", "IBS", "Unknown" }
/best/Student.mdd:42:  education->typeofstud=char
{"Undergraduate", "Postgraduate"} ;Type

and in 2 real (non test) jsp pages:
$ fgrep -n 'char{' `find . -name '*.jsp'`
./public_html/minerva/student/find_acti.jsp:30:         <mak:input 
name="activityKinds" dataType="set char{\"conference\", \"contest\", \"cultural 
event\", \"internship\", \"job\", \"jobfair\", \"other\", \"final project 
proposal\", \"seminar\"}"/>
./public_html/minerva/student/mess_part.jsp:38: <mak:input 
name="activityKinds"  dataType="set char{\"conference\", \"contest\", 
\"cultural event\", \"internship\", \"job\", \"jobfair\", \"other\", \"final 
project proposal\", \"seminar\"}" value="$bla"/>

---> so automating the char{} -> int{} transition might not be so cruical, 
because it can probably be easier done by hand.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 22 Aug 2003 11:49 UTC**
Stefan, since you got closer to the MDD parser, do you think adding support for
deprecated there will be easy?
same goes for checking the deprecated value (i guess it's also in
org.makumba.abstr?)
trimming the charEnum classes from the code will be easy enough i guess...

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 25 Sep 2003 09:56 UTC**
comment 1:
"char {" is also used in one place, best.minerva.Student#activityFields, see bug 596

**Comment by ghost** [comment]
**Comment by @stefanb on 6 Oct 2003 01:39 UTC**
I have the abstract part of int{ ... deprecated, ...} ready, but am wondering
>"blabla"=1 deprecated, ...
>which would still allow the values in the db, but no new values from input, etc
Would this mean that deprecated values should be possible to insert via API or not?
IMO yes, users should still be allowed to enter such values if programmer really
wants them to do so.

So this just needs additional change in taglib to hide deprecated values in
intEnum editor, but leave current value as option in the chooser even if it is
deprecated.

or...?

Not quite sure how char{} could be deprecaed other than in the docs (done). 
Meybe a warning on the log whenever such field is read from MDD?

note that "deprecated"!="drop support"

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 10 Oct 2003 14:39 UTC**
comment 4:

yep, i think the db should still allow deprecated values though it could print a
warning on the log or so

> Not quite sure how char{} could be deprecaed other than in the docs (done). 
> Meybe a warning on the log whenever such field is read from MDD?

well, i do think that, since only best uses makumba and there are a hanful of
char{} only, we should really convert those to int{} and drop the support 

deprecated does mean "support may be dropped in the future"

comment 5: checked the patch, well done! i just think getDeprecatedValues is a
better method name instead of getDeprValues.

what's left now is not to show the respective values in the interface except
when editing the records that use them in the db (and maybe indicate somehow in
the interface that they are deprecated)

**Comment by ghost** [comment]
**Comment by @stefanb on 11 Oct 2003 04:20 UTC**
(From update of attachment 38)
I have problems using  and making HtmlChoiceWriter useful in the new
controller.html.* classes, so am committing the abstract part. 

Fred, if you have some time/will over the weekend to make it work, please do
so.

Checking in classes/org/makumba/abstr/Enumerator.java;
/usr/local/cvsroot/makumba/classes/org/makumba/abstr/Enumerator.java,v	<-- 
Enumerator.java
new revision: 2.1; previous revision: 2.0
done
Checking in classes/org/makumba/abstr/FieldCursor.java;
/usr/local/cvsroot/makumba/classes/org/makumba/abstr/FieldCursor.java,v  <-- 
FieldCursor.java
new revision: 2.1; previous revision: 2.0
done
Checking in classes/org/makumba/abstr/FieldHandler.java;
/usr/local/cvsroot/makumba/classes/org/makumba/abstr/FieldHandler.java,v  <-- 
FieldHandler.java
new revision: 2.3; previous revision: 2.2
done
Checking in classes/org/makumba/abstr/intEnumHandler.java;
/usr/local/cvsroot/makumba/classes/org/makumba/abstr/intEnumHandler.java,v  <--
 intEnumHandler.java
new revision: 2.2; previous revision: 2.1
done
Checking in classes/org/makumba/abstr/printer/intEnumPrinter.java;
/usr/local/cvsroot/makumba/classes/org/makumba/abstr/printer/intEnumPrinter.jav
a,v  <--  intEnumPrinter.java
new revision: 2.2; previous revision: 2.1
done

**Comment by ghost** [comment]
**Comment by @frederikhabils on 11 Oct 2003 08:34 UTC**
hi! Stefan, I'm not sure what you want of me in comment 7. Was it solved by
comment 8? (perhaps discuss on icq if you find me?)

BTW, I had some instinctive doubts about adding the notion of "deprecated"
values to the HtmlChoiceWriter (HCW). HCW is sort of a wrapper to write HTML,
and so far HCW only knew the concepts known by HTML. Until I look at that code
more, I don't know if it would be more natural for the caller of HCW to just
change its arguments for the call, or to add the deprecatedValue notion to HCW,
as you did. Anyway, we can move forward as you want, and refactor later if need be.

I will try now to commit the work of bug 585 to a release.

**Comment by ghost** [comment]
**Comment by @stefanb on 12 Oct 2003 20:01 UTC**
re comment 9: 
No, Fred, attachment 39 is not solving this, it just adds some (untested!)
support to the HCW. 

The remaining problem is elegantly specializing intEnumEditor to pass
deprecatedValues and leave everything else to be done in generic choiceEditor.
This might require a bit of redesign of HCW API (the earlier the easier).

**Comment by ghost** [comment]
**Comment by @stefanb on 21 Oct 2003 03:31 UTC**
choiceEditor is now making use of the info about deprecated options in the
abstract layer and calls the HtmlChoiceWriter with that info if data types are
supporting it.

Tested a bit (select, radio, checkbox inputs) but review could be useful.
Maybe HCW needs an update in its API.

Checking in classes/org/makumba/controller/html/choiceEditor.java;
/usr/local/cvsroot/makumba/classes/org/makumba/controller/html/choiceEditor.java,v
 <--  choiceEditor.java
new revision: 2.5; previous revision: 2.4
done
Checking in classes/org/makumba/HtmlChoiceWriter.java;
/usr/local/cvsroot/makumba/classes/org/makumba/HtmlChoiceWriter.java,v  <-- 
HtmlChoiceWriter.java
new revision: 2.4; previous revision: 2.3
done

I moved "char{} full deprecation" part of this bug to bug 622 and bug 623, as it
is unrelated to this one in terms of implementation.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 30 Nov 2003 23:29 UTC**
Not sure if it's better to create a new bug, or continue here.

Anyway, I noticed that the implementation is buggy. 

format() in controller.html.ChoiceEditor is calling "getDeprecatedValues()" in
abstr.FieldHandler. 
ChoiceEditor.format() is being used for all (almost all?) the inherited classes,
like charEnumEditor, ptrEditor. (that is, the format() method is never overridden)

Supposedly that "getDeprecatedValues" method should only be called on
abstr.intEnumHandler types. 
Also supposedly, the error should be ClassCastException. 

But, after installing 0.5.9.16 in my (and a bunch of other parade-rows) i
noticed that it's causing this error :

java.lang.NullPointerException
	at org.makumba.abstr.FieldHandler.getDeprecatedValues(FieldHandler.java:160)
	at org.makumba.abstr.FieldHandler.getDeprecatedValues(FieldHandler.java:160)
	at org.makumba.controller.html.choiceEditor.format(choiceEditor.java:110)
	at org.makumba.view.RecordFormatter.format(RecordFormatter.java:59)
	at org.makumba.controller.html.FormResponder.format(FormResponder.java:72)
	at org.makumba.view.jsptaglib.InputTag.doMakumbaEndTag(InputTag.java:179)
	at org.makumba.view.jsptaglib.MakumbaTag.doEndTag(MakumbaTag.java:190)
	at org.apache.jsp.eventCreate$jsp._jspService(eventCreate$jsp.java:450)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

e.g. on
https://parade.best.eu.org/fred-k/johnny/lbg/announcing/organiser/edit/eventCreate.jsp?season=spring04

Stefan, you have time to delve into this soonish?

**Comment by ghost** [comment]
**Comment by @frederikhabils on 1 Dec 2003 23:22 UTC**
comment 12 should be fixed by the latest commit :

/usr/local/cvsroot/makumba/classes/org/makumba/abstr/FieldHandler.java,v 
new revision: 2.4; previous revision: 2.3

/usr/local/cvsroot/makumba/classes/org/makumba/controller/html/choiceEditor.java,v
 new revision: 2.7; previous revision: 2.6

to be released asap.

**Comment by ghost** [comment]
**Comment by stefanba on 15 Nov 2010 16:57 UTC**
(In [567]) Fixed bug 28 (support for deprecated values in intEnum also in presentation layer)

**Comment by ghost** [comment]
**Comment by fred on 15 Nov 2010 16:58 UTC**
(In [598]) fix bug 28 comment 12 : call to getDeprecatedValues wasn't working well

**Comment by ghost** [comment]
**Comment by fred on 15 Nov 2010 16:58 UTC**
(In [599]) work done : fix bug 28 comment 12
