### ISSUE TITLE
spaces or weird characters in field names are not prevented

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#251]
**Reported by @stefanb on 20 Aug 2003 07:30 UTC**
MDD with line:
name of person = not null char[10]

is parsed normally without a problem.
MDD parser should probably throw a DataDefinitionParseError because i believe
makumba can't work with field names like "name of person"
(or replace  spaces with '_' on the abstact level)

Migrated-From: http://trac.makumba.org/ticket/526

**Comment by ghost** [comment]
**Comment by @stefanb on 20 Aug 2003 11:56 UTC**
This now has a test case 
http://cvs.makumba.org/cgi-bin/cvsweb.cgi/makumba/classes/test/brokenMdds/Bug526.mdd
http://cvs.makumba.org/cgi-bin/cvsweb.cgi/makumba/classes/test/mdd.java
which fails with:
     [2)
testBrokenMddBug526(test.mdd)junit.framework.AssertionFailedError: Should raise
DataDefinitionParseError
     [java](java])     at test.mdd.testBrokenMddBug526(mdd.java:75)
     [    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java](java])     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
     [    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
     [java](java])     at test.all.main(all.java:37)

**Comment by ghost** [comment]
**Comment by @stefanb on 23 Aug 2003 12:08 UTC**
besides spaces:
  http://cvs.makumba.org/classes/test/brokenMdds/NameContainsSpaces.mdd
also weird characters (#$%^&") are allowed in field names:
  http://cvs.makumba.org/classes/test/brokenMdds/NameContainsWeirdCharacters.mdd

Error reports are missing from both above listed broken MDDs.

**Comment by ghost** [comment]
**Comment by @stefanb on 28 Dec 2003 10:10 UTC**
I fixed this a while ago in:
http://cvs.makumba.org/classes/org/makumba/abstr/RecordParser.java.diff?r1=2.0&r2=2.1&f=h
but forgot to mention in bugzilla.

It was done together with checking data type names:
http://cvs.makumba.org/classes/org/makumba/abstr/RecordInfo.java.diff?r1=2.1&r2=2.2&f=h
