### ISSUE TITLE
db.getName()!=MakumbaSystem.getDefaultDatabaseName()

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#252]
**Reported by @stefanb on 20 Aug 2003 11:49 UTC**
Someone might expect that methods 
http://www.makumba.org/hacking/javadoc/org/makumba/MakumbaSystem.html#getDefaultDatabaseName(java.lang.String)
http://www.makumba.org/hacking/javadoc/org/makumba/MakumbaSystem.html#getDefaultDatabaseName()
and
http://www.makumba.org/hacking/javadoc/org/makumba/Database.html#getName()
would return same, but they don't necesarily do that.

Running config test
http://cvs.makumba.org/cgi-bin/cvsweb.cgi/makumba/classes/test/config.java
with "ant test" reports:
     [1) testDBDiscovery(test.config)junit.framework.AssertionFailedError:
expected:<test/localhost_mysql_makumba> but was:<localhost_mysql_makumba>
     [java](java])     at test.config.testDBDiscovery(config.java:69)
     [    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java](java])     at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
     [    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
     [java](java])     at test.all.main(all.java:37)

Either this needs to be fixed or documented in javadoc.

Migrated-From: http://trac.makumba.org/ticket/527

**Comment by ghost** [comment]
**Comment by @stefanb on 20 Aug 2003 16:34 UTC**
the test, which should in my opinion pass is:
  public void testDBDiscovery()
  {
    String
preferredDB=MakumbaSystem.getDefaultDatabaseName("test/testDatabase.properties");
    Database db=MakumbaSystem.getConnectionTo(preferredDB);
    assertEquals(preferredDB, db.getName());
    db.close();
  }

...but it fails as said in comment 0

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 14 Jan 2009 20:05 UTC**
the implementation of these methods / the definition of these methods does not exist any longer with the new configuration
