### ISSUE TITLE
jasper2 doesn't doAfterBody() for simple & empty-body tags -> ArrayIndexOutOfBounds in org.makumba.util.MultipleKey

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#270]
**Reported by @frederikhabils on 6 Sep 2003 12:37 UTC**
Scenario: 
company logs in minerva, chooses to "find student", gives in search criteria,
and is returned a list of students.

Clicking on those studens often, but not always (about 60% in my brief test)
fails to open, with this message:

Internal Makumba error 

Please report to the developers.

java.lang.ArrayIndexOutOfBoundsException: 4
	at org.makumba.util.MultipleKey.<init>(MultipleKey.java:75)
	at org.makumba.util.MultipleKey.<init>(MultipleKey.java:69)
	at org.makumba.view.Grouper.getKey(Grouper.java:111)
	at org.makumba.view.Grouper.getData(Grouper.java:102)
	at
org.makumba.view.jsptaglib.QueryExecution.getIterationGroupData(QueryExecution.java:96)
	at
org.makumba.view.jsptaglib.QueryExecution.onParentIteration(QueryExecution.java:113)
	at org.makumba.view.jsptaglib.QueryTag.doMakumbaStartTag(QueryTag.java:128)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:171)
	at org.apache.jsp.student_jsp._jspx_meth_mak_list_4(student_jsp.java:1424)
	at org.apache.jsp.student_jsp._jspService(student_jsp.java:372)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:136)
	
--------------------------------------------------------------------------------
Makumba developer support, version: 0.5.9.6 

FAILS
https://parade.best.eu.org/fred-k/minerva/company/student.jsp?name=Ruth&surname=Suarez
https://parade.best.eu.org/fred-k/minerva/company/student.jsp?name=Jessica&surname=Silva
https://parade.best.eu.org/fred-k/minerva/company/student.jsp?name=Sara&surname=Randstrom
https://parade.best.eu.org/fred-k/minerva/company/student.jsp?name=Cornelia&surname=Parvu
https://parade.best.eu.org/fred-k/minerva/company/student.jsp?name=Nadia&surname=Abdalla-Idris
https://parade.best.eu.org/fred-k/minerva/company/student.jsp?name=Mar

Migrated-From: http://trac.makumba.org/ticket/555

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 6 Sep 2003 22:26 UTC**
did this work during regression tests?

i'd suggest trying to test this in a tomcat with jasper1
then a tomcat with antlr 2.7.1...
if both fail, the problem is somewhere in the difference between 0.5.5 and 0.5.9
or in the data...

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 6 Sep 2003 22:31 UTC**
i can look at this the earliest tomorow eve

i recommend using a tomcat on tequila (which still has jikes 1.11 as default),
maybe connected to the real database

my tomcat can be safely used, just backup the jasper2 jars and replace them with
japser1 ones

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 7 Sep 2003 00:28 UTC**
ok, the problem is new to jasper2. 
here is a 0.5.9.6 running jasper1 (0.5.9.5 worked too)
http://tequila.best.eu.org:11666/minerva/company/student.jsp?name=Mar

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 7 Sep 2003 10:41 UTC**
a possible clue to fixing this:

the main difference between jasper1 and jasper2 is that jasper1 creates new tag
objects (new org.makumba.view.jsptaglib.QueryTag) every time a tag is
encountered, while jasper2 keeps such tag objects in a pool and reuses them. for
that to work, good tag cleaning is needed after the tag usage in a page has ended. 

there were 2 other jasper2 bugs, they were both an instance of this problem

**Comment by ghost** [comment]
**Comment by @frederikhabils on 7 Sep 2003 13:24 UTC**
some observations from ongoing experiments. 

- i installed a jasper2 / jikes 1.18 / antlr 2.7.2 / makumba 0.5.9.6 on
tequila:12007 (this setup is changing as i experiment)

- jasper has a configuration setting "enablePooling" (tomcat/conf/web.xml),
default =true. Setting this to "false" did not solve the issue. IFF it had made
the error go away, i would have seen it as a confirmation of suspicion in
comment 4. 

Note that I'm not sure it works the other way around... that is: this experiment
might NOT prove that comment 4 is a wrong lead.

- finally, the distinguishing characteristic between the pages
(student.jsp?user) working and not working, seems to be that those WORKING have
adresses, while those not working, have NO addresses, in their data.

note, addresses are of type "internal set" in general.Person.
I will experiment with Johnny, since theoretically then, it should (might?) have
the same problem.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 7 Sep 2003 14:56 UTC**
some more ongoing observations.

http://tequila.best.eu.org:12007/minerva/company/student.jspx

on line 133 there is an EMPTY <mak:list /> to count the addresses.
on line 192 there is a nested mak:list, listing over studyfields, within a list
of education.

http://tequila.best.eu.org:12007/minerva/company/student.jspx#133
http://tequila.best.eu.org:12007/minerva/company/student.jspx#192

(if no karamba installed on port 12007, try these links on e.g.
private.best.eu.org/ )

these elements are "conflicting"... 
- if you OPEN (make it NON-EMPTY) the mak:list of line 133, like in 
http://tequila.best.eu.org:12007/minerva/company/student.test4.jsp?name=Frederik&surname=Habils

  _or_

- if you remove the nested mak:list  of line 192, like in 
http://tequila.best.eu.org:12007/minerva/company/student.test1.jsp?name=Frederik&surname=Habils

... Then the page will work just fine on jasper 2. (tests done with
enablePooling=false, which I can tell results in different code than with
enablePooling=true)

I have no yet figured out the fundamental cause of this.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 7 Sep 2003 16:24 UTC**
I'm narrowing this down to a change in Jasper1 -> Jasper2 approach of simple and
empty-body tags. Still the bug also appears with jasper1.


definitions: 
  EMPTYTAG  = <mak:list ... ></mak:list>
  NONEMPTY  = <mak:list ... > sth </mak:list>
  SIMPLETAG = <mak:list .../>

jasper2 was tested with enablePooling=false in tomcat/conf/web.xml

jasper1, EMPTY tag - compiles to ...
   .doStartTag()
   .doEndTag()
   .release()

jasper1, NONEMPTY & SIMPLE - compiles to ...
   .doStartTag()
   if not ...SKIP_BODY { 
      do ... while(doAfterBody == EVAL_BODY_AGAIN)
   }
   .doEndTag()
   .release()

jasper2 - EMPTY & SIMPLE - compiles to ...
   .doStartTag()
   .doEndTag()

jasper2 - NONEMPTY - compiles to ...
   .doStartTag()
   if not ...SKIP_BODY { 
      do ... while(doAfterBody == EVAL_BODY_AGAIN)
   }
   .doEndTag()

(note: I'm assuming that jasper2 will execute release() if enablePooling=true)

so BOTTOMLINE : 
- jasper2 does NOT execute the doAfterBody in case of EMPTY or SIMPLE tag. 
- jasper1 does NOT execute the doAfterBody in case of EMPTY.

So, I'll take a wild guess that not executing the doAfterBody, leaves the
QueryExecution in some inconsistent state, as moving on to next mak:list queries.


I've created a reduced jsp page, based on comment 6, with only the constructs
found to be conflicting.

-> The bug is appearing (only) in all cases where doAfterBody() is NOT executed.

-> It proves also that with jasper1, this bug appears, if the SIMPLE tag
(wrongly described as "empty" before) is made EMPTY (see definitions above)
http://tequila.best.eu.org:11666/minerva/company/student.test2.jsp?name=Frederik&surname=Habils

**Comment by ghost** [comment]
**Comment by @frederikhabils on 7 Sep 2003 21:03 UTC**
continuing on previous work, this is fixed in makumba 0.5.9.7.

http://cvs.makumba.org/cgi-bin/cvsweb.cgi/makumba/classes/org/makumba/view/jsptaglib/QueryExecution.java
http://cvs.makumba.org/cgi-bin/cvsweb.cgi/makumba/classes/org/makumba/view/jsptaglib/QueryTag.java

previously, QueryExecution depended on the last iteration's doAfterBody() call
to to QueryExecution.nextGroupIteration() to remove the iterationGroupData's
currentListData from the Stack. (sorry for the long words ;) )

Now, a new QueryExecution.endIterationGroup() called from
QueryTag.doMakumbaEndTag() will restore the Stack to correct state;
QueryExecution.nextGroupIteration() is no longer trying to do that. 

I do hope I've got the right understanding of these 2 classes, and there are no
new errors introduced ;-)

note: pages tested are also working with enablePooling=true.

**Comment by ghost** [comment]
**Comment by fred on 15 Nov 2010 16:52 UTC**
(In [370]) fix bug 555, iterationGroup does not depend on doAfterBody
