### ISSUE TITLE
the post-table-creation timeout in ODBC/access needs be configurable

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#275]
**Reported by @cristianbogdan on 11 Sep 2003 17:06 UTC**
i started to work with ODBC to be able to read/write in Excel files

ever since we started with makumba, we knew that for the data written by makumba
via ODBC connections to be saved, it is necessary to close the physical db
connections.

since we changed the semantics of org.makumba.Database#close(), we don't have a
method to do physical connection closing. 

i suggest to have 
MakumbaSystem.closeConnectionsTo(database_name)
i also made an implementation (will attach a patch here), it's not perfect (the
connections that are not in the pool will not be closed) but it's ok to be able
to work with ODBC.

Migrated-From: http://trac.makumba.org/ticket/564

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 12 Sep 2003 08:39 UTC**
just closing the db connections at the end does not seem to be enough for
ODBC/Access (while it seems OK for Excel).

in the example below, it creates a table and then it can't find it.
interestingly, the table exists in the db, and the problem is not reported at
the next run...

     [INFO: localhost_odbc_propan: checking org.makumba.db.Catalog as org_
makumba_db_Catalog_
     [java](java]) 12-Sep-2003 10:33:44 org.makumba.db.sql.RecordManager create
     [INFO: CREATE TABLE org_makumba_db_Catalog_(Catalog_ INT,TS_modify_ T
IMESTAMP,TS_create_ TIMESTAMP,name_ VARCHAR(200))
     [java](java]) 12-Sep-2003 10:33:44 org.makumba.db.sql.FieldManager manageIndexes
     [INFO: UNIQUE INDEX ADDED on org.makumba.db.Catalog#Catalog (Unique i
ndex)

*********** and so on for all fields *******'

     [java](java]) 12-Sep-2003 10:33:44 org.makumba.db.sql.Database logException

     [in db command SELECT c.Catalog_ FROM org_makumba_db_Catalog_ c WHERE
 ( c.name_ = ?)
     [java](java]) WARNING: connection 8 [Microsoft Access Driver](Microsoft][ODBC) The
Microsoft Jet database engine cannot find the input table or query 'org_makumba_
db_Catalog_'.  Make sure it exists and that its name is spelled correctly. SQL s
tate: S0002 error code :-1305

     [java.sql.SQLException: [Microsoft](java])[Microsoft Access Driver](ODBC) The
 Microsoft Jet database engine cannot find the input table or query 'org_makumba
_db_Catalog_'.  Make sure it exists and that its name is spelled correctly.
     [    at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6879)

     [java](java])     at sun.jdbc.odbc.JdbcOdbc.standardError(JdbcOdbc.java:7036)
     [    at sun.jdbc.odbc.JdbcOdbc.SQLExecute(JdbcOdbc.java:3104)
     [java](java])     at sun.jdbc.odbc.JdbcOdbcPreparedStatement.execute(JdbcOdbcPrepa
redStatement.java:214)
     [    at sun.jdbc.odbc.JdbcOdbcPreparedStatement.executeQuery(JdbcOdbc
PreparedStatement.java:89)
     [java](java])     at org.makumba.db.sql.Query.execute(Query.java:85)
     [    at org.makumba.db.DBConnection.executeQuery(DBConnection.java:18
0)
     [java](java])     at org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionW
rapper.java:44)
     [java]     at org.makumba.db.Database.addTable(Database.java:459)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 21 Sep 2003 05:03 UTC**
it seems that this has mostly to do with db structure. once the db is built 
correctly, normal db operations work ok

in Access, committing the transaction after each table creation and pausing for 
500 ms (if safe transactions are on) or 2000 ms (if they are off) solved the 
problem

in excel, "ant test" doesn't work, presumably due to the structure of 
test.Person. however, i have another application that works OK with excel.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 13 Oct 2003 21:53 UTC**
i'm reusing this bug rather than creating a new one, as the problem is not
totally solved, a small subproblem is left

it seems that the post-table-creation timeout varies from an application to
another. couldn't yet find a rule. should be configurable from
localhost_odbc_dbname.properties

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 26 Jun 2010 16:49 UTC**
