### ISSUE TITLE
ALTER TABLE has different syntax in ODBC

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#277]
**Reported by @cristianbogdan on 11 Sep 2003 17:19 UTC**
this was actually coming from another bug, see 
http://cvs.best.eu.org/cgi-bin/cvsweb.cgi/makumba/classes/org/makumba/db/sql/odbcjet/?sortby=date
so in my case ALTER is not needed anymore, but i guess it will be needed soon

     [11-Sep-2003 18:56:46 org.makumba.db.sql.RecordManager alter
     [java](java]) INFO: localhost_odbc_propan: ALTER TABLE propan_Formatie_ MODIFY per
soane_ INT
     [java.sql.SQLException: [Microsoft](java])[Excel Driver](ODBC) Syntax error i
n ALTER TABLE statement.
     [    at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6879)

     [java](java])     at sun.jdbc.odbc.JdbcOdbc.standardError(JdbcOdbc.java:7036)
     [    at sun.jdbc.odbc.JdbcOdbc.SQLExecDirect(JdbcOdbc.java:3065)
     [java](java])     at sun.jdbc.odbc.JdbcOdbcStatement.execute(JdbcOdbcStatement.jav
a:338)
     [    at sun.jdbc.odbc.JdbcOdbcStatement.executeUpdate(JdbcOdbcStateme
nt.java:288)
     [java](java])     at org.makumba.db.sql.RecordManager.alter(RecordManager.java:362
)
     [    at org.makumba.db.sql.RecordManager.alter(RecordManager.java:308
)
     [java](java])     at org.makumba.db.sql.RecordManager.checkStructure(RecordManager
.java:166)

Migrated-From: http://trac.makumba.org/ticket/566

**Comment by ghost** [comment]
**Comment by @stefanb on 11 Sep 2003 18:11 UTC**
http://msdn.microsoft.com/library/en-us/odbc/htm/odbcjetsdk_113.asp?frame=true
says
ALTER TABLE statements are not supported for the Microsoft Excel or Text drivers.

while 
http://msdn.microsoft.com/library/default.asp?url=/library/en-us/odbc/htm/lr30b_1.asp
specifies the syntax. 

I'm not fully understanding these conflicting pieces of information.

THe only difference seems to be ODBC / ODBCJET.
What are you using, cristi?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 21 Sep 2003 04:32 UTC**
i use odbcjet (i guess it's the only one that works with access)
the first url you point says that it will work with Access if fields are 
missing (checked, it works), and it will not work with excel

so this is correct, case closed
