### ISSUE TITLE
"not a valid bookmark" error with MS access

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#280]
**Reported by @cristianbogdan on 12 Sep 2003 08:49 UTC**
no idea what this error means.
it's strange that Access tries to execute the query while one of the referred
tables (propan_Formatie_ ) does not exist. that leads to the idea that the
detection of table existence doesn't work in access.

     [WARNING: connection 9 [Microsoft](java])[Microsoft Access Driver](ODBC) Not
a valid bookmark. SQL state: S1000 error code :-1045

     [in db command SELECT s.formatie_,s.comanda_ FROM propan_Solutie_ s
     [java](java]) java.sql.SQLException: [Microsoft Access Driver](Microsoft][ODBC) Not
 a valid bookmark.
     [    at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6879)

     [java](java])     at sun.jdbc.odbc.JdbcOdbc.standardError(JdbcOdbc.java:7036)
     [    at sun.jdbc.odbc.JdbcOdbc.SQLExecute(JdbcOdbc.java:3104)
     [java](java])     at sun.jdbc.odbc.JdbcOdbcPreparedStatement.execute(JdbcOdbcPrepa
redStatement.java:214)
     [    at sun.jdbc.odbc.JdbcOdbcPreparedStatement.executeQuery(JdbcOdbc
PreparedStatement.java:89)
     [java](java])     at org.makumba.db.sql.Query.execute(Query.java:85)
     [    at org.makumba.db.DBConnection.executeQuery(DBConnection.java:18
0)
     [java](java])     at org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionW
rapper.java:44)

Migrated-From: http://trac.makumba.org/ticket/569

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 12 Sep 2003 08:58 UTC**
> it's strange that Access tries to execute the query while one of the referred
> tables (propan_Formatie_ ) does not exist. that leads to the idea that the
> detection of table existence doesn't work in access.

this is not the case, the table is not needed by makumba to execute the query
that gives the "bookmark" error. when running the example on an empty excel
sheet, the table is created afterwards, due to an insert.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 21 Sep 2003 03:24 UTC**
discovered that the problem occurs if the database is corrupted

it seems that corruption can be avoided if the transaction is committed after 
an index has been created (or re-created, see bug 565) and there is a sleep for 
a certain timeout... the timeout can be 0 if (in the ODBC connections window) 
the ODBC parameter "safetransactions" is set to 1. otherwise the timeout (on my 
amachine) seems to be 200 ms
