### ISSUE TITLE
OQL date, time literal not supported? (e.g. DATE '1975-07-20' )

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#285]
**Reported by @frederikhabils on 14 Sep 2003 16:02 UTC**
OQL syntax says 

<quote>
Date Literals : OQL provides literals for: 
- Date. The keyword DATE followed by a single quoted string of the form
year-month-day (DATE '1997-11-07') 
- Time. The keyword TIME followed by a single quoted string of the form
hour:minutes:seconds (TIME '14:23:05.3') 
- Timestamp. The keyword TIMESTAMP followed by a single quoted string consisting
of a date and a time (TIMESTAMP '1997-11-07 14:23:05.3') 
</quote>

http://cvs.best.eu.org/cgi-bin/cvsweb.cgi/~checkout~/makumba/classes/org/makumba/db/sql/oql/oql.html?rev=2.0&content-type=text/html
 or also http://castor.exolab.org/oql.html

I can't get this to work in makumba.

code is e.g. 

<mak:list from="general.Person p" where="p.name LIKE 'Fre%' and p.birthdate <
DATE \"1975-07-20\" " >
    <mak:value expr="p.name" /><mak:value expr="p.birthdate" />
</mak:list>

error is e.g. : 

Makumba query error 

Invalid value for general.Person#birthdate: Required Java type:java.util.Date ;
given value: 1975-07-20 of type java.lang.String
in query:
SELECT p.name AS col1,p.birthdate AS col2 FROM general.Person p WHERE p.name
LIKE 'Fre%' and p.birthdate < DATE "1975-07-20" 

or with where="p.name LIKE 'Fre%' and p.birthdate < DATE '1975-07-20' "
the error is :

org.makumba.OQLParseError: expecting character string, found ''1975-07-20''
in query:
SELECT p.name AS col1,p.birthdate AS col2 FROM general.Person p WHERE p.name
LIKE 'Fre%' and p.birthdate < DATE '1975-07-20' 
	at org.makumba.MakumbaSystem.getOQLAnalyzer(MakumbaSystem.java:308)
	at
org.makumba.view.AttributeParametrizer$1.makeResource(AttributeParametrizer.java:142)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:124)
	at org.makumba.view.AttributeParametrizer.findAST(AttributeParametrizer.java:150)
	at org.makumba.view.AttributeParametrizer.<init>(AttributeParametrizer.java:89)
	at
org.makumba.view.MultipleAttributeParametrizer$1.makeResource(MultipleAttributeParametrizer.java:102)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:124)
	at
org.makumba.view.MultipleAttributeParametrizer.getAttributeParametrizer(MultipleAttributeParametrizer.java:67)
	at
org.makumba.view.MultipleAttributeParametrizer.<init>(MultipleAttributeParametrizer.java:59)
	at org.makumba.view.ComposedQuery.prepare(ComposedQuery.java:349)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:331)
	at org.makumba.view.jsptaglib.QueryExecution.<init>(QueryExecution.java:111)
	at org.makumba.view.jsptaglib.QueryExecution.getFor(QueryExecution.java:99)

it works fine if you wrap the date in a java.util.Date, set it as page
attribute, and use that in the where clause. But that is not possible for
expr=... (bug 574)

Migrated-From: http://trac.makumba.org/ticket/575

**Comment by ghost** [comment]
**Comment by @stefanb on 15 Sep 2003 16:17 UTC**
Cristi sent me a solution for this via SMS.
Fix needed in OQL-translator.g:
http://cvs.makumba.org/classes/org/makumba/db/sql/oql/OQL-translator.g.diff?r1=2.4&r2=2.5&f=h
(change committed to CVS)

Please Fred test and confirm how it works

**Comment by ghost** [comment]
**Comment by @frederikhabils on 15 Sep 2003 23:07 UTC**
[
the dateLiteral now works with this syntax : DATE \"1975-07-20\"
... like in this example: 

<mak:if expr="p.birthdate < DATE \"1975-07-20\" " > : 
   <b>Hey! he's old! </b>
</mak:if>

also good: <mak:if expr='p.birthdate < DATE "1975-07-20" ' >


[2](1])
but the syntax that is promoted (see quote comment 0) does not work:
 (DATE '1975-07-20')

[did not yet test for TIME literals

[4](3]
I)
and I wonder if it was a conscious choice to have no change to line 
  timestampLiteral  { ((OQLAST)#literal).makumbaType="date";}
... in
http://cvs.makumba.org/cgi-bin/cvsweb.cgi/makumba/classes/org/makumba/db/sql/oql/OQL-translator.g.diff?r1=2.4&r2=2.5&f=h

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 16 Sep 2003 13:25 UTC**
in reply to comment 2

[[3](2],)
there seems to be an inconsistency somewhere. the original OQL grammar that i
got from ODMG (still in CVS as OQL.G) defines dateLiteral as "date"
StringLiteral not "date" CharLiteral. i guess (didn't try) that simply using
CharLiteral will do. or supporting both

[4]
should actually be 
makumbaType="timestamp";

and it is so now in CVS

**Comment by ghost** [comment]
**Comment by @frederikhabils on 16 Sep 2003 13:53 UTC**
Re: [2] comment 2, comment 3: the odd thing is that stuff like this works (if 
memory serves):

  where="p.name LIKE 'Fre%' and p.surname <> \"Habils\" " >

that is: I can surround the stringLiteral in this case, either with ' or " 
but the stringLiteral on DATE _must_ be quoted with "

it's of minor importance to me, but this type of inconsistency in syntax will 
annoy users who forget about the limitations with bizarre error mesgs in return.

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 14 Jan 2009 20:48 UTC**
is this still valid with MQL?

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 15 Jan 2009 00:03 UTC**
(In reply to comment #5)
> is this still valid with MQL?

none of 
> select (DATE '1975-07-20')
> select DATE '1975-07-20'
> select DATE "1975-07-20"
> select DATE \"1975-07-20\"
> select DATE \'1975-07-20\'

work in MQL, with exceptions like
org.makumba.commons.RuntimeWrappedException: org.makumba.OQLParseError: line 1:13: unexpected char: '"' at org.makumba.commons.ProducerReturner.getRes(NameValue.java:80) at org.makumba.commons.NameValue.getResource(NameValue.java:53) at org.makumba.commons.NamedResources.getResource(NamedResources.java:237) at org.makumba.providers.query.mql.MqlQueryAnalysisProvider.getRawQueryAnalysis(MqlQueryAnalysisProvider.java:22) at org.makumba.providers.QueryAnalysisProvider.getQueryAnalysis(QueryAnalysisProvider.java:39) at org.makumba.db.makumba.sql.Query.(Query.java:84) 

the obvious workaround is to solve this with an attribute, but that is indeed a bit cumbersome, and I guess having the date constant in the query might be more performant.

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 20 Mar 2013 13:54 UTC**
 str_to_date('2011-01-01', '%Y-%m-%d') now works

it's not precisely what is asked for (as that would be a grammar change) but does the job
