### ISSUE TITLE
"can't select a set" not properly reported

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#29]
**Reported by @cristianbogdan on 20 Oct 2002 20:00 UTC**
Vector vv= db.executeQuery("SELECT act.season.deadlines FROM
best.johnny.Activity act WHERE act=$1", act);

java.lang.ClassCastException: org.makumba.abstr.noHandler
        at org.makumba.db.sql.oql.QueryAST.getFieldName(QueryAST.java:482)
        at org.makumba.db.sql.oql.IdAST.writeInSQLQuery(IdAST.java:20)

somehow at this point makumba should tell you that you shouldn't do such a thing
(select a set). so this is a bug. would be cool if you could write it down in
makumba/doc/makumba.oql.todo.txt. include the first 4-5 lines of the
ClassCastException stacktrace

Migrated-From: http://trac.makumba.org/ticket/33

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 2 Jun 2003 01:20 UTC**
fixed in org.makumba.db.sql.oql.QueryAST revision 2.0.4.1, line 172
