### ISSUE TITLE
$attrib='blabla' throws NPE if 'attrib' is not defined, instead of AttributeNotFoundException

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#293]
**Reported by @cristianbogdan on 22 Sep 2003 15:46 UTC**
<mak:list ...>
<mak:if test="$a='dfgfd'" >

will throw a NPE if a is not defined. an AttributeNotFoundException should be
thrown instead

(and there should be a way to define default values for attributes)

Migrated-From: http://trac.makumba.org/ticket/588

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 22 Sep 2003 15:53 UTC**
the NPE is this

java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:389)
	at
org.makumba.view.MultipleAttributeParametrizer.rewriteAttributes(MultipleAttributeParametrizer.java:165)
	at
org.makumba.view.MultipleAttributeParametrizer$1.makeResource(MultipleAttributeParametrizer.java:102)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:124)
	at
org.makumba.view.MultipleAttributeParametrizer.getAttributeParametrizer(MultipleAttributeParametrizer.java:67)
	at
org.makumba.view.MultipleAttributeParametrizer.<init>(MultipleAttributeParametrizer.java:59)
	at org.makumba.view.ComposedQuery.prepare(ComposedQuery.java:360)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:342)
	at org.makumba.view.jsptaglib.QueryExecution.<init>(QueryExecution.java:111)
	at org.makumba.view.jsptaglib.QueryExecution.getFor(QueryExecution.java:99)
	at org.makumba.view.jsptaglib.QueryTag.doMakumbaStartTag(QueryTag.java:106)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:171)
	at
org.apache.jsp.listMaps_0002dcristi$jsp._jspService(listMaps_0002dcristi$jsp.java:135)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 8 Aug 2008 09:03 UTC**
(In reply to comment #0)
> <mak:list ...>
> <mak:if test="$a='dfgfd'" >
> 
> will throw a NPE if a is not defined. an AttributeNotFoundException should be
> thrown instead


Currently, Makumba throws this;

Makumba programmer error
[..]
The argument 'a' should not be null

This might be a sufficient solution, and the bug could be closed.

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 19 Oct 2008 22:21 UTC**
(In reply to comment #2)
> Currently, Makumba throws this;
> 
> Makumba programmer error
> [..]
> The argument 'a' should not be null
> 
> This might be a sufficient solution, and the bug could be closed.


i made a small page in the mak-devel enviroment showing this, and i close the bug; feel free to re-open if you think the issue is not well enough solved.
