### ISSUE TITLE
$a='blabla' comparison problems

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#294]
**Reported by @cristianbogdan on 22 Sep 2003 15:54 UTC**
<mak:if test="$a='abcd'" >

if $a is defined, it will fail with some OQL error

'abcd'=$a works...

here is the error

java.lang.NullPointerException
	at org.makumba.db.sql.oql.QueryAST.writeDistinct(QueryAST.java:459)
	at org.makumba.db.sql.oql.QueryAST.writeInSQLQuery(QueryAST.java:571)
	at org.makumba.db.sql.Query.<init>(Query.java:57)
	at org.makumba.db.sql.Query.<init>(Query.java:51)
	at org.makumba.db.sql.Database.prepareQueryImpl(Database.java:188)
	at org.makumba.db.DBConnection$1.makeResource(DBConnection.java:46)
	at org.makumba.util.NamedResourceFactory.makeResource(NamedResourceFactory.java:61)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:124)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:180)
	at org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:44)
	at org.makumba.view.AttributeParametrizer.execute(AttributeParametrizer.java:174)
	at
org.makumba.view.MultipleAttributeParametrizer.execute(MultipleAttributeParametrizer.java:47)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:343)
	at org.makumba.view.jsptaglib.QueryExecution.<init>(QueryExecution.java:111)
	at org.makumba.view.jsptaglib.QueryExecution.getFor(QueryExecution.java:99)
	at org.makumba.view.jsptaglib.QueryTag.doMakumbaStartTag(QueryTag.java:106)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:171)
	at
org.apache.jsp.listMaps_0002dcristi$jsp._jspService(listMaps_0002dcristi$jsp.java:135)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

Migrated-From: http://trac.makumba.org/ticket/589

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 14 Jan 2009 21:03 UTC**
works with MQL
