### ISSUE TITLE
Server connection failure during transaction

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#312]
**Reported by @stefanb on 15 Oct 2003 06:19 UTC**
After installing bundle to Tina's winXP laptop last night, both 0.5.9.15
(latest) and 0.5.9.10 (in production) were throwing previousy unseen (by me)
exception when trying to connect to karambasmall running on the bundle's mysql:

java.sql.SQLException: Server connection failure during transaction. 
Attemtped reconnect 3 times. Giving up.
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:1674)
	at com.mysql.jdbc.Connection.<init>(Connection.java:486)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:326)
	at java.sql.DriverManager.getConnection(DriverManager.java:512)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
	at org.makumba.db.sql.SQLDBConnection.makeConnection(SQLDBConnection.java:46)
	at org.makumba.db.sql.SQLDBConnection.<init>(SQLDBConnection.java:41)
	at org.makumba.db.sql.Database.makeDBConnection(Database.java:53)
	at org.makumba.db.Database$3.create(Database.java:56)
	at org.makumba.util.ResourcePool.createAndCount(ResourcePool.java:42)
	at org.makumba.util.ResourcePool.init(ResourcePool.java:52)
	at org.makumba.db.Database.initConnections(Database.java:65)
	at org.makumba.db.sql.Database.<init>(Database.java:114)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:274)
	at org.makumba.db.Database$1.makeResource(Database.java:143)
	at org.makumba.util.NamedResourceFactory.makeResource(NamedResourceFactory.java:61)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:66)
	at org.makumba.util.NameValue.getResource(NameValue.java:52)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:124)
	at org.makumba.db.Database.getDatabase(Database.java:241)
	at org.makumba.MakumbaSystem.getConnectionTo(MakumbaSystem.java:66)
	at org.makumba.controller.Logic.doInit(Logic.java:250)
...
Makumba developer support, version: 0.5.9.10
----------
Anyone seen this behaviour before? Ideas about solution?
Command line mysql client could connect to the db normally.

Migrated-From: http://trac.makumba.org/ticket/612

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 15 Oct 2003 08:19 UTC**
i noticed that "3 times, giving up" is shown if
- the server is down (not sure about this)
- there are not enough rights to connect to it

**Comment by ghost** [comment]
**Comment by farry@best.eu.org on 15 Oct 2003 08:36 UTC**
I got this '3 times connecting' error also, but only when
- another mysql was already running (i have different mysqld's on my laptop)
- localhost_mysql_<dbname> mentions sql.user=root, as I don't have that user
defined in my mysql setup. 
(in both cases the error is different. eg in the second case the error
is:java.sql.SQLException: Server connection failure during transaction. 
Attemtped reconnect 3 times. Giving up.
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:1639)
	at com.mysql.jdbc.Connection.<init>(Connection.java:485)
	at com.mysql.jdbc.Driver.connect(Driver.java:341)
	at java.sql.DriverManager.getConnection(DriverManager.java:512)
	at java.sql.DriverManager.getConnection(DriverManager.java:140)
...)

But the error you show mentions
at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:326)
                  ^^^^^^^^^^^^^^^^^^^^

while this should be the mysqldriver that gets loaded, right? Is this related to
mysql-connector? Perhaps copying the mysql-connector from /util-java/lib to
/util-java/tomcat-4.1/commons/lib/ failed? (done with target copyLibsToTomcat
when ant tomcat'ing) 

No clue at all if this is related or not...

**Comment by ghost** [comment]
**Comment by @stefanb on 22 Oct 2003 07:22 UTC**
Yesterday on the log i noticed a more detailing error, mentionig SQLstate 08001
quick search on mysql website turned out
http://www.mysql.com/documentation/connector-j/index.html#id2802490

So i just did a simple SQL thingie:
  grant all privileges on *.* to tina@localhost;
and configured karamba to connect to mysql as user tina.

maybe the error shown on the webpage should include more detailed SQLstate and
vendor code in case it is an SQLException.

**Comment by ghost** [comment]
**Comment by @stefanb on 22 Oct 2003 08:41 UTC**
For easier problem solving SQL errors now show state & code in the error page as:

SQL Internal Makumba error

The problem is related to SQL:
	 SQLstate: 08001
	ErrorCode: 0
	  Message: Server connection failure during transaction. 
Attemtped reconnect 3 times. Giving up.

Refer to your SQL server's documentation for error explanation.
Please check the configuration of your webapp and SQL server.
Please report to the developers.

java.sql.SQLException: Server connection failure during transaction. 
Attemtped reconnect 3 times. Giving up.
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:1610)
	at com.mysql.jdbc.Connection.<init>(Connection.java:474)
...
-------
(reproduced by changing sql.user to a nonexisting one)
-------
Checking in classes/org/makumba/devel/TagExceptionServlet.java;
/usr/local/cvsroot/makumba/classes/org/makumba/devel/TagExceptionServlet.java,v
 <--  TagExceptionServlet.java
new revision: 2.1; previous revision: 2.0
done
http://cvs.makumba.org/classes/org/makumba/devel/TagExceptionServlet.java

**Comment by ghost** [comment]
**Comment by stefanba on 15 Nov 2010 16:57 UTC**
(In [569]) SQL errors show state & code in the error page (see bug 612)
