### ISSUE TITLE
MDD names in Catalog are limited in length

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#331]
**Reported by @stefanb on 18 Nov 2003 13:53 UTC**
Test suite complains:
    [2003.11.18 14:28:55 org.makumba.db.sql.Database <init>
    [junit](junit]) INFO: Makumba devel-20031118142832 INIT: jdbc:mysql://localhost/makumba
    [2003.11.18 14:28:57 org.makumba.db.sql.Database <init>
    [junit](junit]) INFO:       connected to MySQL version: 4.1.0-alpha-max-nt
    [    using MySQL-AB JDBC Driver version: 3.0.7-stable ( $Date:
2003/04/08 18:29:14 $, $Revision: 1.27.2.16 $)
    [junit](junit])     using DBSV 0
...
    [4) testQueryValidMdds(test.table)junit.framework.AssertionFailedError:
    [junit](junit])   Tested 10 valid MDDs, of which 1 cant be used for DB queries:[   [junit](
)  .1) Error querying valid MDD
<ExtremelyLongMddName123456789012345678901234567890123456789012345678901234567
89012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890>:
    [     org.makumba.InvalidValueException: Errors while trying to
assign arguments to query:
    [junit](junit]) SELECT c.Catalog_ FROM org_makumba_db_catalog_ c WHERE ( c.name_ = ?)
    [argument: $1; exception:
    [junit](junit]) org.makumba.InvalidValueException: Invalid value for
temp5938662#param0: String too long for char[field. M
aximum width: 200 given width 205.
    [junit](])     Given value
<test.validMdds.ExtremelyLongMddName12345678901234567890123456789012345678901234567890123456
789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890>]
    [    at test.table.testQueryValidMdds(table.java:96)
    [junit](junit])     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [junit](junit])     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [    at test.all.main(all.java:37)
----
IMO this error is rightfully raised, because in org.makumba.db.Catalog (mdd) the
field "name" has the length limit set to 200 characters. I didn't notice this
before, because i raised this field's length limit in my workplace on tequila to
255 preemptively.

possible solutions: 
a) "char[200](junit])" -> "text" to have it unlimited length, probably with 
   some performance penalties
b) "char[-> "char[255](200]")" to slightly increase the boundary (probably 
   enough for all realistic cases anyway)

Migrated-From: http://trac.makumba.org/ticket/639

**Comment by ghost** [comment]
**Comment by @stefanb on 18 Nov 2003 16:05 UTC**
just want to stress that both a) and b) can simply be achieved by just changing
the field definition in Catalog.mdd (i tested it).

feel tha power! :)

**Comment by ghost** [comment]
**Comment by @stefanb on 4 Feb 2004 15:38 UTC**
Catalog entries are now keeping the abstract type name in text form instead of
char[200], which makes mdd names length unlimited (in theory).

Performance penalty should be only that text fields are not indexed.

Checking in classes/org/makumba/db/Catalog.mdd;
/usr/local/cvsroot/makumba/classes/org/makumba/db/Catalog.mdd,v  <--  Catalog.mdd
new revision: 2.2; previous revision: 2.1
done

**Comment by ghost** [comment]
**Comment by @stefanb on 6 Feb 2004 17:00 UTC**
Trying running karamba with this, got:
INFO: localhost_mysql_TESTkaramba: checking org.makumba.db.Catalog as
org_makumba_db_Catalog_
Feb 6, 2004 5:45:21 PM org.makumba.db.sql.RecordManager alter
INFO: localhost_mysql_TESTkaramba: ALTER TABLE org_makumba_db_Catalog_ MODIFY
name_ LONGBLOB
Feb 6, 2004 5:45:21 PM org.makumba.db.sql.RecordManager alter
INFO: SUCCESS: DROP INDEX name_ ON org_makumba_db_Catalog_
java.sql.SQLException: Invalid argument value,  message from server: "BLOB
column 'name_' can't be used in key specification with the used table type"


reverted to char, but now is: char[is longer than before (char[200](255]
which))

Checking in db/Catalog.mdd;
/usr/local/cvsroot/makumba/classes/org/makumba/db/Catalog.mdd,v  <--  Catalog.mdd
new revision: 2.3; previous revision: 2.2
done

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 11:02 UTC**

**Comment by ghost** [comment]
**Comment by stefanba on 15 Nov 2010 16:58 UTC**
(In [632]) reverted to char, see bug 639

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 20 Mar 2013 11:18 UTC**
char[255] is there now and is good enough
