### ISSUE TITLE
Communication link failure (SQLState 08S01, errorcode 0)

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#339]
**Reported by @cristianbogdan on 2 Dec 2003 16:50 UTC**
i have two makumba servers connected to the same mysql 4.0.13 over connector/J
3.0.6-stable

the one working with makumba-0.5.9.14 has no problems even if it's not accessed
for days. the one working with the latest makumba checkout and left alone for a
while shows 08S01 (error code 0) exceptions on the log and in the page. i will
paste a stacktrace here when i can reproduce. i remember it was at
java.sql.Connection.commit()

i should say that i had problems with this system before, due to lack of
db.close(). it can be something specific to my system, but can equally be
something due to the latest changes to org.makumba.db.sql. for now, i'll mark
this as platform-independent as it really seems to be either in makumba, or in
the application. 

the error occurs on all connections. the rapid succession is probably due to the
system having frames which provoke makumba accesses at approximately the same time

Dec 2, 2003 4:16:44 PM org.makumba.db.sql.Database logException
WARNING: connection 8 Communication link failure: java.net.SocketException SQL
state: 08S01 error code :0

Dec 2, 2003 4:16:44 PM org.makumba.db.sql.Database logException
WARNING: connection 9 Communication link failure: java.net.SocketException SQL
state: 08S01 error code :0

Dec 2, 2003 4:16:44 PM org.makumba.db.sql.Database logException
WARNING: connection 7 Communication link failure: java.net.SocketException SQL
state: 08S01 error code :0

Dec 2, 2003 4:16:45 PM org.makumba.db.sql.Database logException
WARNING: connection 7 Communication link failure: java.net.SocketException SQL
state: 08S01 error code :0

Dec 2, 2003 4:16:45 PM org.makumba.db.sql.Database logException
WARNING: connection 9 Communication link failure: java.net.SocketException SQL
state: 08S01 error code :0

Dec 2, 2003 4:16:45 PM org.makumba.db.sql.Database logException
WARNING: connection 8 Communication link failure: java.net.SocketException SQL
state: 08S01 error code :0

Migrated-From: http://trac.makumba.org/ticket/655

**Comment by ghost** [comment]
**Comment by farry@best.eu.org on 2 Dec 2003 17:03 UTC**
these errors are similar to the errors I found the previous time private area
was down...

**Comment by ghost** [comment]
**Comment by @frederikhabils on 2 Dec 2003 18:58 UTC**
> the one working with the latest makumba checkout

you mean : the last release (.16), or the HEAD of development? I assume you mean
HEAD. There's plenty of DB level changes between those 2.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 3 Dec 2003 09:23 UTC**
this error refers to the HEAD of makumba

if it wouldn't be for comment 1, i would hypothesize that there is a problem
reconnecting when InnoDb tables are involved. even so, the problem may exist
with all of mysql and may be more serious with InnoDb.

presently we rely on the JDBC driver to reconnect, maybe that's not enough?
should not be hard to add some reconnection code, i just wonder what should be
the condition for that? 08S01?

i reporoduced the error this morning. here is the stacktrace. please compare
with what you saw in production...

SQL Internal Makumba error

The problem is related to SQL:
	 SQLstate: 08S01
	ErrorCode: 0
	  Message: Communication link failure: java.net.SocketException

Refer to your SQL server's documentation for error explanation.
Please check the configuration of your webapp and SQL server.
Please report to the developers.

java.sql.SQLException: Communication link failure: java.net.SocketException
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:882)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:945)
	at com.mysql.jdbc.MysqlIO.sqlQuery(MysqlIO.java:917)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:1806)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:1752)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:1733)
	at com.mysql.jdbc.Connection.commit(Connection.java:1074)
	at org.makumba.db.sql.SQLDBConnection.commit(SQLDBConnection.java:56)
	at org.makumba.db.DBConnectionWrapper.commit(DBConnectionWrapper.java:65)
	at org.makumba.db.DBConnectionWrapper.close(DBConnectionWrapper.java:71)
	at org.makumba.controller.Logic.doInit(Logic.java:307)
	at org.makumba.controller.http.RequestAttributes.<init>(RequestAttributes.java:66)
	at org.makumba.controller.http.RequestAttributes.<init>(RequestAttributes.java:54)
	at
org.makumba.controller.http.RequestAttributes.getAttributes(RequestAttributes.java:48)
	at org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:48)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:213)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:193)
	at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:260)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.catalina.core.StandardContext.invoke(StandardContext.java:2415)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:180)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:643)
	at
org.apache.catalina.valves.ErrorDispatcherValve.invoke(ErrorDispatcherValve.java:170)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:641)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:172)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:641)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:509)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:641)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:174)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.coyote.tomcat4.CoyoteAdapter.service(CoyoteAdapter.java:223)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:432)
	at
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:386)
	at org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:534)
	at
org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:530)
	at java.lang.Thread.run(Thread.java:536)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Dec 2003 14:44 UTC**
i put the version to 0.5.10 as this code will either be released as 0.5.9.10
(test release as 0.5.7 was) or as 0.6

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Dec 2003 14:45 UTC**
sorry, in comment 4 i meant 0.5.10 not 0.5.9.10

**Comment by ghost** [comment]
**Comment by @stefanb on 8 Dec 2003 09:19 UTC**
The only suggestion i could found by googling was to add the autoReconnect=true,
which makumba was suppose to use in case of MySQL.

It is done so in 
http://cvs.makumba.org/classes/org/makumba/db/sql/Database.java
which should probably be done somewhere in
http://cvs.makumba.org/classes/org/makumba/db/sql/mysql/
as it is also suggested by the comment.

Probably karamba is not showing a problem with this as it is regularly used
(www, private...), but would at least be shown in parade if this was the case
(or is it enough that a scheduler tries to send some statistics from aplications
in johnny every night, probably accessing the DB)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 8 Dec 2003 11:36 UTC**
the system that uses makumba (some stable version) without having this problem
is a non-BEST system with no periodic run kind of tricks. so probably "often
accesses" is not the cause

it seems that between the HEAD and the stable version of karamba there is
something that provokes this. can be transactions, can be innodb, can be both

can we convert some karamba (e.g. a parade row) to a makumba HEAD and an innodb
database to test this hypothesis?

**Comment by ghost** [comment]
**Comment by @stefanb on 8 Dec 2003 12:24 UTC**
stefan-m can be used for that.
It is using tequila_mysql_TESTkaramba, which is already innodb.
I updated stefan-m to current HEAD and did getLocalMakumba in stefan-k, so that
it now contains Makumba devel-20031208131202.

cleaned, compiled and installed the context.
Available at
https://parade.best.eu.org/stefan-k/
now let's _wait_ and see.

**Comment by ghost** [comment]
**Comment by priit@best.eu.org on 24 Dec 2003 07:36 UTC**
Some background from today's MySQL monthly newsletter (actually just confirms
what you guys have said already - and the link at the end doesn't help much either):

Correcting Java Disconnect  Errors

    I have a servlet/application that works fine for a
    day, and then stops working overnight? What can I
    do? 
    
    MySQL closes connections after 8 hours of
    inactivity. You either need to use a connection
    pool that handles stale connections or use the
    "autoReconnect" parameter (see "Developing
    Applications with MySQL Connector/J").
    
    Also, you should be catching SQLExceptions in your
    application and dealing with them, rather than
    propagating them all the way until your
    application exits. This is just good programming
    practice. MySQL Connector/J will set the SQLState
    to "08S01" when it encounters network-connectivity
    issues during the processing of a query. Your
    application code should then attempt to re-connect
    to MySQL at this point.
    
    Other relevant information can be found in the
    MySQL documentation at
    http://www.mysql.com/documentation/connector-j/index.html#id2802490

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 16 Jan 2004 23:22 UTC**
comment 8:
> cleaned, compiled and installed the context.
> Available at
> https://parade.best.eu.org/stefan-k/
> now let's _wait_ and see.

it seems we've waited too much, i went into parade (which worked ok) then tried
to access stefan-k and tallinn went to load average 3

i restarted parade, re-installed stefan-k, works. we wait again :)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 18 Jan 2004 20:22 UTC**
tested stefan-k just now, no error... and it was only me using it in the past 32h

anyway, as suggested in comment 9, i think the best is for the makumba
connection pool to "handle stale connections". we could do this by sending a
COMMIT command on each connection that was unused in the past 7 hours or so.

the other alternative suggested (catch the error, check if it's 08S01, etc) is
more clumsy, because the command executed needs to be repeated. if the command
is in the middle of a transaction, there's no hope... better prevent than cure.

i think one way of handling stale connections is to keep the date of last use
for each resource in org.makumba.util.ResourcePool, then add a method:

public Object getOneUnused(long milliseconds)

which would return one of the unused resources (if any) in the last
"miliseconds", or null if there is none to be left unused all that time.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 20 Jan 2004 01:34 UTC**
it seems that my non-best application is the only reliable way to reproduce
this. stefan-k works...

with the latest connector/J (3.0.10), and latest makumba HEAD, the error code
reported by my app is 08003 (Connection does not exist). it seems that we really
have to do with a timeout disconnection error.

about the solution based on the daemon thread which i suggested in comment 11:
the thread should be stopped (interrupted from sleeping and terminated) whenever
the webapp is destroyed (i.e. connections are closed to be re-created in another
classloader). this can be done by a makumba context listener, like the one that
exists already to free up caches.

i guess i will be the one to fix this since i'm the only one who can test it...

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 24 Jan 2004 23:47 UTC**
this is fixed and tested in my non-best site. probably some mysql configuration
could have solved it but this is more db-independent

this was an interesting problem of threads: the thread that loooks periodically
at the pool to check for stale connections should not keep a reference to the
pool, otherwise it will prevent the pool from being garbage collected when e.g.
the webapp is reloaded (the thread is always referenced by the JVM so the only
way for it to be garbage collected is to terminate). in turn, if the pool is not
garbage collected/finalized, there's no way to find out when to terminate the
thread. so a weak reference from the thread to th pool was needed.

a very pleasant hack, after such a long break :)
