### ISSUE TITLE
delete API call generates broken SQL

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#351]
**Reported by @stefanb on 5 Feb 2004 15:46 UTC**
API call to delete all records of some type
 db.delete("test.validMdds.Int i", "5=5",null);
results in
    [1) testIntAggregation(test.table)
    [junit](junit]) in db command delete on type: <test.validMdds.Int i>  where: <5=5>
    [ generated SQL: DELETE FROM test_valdMdds_Int_  WHERE ( 5 = 5)
    [junit](junit]) java.sql.SQLException: General error,  message from server: "Table
'makumba.test_valdMdds_Int_' doesn't exist"
    [    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1876)
    [junit](junit])     at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1098)
    [    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1192)
    [junit](junit])     at com.mysql.jdbc.Connection.execSQL(Connection.java:2051)
    [    at
com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1680)
    [junit](junit])     at
com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1527)
    [    at org.makumba.db.sql.SQLUpdate.execute(SQLUpdate.java:137)
    [junit](junit])     at org.makumba.db.DBConnection.executeUpdate(DBConnection.java:193)
    [    at org.makumba.db.DBConnection.delete(DBConnection.java:302)
    [junit](junit])     at
org.makumba.db.DBConnectionWrapper.delete(DBConnectionWrapper.java:62)
    [junit]     at test.table.testIntAggregation(table.java:445)

Note that "i" is missing in ...valdMdds...
DELETE FROM test_valdMdds_Int_  WHERE ( 5 = 5)

if i change the label 
 db.delete("test.validMdds.Int a", "5=5",null);
"a" becomes missing (...vlidMdds...)

 db.delete("test.validMdds.Real r", "r=r",null);
works just fine, probably because there is no "r" to mess up

It also works if i change the label to a unique pattern
 db.delete("test.validMdds.Int iii", "5=5",null);

Migrated-From: http://trac.makumba.org/ticket/673

**Comment by ghost** [comment]
**Comment by @stefanb on 5 Feb 2004 17:04 UTC**
A more illustrative example:
    [1) testDelete(test.table)
    [junit](junit]) in db command delete on type: <test.validMdds.CharWithLength t> 
where: <5=5>
    [ generated SQL: DELETE FROM es_validMdds_CharWihLengh_  WHERE ( 5 = 5)
    [junit](junit]) java.sql.SQLException: General error,  message from server: "Table
'makumba.es_validMdds_CharWihLengh_' doesn't exist"

This is now in the test suite: test.table#testDelete()

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 5 Feb 2004 17:36 UTC**
yeh, there is a String operation that removes the label name from the final SQL
so it will have no labels, and that removes also from other parts of the
statement...

i remember that mysql 4 supports labelled delete but for some reason there were
problems in using it on makumba multiple deletes

one fixing this should be pretty easy, just remove separate words, not parts of
words

**Comment by ghost** [comment]
**Comment by @stefanb on 6 Feb 2004 08:51 UTC**
ok, so this parameter to delete is not actually an OQL, right?
i mean, it is impossible to write:
 db.delete("general.Person e, e.address a", "5=5",null);
to remove all addresses.

One should write
 db.delete("general.Person->address x", "x.street LIKE '% 55'",null);
instead.

should we make it OQL and let OQL parser take care of handling the labels properly?

With OQL support, it would be even possible to 
 db.delete("general.Person.address x", "x.country.name LIKE '%epublic%'",null);

or even:
 db.delete(String oql, Object[] args);

Which makes me wonder if it is already now possible to do
 db.executeQuery("DELETE FROM general.Person.address a WHERE a.country.name LIKE
'%epublic%', null)
is it/should it work?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 6 Feb 2004 11:26 UTC**
> ok, so this parameter to delete is not actually an OQL, right?

i don't know what you mean by "is not an OQL". 

basically the implementation 
1) puts the FROM and WHERE arguments of the  delete() method together in an OQL
query, 
2) parses that OQL query, 
3) makes sure there is only one table involved and remembers its label L
4) breaks the translated SQL SELECT using FROM and WHERE as markers and forms
the DELETE statement
5) removes all the instances of L from the generated SQL

> i mean, it is impossible to write:
>  db.delete("general.Person e, e.address a", "5=5",null);
> to remove all addresses.

shouldn't be due to step (3) above


> should we make it OQL and let OQL parser take care of handling the labels
properly?

i'm nt sure what you mean by that, i think it does so already, or?

> With OQL support, it would be even possible to 
>  db.delete("general.Person.address x", "x.country.name LIKE '%epublic%'",null);

yep, at the SQL level, that's multitable DELETE

as i said, i think mysql supports multitable/laballed deletes, however, i don't
know how standard SQL they are, one needs to check.

also, in the other delete(pointer) operation, makumba also deletes all the
subsets (e.g. addresses above) and subrecords (e.g. content of g.a.Doc) of the
deleted records. it could be possible to generate the respective multitable
deletes to delete the subsets/records automatically too, but a bit of analysis
is needed.

there might be a bugzilla entry about multitable delete already, or we should
have one. for this bug, the problem at hand should be easier to solve.

**Comment by ghost** [comment]
**Comment by @stefanb on 6 Feb 2004 14:34 UTC**
Checking in classes/test/table.java;
/usr/local/cvsroot/makumba/classes/test/table.java,v  <--  table.java
new revision: 2.5; previous revision: 2.4
done
Checking in classes/org/makumba/db/sql/SQLUpdate.java;
/usr/local/cvsroot/makumba/classes/org/makumba/db/sql/SQLUpdate.java,v  <-- 
SQLUpdate.java
new revision: 2.2; previous revision: 2.1
done

Current related tests are passing, but a review could be good.

**Comment by ghost** [comment]
**Comment by @stefanb on 6 Feb 2004 14:54 UTC**
Basically, what i did was to break down the general
 "remove all 'label' and 'label.'"
into more specific:
 "remove all 'label.' from list of SELECTed fields",
 "remove the last ' label' from FROM part",
 "remove all 'label.' from WHERE part"
