### ISSUE TITLE
OQL-related problems in mak:if

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#360]
**Reported by @cristianbogdan on 8 Apr 2004 21:39 UTC**
test="bjac.isGreenApple = 1 AND bjac.isGreenAppleStamped = 1"

results into the SQL error below. it looks like an OQL translation error, though
the AND operator is widely used and had no such problem before. maybe this has
to do with the "translation" of 1?

SQL Internal Makumba error
 
 The problem is related to SQL:
 	 SQLstate: S1000
 	ErrorCode: 1109
 	  Message: General error,  message from server: "Unknown table
 '1ANDbjac' in field list"

	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1626)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:886)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:945)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:1844)
	at
com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1458)
	at org.makumba.db.sql.Query.execute(Query.java:85)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:180)
	at
org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:44)
	at
org.makumba.view.AttributeParametrizer.execute(AttributeParametrizer.java:174)
	at
org.makumba.view.MultipleAttributeParametrizer.execute(MultipleAttributeParametrizer.java:47)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:343)
	at
org.makumba.view.jsptaglib.QueryExecution.<init>(QueryExecution.java:111)
	at
org.makumba.view.jsptaglib.QueryExecution.getFor(QueryExecution.java:99)
	at
org.makumba.view.jsptaglib.QueryTag.doMakumbaStartTag(QueryTag.java:106)
	at
org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:171)

Migrated-From: http://trac.makumba.org/ticket/686

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 8 Apr 2004 21:41 UTC**
Risto, would be grateful if you could make (or quote here) a separate JSP that
proves the problem and is runnable by itself...

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 8 Apr 2004 21:46 UTC**
https://parade.best.eu.org/risto-k/johnny/test.jsp?activity=9zubxtc

also results in a OQL-SQL error in connection with LIKE

https://parade.best.eu.org/risto-k/johnny/test2.jsp?activity=9zubxtc

provides a workaround for the problem reported at comment 0

i have a feeling that the two are instances of the same makumba problem so i
leave them under the same bug for now

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 24 May 2004 16:36 UTC**
it was a more generic OQL problem. 

SELECT a FROM... worked but SELECT a<b AND c>d FROM... did not work (was
translated into  SELECT a<bANDc<d FROM ...). that is, selection of more
complicated expressions failed (even <mak:value expr="a<b AND c>d" />)

now i made makumba add spaces after each lexical token when translating from OQL
to SQL. it already does that for the WHERE part of the query (this is why AND
and LIKE worked in WHERE but not in SELECT, etc)
