### ISSUE TITLE
org.apache.jasper.JasperException: addrecpient tag could not find an

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#374]
**Reported by Vilius on 13 Jun 2004 15:20 UTC**
From: Rudolf Mayer [2004 06 13 on karamba@ subj: 
[Testing](rudolf_mayer@utanet.at]) Johnny LBG

*** ERRORS! (the stack traces can be found in the end of the mail...)

when changing some data (i tested it with the name, location and dates 
of the event, each individually), i get the following exception.
however, the changed data IS saved in the database!!!! also, there seems 
to be no problem with any email address in that form!

Testing Johnny
HTTP Status 500 -
type Exception report
message
description The server encountered an internal error () that prevented 
it from fulfilling this request.

exception
org.apache.jasper.JasperException: addrecpient tag could not find an 
email address. set  the address attribute, or place the address in the 
body of the tag.

Stack:

exception
org.apache.jasper.JasperException: addrecpient tag could not find an 
email address. set  the address attribute, or place the address in the 
body of the tag.
	at 
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:248)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile
(JspServlet.java:289)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at 
org.apache.catalina.core.ApplicationDispatcher.invoke
(ApplicationDispatcher.java:684)
	at 
org.apache.catalina.core.ApplicationDispatcher.doInclude
(ApplicationDispatcher.java:575)
	at 
org.apache.catalina.core.ApplicationDispatcher.include
(ApplicationDispatcher.java:498)
	at 
org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:820)
	at org.apache.jsp.event_jsp._jspService(event_jsp.java:153)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:136)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at 
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:204)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile
(JspServlet.java:289)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:247)
	at 
org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at 
org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:75)
	at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at 
org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)
	at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at 
org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.eu.best.tools.TriggerFilter.doFilter(TriggerFilter.java:58)
	at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at 
org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at 
org.apache.catalina.core.StandardWrapperValve.invoke
(StandardWrapperValve.java:260)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at 
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at 
org.apache.catalina.core.StandardContextValve.invoke
(StandardContextValve.java:191)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at 
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at 
org.apache.catalina.core.StandardContext.invoke(StandardContext.java:2396)
	at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:180)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at 
org.apache.catalina.valves.ErrorDispatcherValve.invoke
(ErrorDispatcherValve.java:170)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at 
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:172)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at 
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:469)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at 
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at 
org.apache.catalina.core.StandardEngineValve.invoke
(StandardEngineValve.java:174)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at 
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.coyote.tomcat4.CoyoteAdapter.service
(CoyoteAdapter.java:223)
	at 
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:405)
	at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnectio
n(Http11Protocol.java:380)
	at 
org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:508)
	at 
org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run
(ThreadPool.java:533)
	at java.lang.Thread.run(Thread.java:534)

root cause

javax.servlet.ServletException: addrecpient tag could not find an email 
address. set  the address attribute, or place the address in the body of 
the tag.
	at 
org.apache.jasper.runtime.PageContextImpl.handlePageException
(PageContextImpl.java:494)
	at 
org.apache.jsp.eventChangeMail_jsp._jspService(eventChangeMail_jsp.java:795)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:136)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at 
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:204)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile
(JspServlet.java:289)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at 
org.apache.catalina.core.ApplicationDispatcher.invoke
(ApplicationDispatcher.java:684)
	at 
org.apache.catalina.core.ApplicationDispatcher.doInclude
(ApplicationDispatcher.java:575)
	at 
org.apache.catalina.core.ApplicationDispatcher.include
(ApplicationDispatcher.java:498)
	at 
org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:820)
	at org.apache.jsp.event_jsp._jspService(event_jsp.java:153)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:136)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at 
org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:204)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile
(JspServlet.java:289)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:247)
	at 
org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at 
org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:75)
	at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at 
org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)
	at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at 
org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at org.eu.best.tools.TriggerFilter.doFilter(TriggerFilter.java:58)
	at 
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter
(ApplicationFilterChain.java:213)
	at 
org.apache.catalina.core.ApplicationFilterChain.doFilter
(ApplicationFilterChain.java:193)
	at 
org.apache.catalina.core.StandardWrapperValve.invoke
(StandardWrapperValve.java:260)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at 
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at 
org.apache.catalina.core.StandardContextValve.invoke
(StandardContextValve.java:191)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at 
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at 
org.apache.catalina.core.StandardContext.invoke(StandardContext.java:2396)
	at 
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:180)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at 
org.apache.catalina.valves.ErrorDispatcherValve.invoke
(ErrorDispatcherValve.java:170)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at 
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:172)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at 
org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:469)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:641)
	at 
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at 
org.apache.catalina.core.StandardEngineValve.invoke
(StandardEngineValve.java:174)
	at 
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNex
t(StandardPipeline.java:643)
	at 
org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.coyote.tomcat4.CoyoteAdapter.service
(CoyoteAdapter.java:223)
	at 
org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:405)
	at 
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnectio
n(Http11Protocol.java:380)
	at 
org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:508)
	at 
org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run
(ThreadPool.java:533)
	at java.lang.Thread.run(Thread.java:534)

Migrated-From: http://trac.makumba.org/ticket/705

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 13 Jun 2004 22:52 UTC**
please provide the URL where this happens (or at least more precise info of what
you wanted to do)

this seems to be a JSP compilation error and most probably has nothing to do
with the makumba version.

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 14 Jun 2004 14:09 UTC**
the bugs occured at

https://parade.best.eu.org/demo-k/johnny/lbg/applying/applicationsToAll.jsp?season=summer04
(the season doesn't matter)

and at 

https://parade.best.eu.org/demo-k/johnny/lbg/announcing/organiser/event.jsp 
(you need to edit and submit the changes to trigger it)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 14 Jun 2004 14:20 UTC**
i actually see a completely different error in the first address provided

org.apache.jasper.JasperException: Unable to compile class for JSP

An error occurred at line: 99 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [Compiling 1 source file
    [javac](javac])
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:272:13:272:15:
Semantic Error: No field named "cnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 99 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [Error: No field named "maxcnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 100 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [javac](javac]
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:273:13:273:18:
Semantic)
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:277:26:277:28:
Semantic Error: No field named "cnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 101 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [Error: No field named "cnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 111 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [javac](javac]
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:281:25:281:27:
Semantic)
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:323:20:323:25:
Semantic Error: No field named "maxcnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 99 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [Error: No field named "cnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 99 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [javac](javac]
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:326:15:326:17:
Semantic)
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:327:15:327:20:
Semantic Error: No field named "maxcnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 99 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [Error: No field named "cnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 99 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [javac](javac]
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:334:11:334:13:
Semantic)
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:335:11:335:16:
Semantic Error: No field named "maxcnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 130 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [Error: No field named "cnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 130 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [javac](javac]
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:354:13:354:15:
Semantic)
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:403:15:403:17:
Semantic Error: No field named "cnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



An error occurred at line: 130 in the jsp file:
/johnny/lbg/applying/applicationsToAll.jsp

Generated servlet error:
    [javac]
/home/projects/parade/server/parade/tomcat/work/Standalone/localhost/demo-k/johnny/lbg/applying/applicationsToAll_jsp.java:410:11:410:13:
Semantic Error: No field named "cnt" was found in type
"org.apache.jsp.applicationsToAll_jsp".



	at
org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:120)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:293)
	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:313)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:324)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:474)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:184)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:289)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:853)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:247)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:193)
	at org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:75)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:213)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:193)
	at org.eu.best.tools.VHostFilter.doFilter(VHostFilter.java:83)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:213)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:193)
	at org.eu.best.tools.TriggerFilter.doFilter(TriggerFilter.java:58)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:213)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:193)
	at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:260)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.catalina.core.StandardContext.invoke(StandardContext.java:2396)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:180)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:643)
	at
org.apache.catalina.valves.ErrorDispatcherValve.invoke(ErrorDispatcherValve.java:170)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:641)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:172)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:641)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:469)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:641)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:174)
	at
org.apache.catalina.core.StandardPipeline$StandardPipelineValveContext.invokeNext(StandardPipeline.java:643)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:480)
	at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:995)
	at org.apache.coyote.tomcat4.CoyoteAdapter.service(CoyoteAdapter.java:223)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:405)
	at
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:380)
	at org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:508)
	at
org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:533)
	at java.lang.Thread.run(Thread.java:534)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 14 Jun 2004 22:58 UTC**
this is indeed a matter of jasper1 - jasper2 difference 

this site works with jasper1 (which is default in karamba installation, see bug 708)
http://tallinn.best.eu.org:28080/johnny/lbg/applying/applicationsToAll.jsp?season=summer04

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 15 Jun 2004 21:53 UTC**
Lode sent more details on how to reproduce (Lode please put those directly in
bugzilla)

it seems that we talked about two different bugs here. one is a jasper
compilation problem, the other is "the email problem". let us keep this bug
entry for "the email problem" only.

> 1. Made dummy season as superuser in johnny(TEST2Karamba): ITC TEST 04
> 2. Logged in as LBG Ghent
> 3. Tried to announce new event in ITC TEST 04
> 
> through page:
> https://parade.best.eu.org/demo-k/johnny/lbg/announcing/organiser/event.jsp
> 
> Error:
> 
> type Exception report
> 
> message
> 
> description The server encountered an internal error () that prevented it
> from fulfilling this request.
> 
> exception
> 
> org.apache.jasper.JasperException: addrecpient tag could not find an email
> address. set  the address attribute, or place the address in the body of
> the tag.
>

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 15 Jun 2004 22:06 UTC**
Comment 3/4
Indeed https://parade.best.eu.org/demo-k/johnny/lbg/applying/applicationsToAll.
jsp?season=summer04 is linked to the use of jasper2 (This is actually treated in 
bugs 703/706 and by mistake on comment 2 poped up in this bug)..
Well it seems that it was noticed already, I haven't been fast enough.. 

On the other hand issue reported in this bug, found at 
/johnny/lbg/announcing/organiser/edit/eventCreate.jsp is apparently not related 
to jasper:

* jasper1 http://tallinn.best.eu.org:
28080/johnny/lbg/announcing/organiser/edit/eventCreate.jsp?season=ITC%20TEST%
20'04 (and press submit) 
AND
* jasper2 http://parade.best.eu.
org/demo-k/johnny/lbg/announcing/organiser/edit/eventCreate.jsp?season=ITC%
20TEST%20'04 (...)

..returns the reported error (funny spelling mistake btw "addrecpient"), leaving 
the only difference to be makumba version.

Gwen @ midair collision, hoping not to say too many things twice

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 15 Jun 2004 22:17 UTC**
ok, i saw the same problem at 
http://tallinn.best.eu.org:28080/johnny/lbg/announcing/organiser/edit/eventCreate.jsp?season=ITC%20TEST%20'04`

(please indicate the first page where you can start reproducing the problem)

upon form submission (event.jsp) johnny wants to send email to somebody to
report on the newly created activity. this fails due to lack of an email address.

if you look at event.jsp

http://tallinn.best.eu.org:28080/johnny/lbg/announcing/organiser/event.jspx#48

it includes eventChangeMail.jsp. that one sets recipient differently in
production and in test.

http://tallinn.best.eu.org:28080/johnny/lbg/announcing/organiser/eventChangeMail.jspx#123

i've no idea why it goes wrong, the recipient is clearly set. 

more investigation is needed
- try to take out the <mt: > stuff and see what are values passed to <mt: >
- test this with makumba 0.5.9 and see how it behaves (maybe the recipient
computation for test environments is wrong after all)

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 15 Jun 2004 22:20 UTC**
Trying to help with some observations:
* Error seems to come actually from (compiled version of?)
http://parade.best.eu.
org/demo-k/johnny/lbg/announcing/organiser/eventChangeMail.jspx

A similar (but working!) page is 
http://parade.best.eu.org/demo-k/email/mailsend.jspx

Just in case it is useful other used way to send mails, from BL, is working as 
well, at least from following page: http://parade.best.eu.
org/demo-k/classes/org.eu.best.privatearea.LbgLbgEditLogic

Gwen @ "midair" again.. stop working on this Cristi ;)

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 15 Jun 2004 22:40 UTC**
Reply comment 7
retested, works with 0.5.9.18 (borrowed Vilius's context for this) with or 
without activity responsible email entered upon activity creation.

Gwen

PS: Just in case https://parade.best.eu.
org/vilius-k/johnny/lbg/announcing/organiser/edit/eventCreate.jsp?
season=SPOCtest05

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 16 Jun 2004 00:01 UTC**
i brought tallinn:28080 to makumba-0.5.9.18 and the error is still there. 

rm -rf tomcat/work
ant stopTomcat getMakumba tomcat

so at this point i am pretty convinced that this is not a makumba 0.5.9->0.5.10
problem. 

in any case, the problem is specific to <mt> (mail-sending) tags, which are used
in a very small number of pages. the only expert in using those is Fred. 

still, i think the problem can be investigated by adding
System.out.println(various expressions) in the eventChangeMail.jsp in the
contexts (and seasons) where this is known to work and not to work respectively

http://tallinn.best.eu.org:28080/johnny/lbg/announcing/organiser/edit/eventCreate.jsp?season=ITC%20TEST%20'04`
https://parade.best.eu.org/vilius-k/johnny/lbg/announcing/organiser/edit/eventCreate.jsp?
season=SPOCtest05
https://parade.best.eu.org/demo-k/johnny/lbg/announcing/organiser/edit/eventCreate.jsp?season=ITC%20TEST%20'04`

then compare the outputs...

i leave tallinn:28080 on 0.5.9 for more testing. to bring it to 0.5.10 do

cd ~cristi/sources/karamba
rm -rf tomcat/work
ant stopTomcat copyLocalMakumba tomcat

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 16 Jun 2004 00:03 UTC**
in comment 10, by "compare the outputs" i mean look in 
tail -f tomcat/logs/server-output.txt
if you use System.out, that's where the output goes

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 16 Jun 2004 00:39 UTC**
fuck. revision 2.3 of eventChangeMail is buggy, but it has the STABLE tag. 

http://cvs.best.eu.org/cgi-bin/cvsweb.cgi/karamba/public_html/johnny/lbg/announcing/organiser/eventChangeMail.jsp

Fred did a fix to the page, related to exactly this problem (bug 645). the page
probably fails even in production since the STABLE tag was not moved to 2.4

vilius-k uses revision 2.4 which works. the other two (tallinn:28080 and demo-k)
use STABLE=> revision 2.3=> fails.

i updated tallinn:28080
cvs update -A public_html/johnny/lbg/announcing/organiser/eventChangeMail.jsp
and now it works.

so i moved the stable tag.
cvs tag -F STABLE public_html/johnny/lbg/announcing/organiser/eventChangeMail.jsp

production will probably be updated (i won't touch production)

i updated demo-k (simply cvs update since it was checked out with -r STABLE).
should work now.

*** This bug has been marked as a duplicate of 645 ***

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 16 Jun 2004 00:42 UTC**
tallinn:28080 is back to karamba 0.5.10.3
as before, it uses jasper1 for comparison
