### ISSUE TITLE
date arithmethic

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#386]
**Reported by @cristianbogdan on 22 Oct 2004 10:36 UTC**
before makumba has functions (bug 26), it should be possible to perform some
date arithmethic. this is needed in an application at IPLab

i will try to implement
date+N
to translate to the SQL
date+INTERVAL N/1000 second

and with mysql 4.1
date+INTERVAL N*1000 microsecond

see "date functions" in the mysql documentation

Migrated-From: http://trac.makumba.org/ticket/748

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 21 Mar 2005 21:34 UTC**
From the documentation at mysql
(http://dev.mysql.com/doc/mysql/en/date-and-time-functions.html), seems actually
not that difficult to translate to SQL. 

one thing i don't understand, though

>to translate to the SQL
>date+INTERVAL N/1000 second
>
>and with mysql 4.1
>date+INTERVAL N*1000 microsecond

imho you would either do the first, OR the second conversion, or do i get
something wrong?

also, i read in MySQL documentation that with these +/- INTERVAL arithmetic, you
can specify the type of the expression - so one could say "+ INTERVAL 1 SECOND".
so as long as you specify what is expected in the expression, there should be no
need to convert.


besides, i was without success trying to find an ANSI SQL specification
somewhere, to check how much MySQL correspondents to this - anyone having a clue?

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 14 Jan 2009 20:52 UTC**
what's the state of this in MQL?

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 14 Jan 2009 23:53 UTC**
(In reply to comment #2)
> what's the state of this in MQL?

> select current_date() + interval 1 day

doesn't pass the parser:

org.makumba.OQLParseError: line 1:34: unexpected token: 1
-->
<--
org.makumba.commons.RuntimeWrappedException: org.makumba.OQLParseError: line 1:34: unexpected token: 1 at org.makumba.commons.ProducerReturner.getRes(NameValue.java:80) at org.makumba.commons.NameValue.getResource(NameValue.java:53) at org.makumba.commons.NamedResources.getResource(NamedResources.java:237) at org.makumba.providers.query.mql.MqlQueryAnalysisProvider.getRawQueryAnalysis(MqlQueryAnalysisProvider.java:22) at org.makumba.providers.QueryAnalysisProvider.getQueryAnalysis(QueryAnalysisProvider.java:39) at org.makumba.db.makumba.sql.Query.(Query.java:84) at org.makumba.db.makumba.sql.Database.prepareQueryImpl(Database.java:301) at org.makumba.db.makumba.Database$3.makeResource(Database.java:239) at org.makumba.commons.NamedResourceFactory.makeResource(NamedResourceFactory.java:81) at org.makumba.commons.ProducerReturner.getRes(NameValue.java:70) at org.makumba.commons.NameValue.getResource(NameValue.java:53) at org.makumba.commons.NamedResources.getResource(NamedResources.java:237) 


neither does
> SELECT DATE_ADD(current_date(), INTERVAL 1 MINUTE)
has the same exception.


does this or something similar work in hibernate?

greetings
rudi

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 27 Jun 2010 19:42 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 27 Jun 2010 19:43 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 19 Mar 2013 02:40 UTC**
this works since Rudi's function work
