### ISSUE TITLE
unique keyword in MDDs

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#4]
**Reported by @cristianbogdan on 6 Oct 2002 23:11 UTC**
UNIQUE keyword to be used in the MDDs for field values and even for groups of fields
could be implemented with SQL UNIQUE indexes

Migrated-From: http://trac.makumba.org/ticket/4

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 19 Oct 2002 01:06 UTC**
one design issue here is: the uniqueness will not be checked manually by the BL
anymore, but at makumba level. then the logic-error-message that the user sees
in case of non-uniqueness should be even stored in the MDD, or could be passed
as an argument to the insert() or update() method that is passible of violating
uniqueness. i think the MDD solution is best

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 24 Oct 2002 08:15 UTC**
The problem of what to show to the user if an insert is made that violates
unicity is quite delicate. An ordinary makumba error page can be too scary for
the user (there are already complaints).

One idea is to have NotUniqueException (NUE) extends LogicException. The message
associated with the NUE would then be read from the MDD where the unique
constraint is defined (see http://bugs.best.eu.org/show_bug.cgi?id=4#c1)

A more general solution is to have a BL method
on_DBError(Throwable t)

which would be called whenever a database error occurs in the insert, delete or
update that follows on_new, on_delete or on_edit. that would give BL the chance
to throw a more user-friednly LogicException instead

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 17 Mar 2003 12:30 UTC**
there are many uniqueness checks in karamba, and i think most of them are less
reliable than the automatic SQL uniqueness check, which is not as expensive as
other SQL checks (e.g. foreign key)

so having this feature will make makumba systems (karamba) much more reliable.
just the UI aspect at comment 1 should be considered.

also, bug 190 is related: once unique constraints exist, submitting the same
add/new form repeatedly will not work anyway. making a form-specific protection
will improve the user experience, but the data as such can be protected by the
unique constraint

**Comment by ghost** [comment]
**Comment by @stefanb on 16 Apr 2003 10:21 UTC**
things get pretty interesting in internal sets... eg:
general.Team (http://private.best.eu.org/dataDefinitions/general.Team) has:
aliases=set
aliases->alias=char[would need to be made unique:
aliases->alias=unique char[50](50]

which)

but should it define alias uniqness 
- in all teams (=no duplicate team aliases within the system) or 
- just in this team (=no duplicates within the team)
...although i am still trying to come up with a real life example for the later 
one :)

**Comment by ghost** [comment]
**Comment by @stefanb on 16 Apr 2003 10:52 UTC**
actually the real life example for second case in comment 4 would be in the 
same general.Team:

members=set 
members->member=unique ptr general.Person 
members->email=unique char[100]

where "unique" should actually mean 'unique or null'
strictly unique would be achieved by specifying "unique not null" in MDD

**Comment by ghost** [comment]
**Comment by @stefanb on 3 Jul 2003 01:27 UTC**
one huge design decision is missing here, 
whether to keep uniqness:

a)troughout the table (can also have support on the DB level)
b)troughout a set (makumba can check values with a query before edit/insert)

hkm...I am in favour of a), but it doesn't mean we can't have b). We could 
specify "set-unique" (or setUnique) in mdd to make it different from the 
ordinary "unique"

For the moment (untill error showing is addressed properly) the error shown can 
be in the same manner as it is in case of entereing "abc" into an int field

**Comment by ghost** [comment]
**Comment by @stefanb on 4 Jul 2003 09:37 UTC**
org.makumba.abstr now supports "unique" MDD keyword, so fields can have it. 
automagic field ptrIndex is specified as unique as well:

stefan@tequila:~/bundle/sources/makumba/classes$ java -cp .:../../../util-
java/lib/antlr.jar org/makumba/abstr/printer/RecordPrinter test.Language
test.Language title: name
Language= fixed notnull unique ptrIndex ; Unique index
TS_modify= notnull dateModify ; Last modification date
TS_create= fixed notnull dateCreate ; Creation date
name= notnull char[unique char[2](10]
isoCode=)

next steps are:
- to add UNIQUE in the DB field specification and
- uniqness checks for insert and update

**Comment by ghost** [comment]
**Comment by @stefanb on 4 Jul 2003 11:18 UTC**
ant test now generates table:
     [java] INFO: CREATE TABLE test_Language_(Language_ INT UNIQUE,TS_modify_ 
TIMESTAMP,TS_create_ TIMESTAMP,name_ VARCHAR(10) BINARY,isoCode_ VARCHAR(2) 
BINARY UNIQUE)
and test passes well.

Generated tables prevent duplicte values (duplicate NULLs are allowed):
mysql> insert into test_Language_ (name_, isoCode_) values ('jiberish','ji');
Query OK, 1 row affected (0.00 sec)
mysql> insert into test_Language_ (name_, isoCode_) values ('jiberish','ji');
ERROR 1062: Duplicate entry 'ji' for key 2

As in bug 222 i still don't know how to make it alter existing tables, which 
would allow testing in karamba, with real data.

Looking also at bug 3

**Comment by ghost** [comment]
**Comment by @frederikhabils on 4 Jul 2003 12:01 UTC**
Stefan, comment 8.

You mean you don't know the SQL statement to execute, or in general where and 
what to change in makumba?

ALTER statement is documented in mysql manual: 6.5.4 ALTER TABLE Syntax


I understood relevant syntax to be:

ALTER TABLE <name> MODIFY <columnname> <dataType and modifiers>;
or
ALTER TABLE <name> CHANGE <columnname> <columnname> <dataType and modifiers>;

(change is meant also for changing column's name, if so desired.)

e.g. 
ALTER TABLE general_Language_ MODIFY iso2 CHAR(2) UNIQUE;

You would have to try this before believing.

**Comment by ghost** [comment]
**Comment by @stefanb on 4 Jul 2003 12:30 UTC**
The ALTER syntax is familiar to me (well, with the SQL docs handy :),

now talking about:
http://cvs.makumba.org/classes/org/makumba/db/sql/FieldManager.java

the problem are the makumba method unmodified() that are calculating whether 
the field definition still matches the one in DB don't recognize such details.

OTOH, i just noticed that "CREATE INDEX ...." is done onStartup() everytime, so 
maybe the idea is to set all the needed UNIQUE params there?

**Comment by ghost** [comment]
**Comment by @stefanb on 4 Jul 2003 16:44 UTC**
noticed that unique can only be used with indexed fields, so we can't use 
unique on text fields, which makes sense, but needs to be changed in abstract 
level ... or we should start index text fields as well (maybe just first few 
kilo characters for better performance?)

**Comment by ghost** [comment]
**Comment by @stefanb on 4 Jul 2003 16:57 UTC**
trying to do ALTERs onStartup()... 

problem is that there are already existing (not unique) indexes, and some of 
them should be changed to unique. 

ALTER TABLE x ADD UNIQUE indexname (fieldname)
may fail because of a duplicate value OR because index with such name already 
exists. 

We can't just create new indexnames as it affects db performance (slows down 
inserts), so we have to DROP indexes sometime when passing to unique, but not 
just blindly everytime onStartup() as it takes time to rebuild them.

I didn't yet find a java/SQL way to find out whether an existing index in DB is 
unique or not.

Another (less cruical, but still) problem is changing back to not-unique if 
design changes demands that.

I managed to persuade my karamba to some unique constraints into the DB and 
when editing LBG Belgrade's unique university to "University College Dublin" i 
got long awaited:

Internal Makumba error 
Please report to the developers.
java.sql.SQLException: Invalid argument value,  message from server: "Duplicate 
entry '184549381' for key 2"
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:1613)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:880)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:939)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:1780)
	at com.mysql.jdbc.PreparedStatement.executeUpdate
(PreparedStatement.java:1601)
	at com.mysql.jdbc.PreparedStatement.executeUpdate
(PreparedStatement.java:1491)
	at org.makumba.db.sql.SQLUpdate.execute(SQLUpdate.java:137)
	at org.makumba.db.DBConnection.executeUpdate(DBConnection.java:189)
	at org.makumba.db.DataHolder.update(DBConnection.java:457)
	at org.makumba.db.DBConnection.update(DBConnection.java:82)
	at org.makumba.db.DBConnectionWrapper.update
(DBConnectionWrapper.java:53)
	at org.makumba.controller.Logic.doEdit(Logic.java:369)
	at org.makumba.controller.http.Responder$3.respondTo(Responder.java:281)
	at org.makumba.controller.http.Responder.response(Responder.java:229)
	at org.makumba.controller.http.ControllerFilter.doFilter
(ControllerFilter.java:56)
...
Message should be improved, but is a start.

**Comment by ghost** [comment]
**Comment by @stefanb on 15 Jul 2003 12:43 UTC**
Unique indexes on individual fields are now created and dropped in the DB as 
needed during table checking.

changes are between revision 2.1 and 2.2 of:
http://cvs.makumba.org/classes/org/makumba/db/sql/FieldManager.java

Made new TESTkaramba from production DB (as i managed to screw-up the indexes 
in previous TESTkaramba earlier)
set some fields to unique ad got for example:
-- Table structure for table 'general_Language_'
CREATE TABLE general_Language_ (
  Language_ int(11) default NULL,
  TS_modify_ timestamp(14) NOT NULL,
  TS_create_ timestamp(14) NOT NULL,
  name_ varchar(40) binary default NULL,
  iso2LetterCode_ char(2) binary default NULL,
  iso3LetterCode_ char(3) binary default NULL,
  UNIQUE KEY general_Language__Language__UNIQ (Language_),
  UNIQUE KEY general_Language__name__UNIQ (name_),
  UNIQUE KEY general_Language__iso2LetterCode__UNIQ (iso2LetterCode_),
  KEY general_Language__TS_modify_ (TS_modify_),
  KEY general_Language__TS_create_ (TS_create_),
  KEY general_Language__iso3LetterCode_ (iso3LetterCode_)
) TYPE=MyISAM;

which looks ok, works as expected (prevents duplicates with ugly error msg as 
shown in comment 12)

Checking best.internal.OfficialDocument#bestNr (with unique attribute in mdd)
reports to log:
WARNING: NOT UNIQUE value of field docNr found in 
best.internal.OfficialDocument, unable to add UNIQUE constraint 
(java.sql.SQLException: Invalid argument value,  message from 
server: "Duplicate entry '20-W-AT-BRD-998' for key 3").
...and keeps the normal index in such cases

I also added some unique field attributes to MDDs in more risky places, like
best.{internal|johnny|minerva}.Student#student and it worked nicely, with no 
duplicates reported.

Adding indexes on big tables requires a lot of free space because server (mysql 
at least) copies whole table to a temporary one in the process.
It took 10 minutes to add unique indexes to general.archive.Document content
and 2 minutes for best.johnny.EventApplication. 

Would resolve the bug as fixed, but then i noticed "and even for groups of 
fields" in comment 0. If, how should this be specified in mdd? 
maybe with line:
!unique=name,surname,birthdate
which would ensure that no two persons have same name, same surname and same 
birthdate (=probably a duplicate account)
is it unclear, conflicting with normal unique field atribute?
should it be:
!uniqueCombination=name+surname+birthdate
or somehow else?

**Comment by ghost** [comment]
**Comment by @frederikhabils on 15 Jul 2003 14:32 UTC**
Hi! that's nice work. 

I had a super quick look at the code, not really enough to understand it. But i 
did notice some error-codes that are specific for MySQL, and I wonder if that 
is appropriate? 

I can only perhaps suggest you to look at the create function in 
http://cvs.makumba.org/classes/org/makumba/db/sql/RecordManager.java

In light of bug 512, I studied that a bit, and noticed that it is using "more 
general" ODBC error codes (SQLSTATE)... which are set for various db engines in 
properties file makumba/classes/org/makumba/db/sql/sqlEngines.properties

**Comment by ghost** [comment]
**Comment by @stefanb on 15 Jul 2003 16:08 UTC**
SQL states are less detailed than error codes as can be observed from:
http://www.mysql.com/doc/en/Error-returns.html

I isolated the MySQL-specific error codes in variables that can be ovverriden 
by other drivers that are exending the basic (=mysql) driver, but more 
importantly try-catch blocks are placed in such way that the actual code/state 
does not matter for proper operation, it may just speed up db operations (by 
deleting one index if other one exists) and provide detailed error message (if 
duplicate is found in supposably unique field)

I just noticed that i only usied 2 error codes that also have different SQL 
states, so transition to SQL states should be easy, also having them specified 
in .poperties file as some are already.

also looking at jdbc api's getIndexInfo()

**Comment by ghost** [comment]
**Comment by @frederikhabils on 16 Jul 2003 08:05 UTC**
about the question comment 13, I like the simplicity of 
  !unique=name,surname,date

... but I think it might leave some room for misinterpretation. Therefore 
suggest for unique groups
  !unique=(name, surname, date)

... we will also have to solve "conflicts" between 
  !unique=(fieldA)
  fieldA=date

... by 
(a) saying that any style of unique declaration defines the field as unique OR
(b) disallowing unique groups of size 1 field?

(b) seems easier to do; (a) might be preferred for consistency and simplicity 
of concept. 

BTW, was comment 11 solved? (avoiding creation of unique indexes for text 
fields, (and by extension:) avoiding text fields to appear in unique 
fieldGroups)

ok, back to office tasks...

**Comment by ghost** [comment]
**Comment by @stefanb on 16 Jul 2003 12:28 UTC**
Re comment 14:
Unfortunately proper SQL states are only returned by MySQL version 4.1 and 
above while BEST is using 4.0 (i guess that jdbc invents the state "S1009" that 
is returned in most cases) This is probably also important for bug 512.

So i did the change to have errorcode specified in .properties which 
FieldManager.manageIndexes uses now.

Text fields are not indexed so they can't even be specified as unique in the 
DB, but user might write 
bla=unique text
in the MDD and expect uniqness - which is not provided. I guess some exception 
should be thrown while parser reads such line.

Not sure what happens with:
bla=unique set...
or even:
bla=not null set...

#moved "unique goups of fields" to a seperate bug 513 to keep things clearer

**Comment by ghost** [comment]
**Comment by @frederikhabils on 16 Jul 2003 15:01 UTC**
Comment 12:
> I didn't yet find a java/SQL way to find out whether an existing index in 
> DB is unique or not.

I guess it is for this reason, that you have created a modified naming 
convention for INDEXes. 
  - tableName_fieldName for normal INDEX
  - tableName_fieldName_UNIQ for unique INDEX

I would expect that there are ways to query the index type... 

But as long as this naming convention is used, we must make sure to employ it 
everywhere... I noticed in 
http://cvs.makumba.org/classes/org/makumba/db/sql/RecordManager.java

... the function: boolean alter(Statement, FieldManager, String)
which drops only the 'regular' INDEX, not the unique one.

This and other code must be searched for and updated. Perhaps separating a 
dropIndex(fieldname) function that centralizes all possible index dropping. 

Or figuring out how to check the type of index, so that all types of index can 
have the same generic name.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 16 Jul 2003 15:05 UTC**
there is a function for getting all sorts of information about the indexes:

http://java.sun.com/j2se/1.4.2/docs/api/java/sql/DatabaseMetaData.html#getIndexI
nfo(java.lang.String, java.lang.String, java.lang.String, boolean, boolean)

**Comment by ghost** [comment]
**Comment by @stefanb on 22 Jul 2003 09:49 UTC**
with comment 12 and comment 13 in mind I dropped the "_UNIQ" index name postfix 
in favour of real index uniqness check, discovered with 
databaseMetaData.getIndexInfo() 

committed revision 2.4 of
http://cvs.makumba.org/classes/org/makumba/db/sql/FieldManager.java

**Comment by ghost** [comment]
**Comment by @stefanb on 22 Jul 2003 10:12 UTC**
There might be a problem if unique field is dropped (eg commented out in the 
MDD) because uniqness would still be required by DB engine during inserts and 
updates because indexes are presently not deleted for extra fields (those not 
defined in mdd).

probably 
http://cvs.makumba.org/classes/org/makumba/db/sql/RecordManager.java
shoulld drop makumba-created unique indexes for unknown fields somewhere 
around "extra field:". 
Maybe manageIndexes() should move there.

probable workaround is to make the field non-unique type before dropping it

writing this down so it won't be forgotten.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 22 Jul 2003 10:55 UTC**
Re: comment 20
nice work! :-)

I spotted an improvement in isIndexOk(SQLDBConnection dbc) that in theory 
should be applied, but will have not so much speed impact here:
- avoid recalculation in the while-loop -> getDBIndexName()
- break out of the while as early as possible, because if part will run 0 or 1 
time only -> if(){ action; break; }


Re: comment 21
I don't think this is a concern: if a unique field is dropped in the MDD - and 
continues to exist in the DB (field + unique index), then makumba will never 
add values to this field, so db will always add the default (NULL).
But surely, it wouldn't hurt to drop indexes for dropped fields, even if the 
field itself is not dropped from DB. 
It might be better to make a new bug for that, and then we have bug 513 + new 
bug to optimise this issue, while the core part of this bug is RESOLVED :-)


What I am slightly more worried for, is the behaviour in case a field needs a 
UNIQUE index, but it can not be made (e.g. non-unique values): current 
behaviour of code is:

1/ indexIsOK = false => drop the non-unique index
2/ try making unique index => fails
3/ make a non-unique index

That's a bit costly effort. 

Have to admit I can't think of way to avoid. It's exceptional situation also, 
which should be solved ASAP by mak:user, so it shouldn't continue to live on 
and create annoyance. Meaning we may accept this 'weakness'.

**Comment by ghost** [comment]
**Comment by @stefanb on 22 Jul 2003 11:38 UTC**
#please, Fred, next time if you make longer commnets about different topics 
#use some ABC/123/btw/ps/***/++ for easier reference :)

for the sake of nice code I improved isIndexOk() as Fred suggested in comment 22

I also hope that several NULL values are considered as unique.

Was also thinking about cases when unique index fails to be  created, but the 
only possible solutions are also costly:

a) 1. try to make a temporary unique index to see if ti is possible
   2. drop non-unique index 
   3. create unique index   \___ or is index renaming 
   4. drop temporary unique /    possible in standard sql?

b) 1. try to detect duplicates with some SELECTs
   2. if none found proceed with current procedure

Agree that this should not be a very common case and app maintainer should 
solve it ASAP anyway, not because startups would take a bit longer, but because 
it represents a poblem in his data (as in bug 514) or his app's MDD design.

btw: error messages are slightly improved, not relying on error return codes 
anymore, but logging any problem in places there should not be. 
ant test surfaced previously unseen (but present) new bug 516

Resolving this one as fixed.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 22 Jul 2003 15:20 UTC**
I hate to reopen after such long and nice work done already, but after 
rereading this thread entirely, I spotted 2 areas of improvement which would 
come to our attention sooner or later:

[insert/update resulting in not-unique-error : UI aspect? (comment 1, 2, 3)
[b](a]) datatypes not supporting 'unique' must give warning if 'unique' is requested
(comment 17)

---
[is a larger issue for which I don't have the energy to get into now
[b](a]) I think it is sufficient to write a warning on the log, and "continue as 
usual". Not too difficult to add this in abstr level?

**Comment by ghost** [comment]
**Comment by @stefanb on 23 Jul 2003 07:53 UTC**
addressing [b] from Fred's comment 24:
I made the abstract level reject unique texts and sets
http://cvs.makumba.org/classes/org/makumba/abstr/?sortby=date#dirlist
should it reject some other stuff also?

http://private.best.eu.org:11888/dataDefinitions/best.helpdesk.Request
demonstrates the errors:
----
24:	body = unique text
	                  ^ text fields can't be declared unique
25:	
26:	status = int {"New"=0, "In progress"=2, "Solved"=1, "Deleted"=3}
27:	
28:	history = unique set
	                    ^ sets can't be declared unique
29:	   history->statusModifiedBy = not null ptr best.helpdesk.Solver
	                                                                ^ no 
such field in subfield definition
----
error on line 29 (and some more afterwards) results from failing to parse line 
28, which makes parser unaware of 'history' field altogether

**Comment by ghost** [comment]
**Comment by @frederikhabils on 23 Jul 2003 09:03 UTC**
comment 25 looks satisfactory :-)

**Comment by ghost** [comment]
**Comment by @stefanb on 23 Jul 2003 10:59 UTC**
about error messages:
is it better to catch all java.sql.SQLExceptions, title them as 
"Makumba SQL error" and just give a reason, without a scary stacktrace (still 
included as hidden html comment)

Managed to do so in 
http://cvs.makumba.org/classes/org/makumba/devel/TagExceptionServlet.java
the error seen by the user is now:
---
Makumba SQL error 
Invalid argument value,  message from server: "Duplicate entry 'sl' for key 3"
---
hopefully this is short enough so that users will actually read the message, 
not just say it doesn't work when seeing huge stacktrace

...but donno if this hides some important stacktraces for business logic 
developers, so i didn't commit it yet.

**Comment by ghost** [comment]
**Comment by @frederikhabils on 23 Jul 2003 21:11 UTC**
this error message thing (comment 24 [a], etc) certainly is a headache

- I guess it should be possible to determine, from SQLSTATE or other errorcode 
numbering systems, that the SQLException is "NotUniqueException". I like the 
ideas of comment 2, to throw a specific exception for it... or the DB_error() 
solution... I just don't know yet how to make it most practical. 
I think the idea of comment 27 is a start, but only that... It lacks in user-
friendliness, and as per bug 443, I prefer _not_ to show "Makumba error" at 
all, esp. where user-programmed logic (in this case data-logic) is the source 
of the 'error')

- I've seen no indication so far that it would be possible to retrieve and 
present in user-friendly way exactly WHICH uniqueness (i.e. which of the 
various unique fields in a record) is broken for an update/insert. Db message 
is referring to unique fields by a number (see prev comments) :-(

**Comment by ghost** [comment]
**Comment by @stefanb on 23 Jul 2003 21:28 UTC**
>- I've seen no indication so far that it would be possible to retrieve and 
>present in user-friendly way exactly WHICH uniqueness (i.e. which of the 
>various unique fields in a record) is broken for an update/insert. Db message 
>is referring to unique fields by a number (see prev comments) :-(
The only possibility seems to run a (costly?) select on all unique fields 
before insert and update.

This can be done by overriding abstract checkInsert in
http://cvs.makumba.org/classes/org/makumba/abstr/FieldHandler.java
with a checkInsert method in
http://cvs.makumba.org/classes/org/makumba/db/sql/FieldManager.java

see also:
$ fgrep 'checkInsert' `find . -name '*.java'`
$ fgrep 'checkUpdate' `find . -name '*.java'`

#going offline for a week, to cristi's wedding and a shorter ITC meeting in .ro

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 20 Aug 2003 13:41 UTC**
comment 29:

> The only possibility seems to run a (costly?) select on all unique fields 
> before insert and update.

grrr... how about doing those selects _after_ the exception occured? then you
will do them in an exceptional case, where performance doesn't matter anyway

i will also suggest (at bug 513) a human-readable description for each
uniqueness constraint, that will improve the error message

**Comment by ghost** [comment]
**Comment by @stefanb on 23 Aug 2003 11:13 UTC**
Cristi, thank you for the idea in comment 30, worth looking into it!

I was giving up on implementation of pre-insert/update checks (comment 29)
because current code (DataHolder if memory serves well) just calls abstract
checkInsert() and checkUpdate() methods... and i didn't want to mess around too
much :)

**Comment by ghost** [comment]
**Comment by @stefanb on 23 Aug 2003 17:58 UTC**
Aaargh! 
From SQLException caught at  
  org.makumba.db.sql.SQLUpdate.execute(SQLUpdate.java:137) 
I get (ugly)message, SQLState and errorCode:
WARNING: Invalid argument value,  message from server: "Duplicate entry 'sl' for
key 3" SQL state: S1009 error code :1062
       ^^^^^^^^^^^^^^^^
even if http://www.mysql.com/doc/en/Error-returns.html defines:
ER_DUP_ENTRY 	 errcode:1062	 SQLState:23000
                                 ^^^^^^^^^^^^^^
We can't rely on message to always have this format, nor that index numbers will
represent the order in mdd.
error codes are vendor dependant (and can't figure them out)
and SQLstate not only that can be the same for several errors, it appearently
changes even between versions from same vendor.
(using MySQL-AB JDBC Driver version: 3.0.5-gamma)

Only after we re sure that the error was because of duplicate entry we can start
to discover which is the guilty field (which might also be interesting in case
of editing eg student.person.name of best.internal.Student)

Starting to wonder if pre-insert/update queries are really that expensive. in
most cases the resultset would be empty (for insert) or at most 1 record (for
update). Because unique fields are indexed anyway, looking for duplicates is fast.

Also wondering about the purpose of totally undocumented DataHolder class.
Can it ease solving this?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 25 Aug 2003 18:16 UTC**
> I was giving up on implementation of pre-insert/update checks (comment 29)
> because current code (DataHolder if memory serves well) just calls abstract
> checkInsert() and checkUpdate() methods... and i didn't want to mess around too
> much :)

what do you mean by "calls abstract ... methods" ? 

DataHolder gets a data records with keys of the form ptr1.ptr2.xxx and
transforms them into a group of DataHolders, each containing single-record (non
pointer) key-value pairs, then it executes operations (checking, inserting, etc)
into these recursively.

about comment 32: i really think that drawing this to a close now that so much
good work has been done is more important than closing it in a perfect way
(mysql-independent, version-independent, etc). 

the post-check solution idea can look like
- insert
- if it fails, check if it was due to duplicate key, no matter which one
- run selects for each uniqueness as described in the MDD and see which is the
guilty one

but of course this is strongly affected by bug 542 so pre-write checks might
make more sense for now, though they are affected by data integrity problems
(bug 48) because another write may happen between the check and the write,
resulting in a notUniqueError, which brings us back to the need for transactions
in multi-table writes (bug 542)

it may be wiser to turn to simpler problems for now (JSP bugs, etc), but it
looks like bug 3 needs the fix of bug 542 before getting in production anyway.

**Comment by ghost** [comment]
**Comment by @stefanb on 25 Aug 2003 18:33 UTC**
>what do you mean by "calls abstract ... methods" ? 
Sorry, I badly expressed myself. In comment 31 I meant:
"calls the checkInsert() methods in org.makumba.abstr.* package"

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 25 Aug 2003 19:09 UTC**
> In comment 31 I meant:
> "calls the checkInsert() methods in org.makumba.abstr.* package"

those are at field level. as per bug 513, you'd have to make the uniqueness
checks at record level (since more than one field can be involved in a constraint)

so DataHolder would probably be the place. 

but post-tests still look like a better solution (bug 542 seems to affect both
pre and post tests equally)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 26 Aug 2003 14:04 UTC**
about comment 31 (and the whole issue of detecting the index whose uniqueness
was broken in a vendor independent manner):

the present idea discussed with Stefan is that from a string like "Duplicate
entry 'sl' for key 3" we can find which is the 3rd row returned by "SHOW INDEX
FROM tablename" and then we know which index was broken (whether it's a unique
field, or a unique constraint, bug 513)

some aspects of this (especially the error message) may be mysql-dependent, but
we cannot know that before getting another db to production quality. then fixing
it in a db-independent manner can use sqlEngines.properties or a db-specific
package.

even before that, we can separate this potentially mysql-dependent stuff in a
org.makumba.db.sql.Database method, which can later be redefined in a
db-specific class, etc. 

but for now i suggest to concentrate on mysql, and refactor when supporting
other dbs

about variations for the same vendor: i see that the error code (1062) is the
same, although the SQL state changed. can we use that?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 24 Sep 2003 13:03 UTC**
i have experimented with cross-database copying (bug 93) and found that odbc and
informix have pretty unusable messages when a unique index is broken.

so i think the post-insert check is maybe the only way out. i would put it in
RecordManager.insertRecordImpl, simply catch an exception, see (in a
database-dependent way) if it _may_ be a duplicate index (cause i'm sure the
ODBC error is more general than that) and then do a SELECT for each unique
condition, and report a higher-level error if equal values are found for a field
or (bug 513) group of fields. since we are (hopefully) in a repeatable read
transaction, data should not change from the failed INSERT to the SELECT.

ODBC says 
24-Sep-2003 14:57:56 org.makumba.db.sql.Database logException
WARNING: General error SQL state: S1000 error code :0

java.sql.SQLException: General error
        at sun.jdbc.odbc.JdbcOdbc.createSQLException(JdbcOdbc.java:6908)
....

Informix gives a more precise error:

24-Sep-2003 14:09:37 org.makumba.db.sql.Database logException
WARNING: Could not insert new row - duplicate value in a UNIQUE INDEX column. SQ
L state: 23000 error code :-239
ISAM error: duplicate value for a record with unique key. SQL state: IX000 error
 code :-100

java.sql.SQLException: Could not insert new row - duplicate value in a UNIQUE IN
DEX column.
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:348)
....

the makumba part of these stacktraces is the expected:

        at org.makumba.db.sql.RecordManager.insertRecordImpl(RecordManager.java:
505)
        at org.makumba.db.Table.insertRecord(Table.java:150)
        at org.makumba.db.DataHolder.insert(DBConnection.java:401)
        at org.makumba.db.DBConnection.insert(DBConnection.java:157)
        at org.makumba.db.DBConnectionWrapper.insert(DBConnectionWrapper.java:47
)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 5 Oct 2003 10:43 UTC**
are we done with the thinking here? is it ok to assume that
- post insert tests are the only reliable way to detect the broken key in most dbs
- repeatable read transactions are sufficient for reliably determining the
broken key
- alternatively, in mysql it may be possible to detect the broken key from the
error message

should we do the programming (for mysql or more universal) and finish this up? 

should this be fixed first, or together with bug 513?

Stefan, are you in, or you want somebody else to take it from here?

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 6 Apr 2004 23:27 UTC**
i tried to have the throwing of org.makumba.NotUniqueError in a general way
(i.e. not mysql-specific)

about the user-readability of the NotUniqueError, it contains all data necessary
to produce more readable errors. the default message is like 

    [java] org.makumba.NotUniqueError: There is already a best.Auth that
has <shortname> set to 'cristi'.

simply doing a replace of best.Auth with "best account", etc. will generate a
more readable message.

about any other issue raised here and not yet solved, i think it should become a
post-0.6 bug
