### ISSUE TITLE
Wrong tag from other file shown as source of error in form response

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#407]
**Reported by @stefanb on 12 Jan 2005 17:24 UTC**
While testing problems with bug 788 on http://private.best.eu.org/test/types.jsp
I noticed that after entering "aaa" into the first int field (and selecting some
set int values because of bug 788) yields a decieving error message:
----
Makumba invalid value error

While executing inside this body tag, but most probably _not_ due to the tag:
/home/projects/karamba/sources/karamba/public_html/johnny/lbg/evaluating/evaluationsStats.jsp:176:1:176:223
176:
<mak:list from="best.johnny.Application app, app.evaluation eval, eval.answers
a" where="app.activ=$activity AND app.evaluationSigned<>nil AND
a.number=q.number AND (a.letter=q.letter OR (q.letter='' AND a.letter=NIL) )" >
^
Invalid value for expression 'theInt': invalid integer: aaa
Makumba developer support, version: 0.5.13.3
----
It is probably connected to recent changes in error reporting, which show the
problematic tag, as remembered from page analysis. 
Message should either show the int input tag or not show the wrong tag from
other file at all, as it is not related.

Migrated-From: http://trac.makumba.org/ticket/789

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 12 Jan 2005 17:32 UTC**
very strange.

what does types.jsp have to do with johnny/lbg/evaluating/evaluationsStats.jsp?

if i try to reproduce, i get 
While executing inside this body tag, but most probably _not_ due to the tag:
/home/projects/karamba/sources/karamba/public_html/test/types.jsp:10:1:10:46
10:
<mak:form action="types.jsp" method="post"  >
^

Invalid value for expression 'theInt': invalid integer: AAAA

which looks quite OK, though it isn't so much correct as the error actually
occurs during the form response.

if you see the error again, please press "view source", you should see the
stacktrace there, please put it here.

**Comment by ghost** [comment]
**Comment by @stefanb on 12 Jan 2005 18:59 UTC**
I mamaged to reproduce it
a) entered "aaa" into the int field,
b) selected "eee" in the set int field
c) set ptr and set field to some value
d) submit it. If you get the error from comment 1, press back and start agaom
from step c).

the hidden stacktrace on the error from comment 0 is:
org.makumba.view.InvalidValueException: Invalid value for expression 'theInt':
invalid integer: aaa
	at org.makumba.controller.html.FieldEditor.toInt(FieldEditor.java:116)
	at org.makumba.controller.html.intEditor.readFrom(intEditor.java:52)
	at org.makumba.controller.html.RecordEditor.readFrom(RecordEditor.java:52)
	at org.makumba.controller.html.FormResponder.getHttpData(FormResponder.java:43)
	at org.makumba.controller.http.Responder$4.respondTo(Responder.java:327)
	at org.makumba.controller.http.Responder.response(Responder.java:256)

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 12 Jan 2005 19:01 UTC**
Well Lode and me happen to have got a couple of those today:
E.g during some fixing of a bug related to CV editing in BCC (=minerva)

Error in business logic code
While executing inside this body tag, but most probably _not_ due to the tag:
/home/projects/karamba/sources/karamba/public_html/tasks/tasks.jsp:6:1:6:93
6:
<mak:object from="best.internal.Student ins, ins.student s, s.person p"
where="ins=$member"> 
^
java.lang.NullPointerException
	at
org.eu.best.minerva.StudentLogic.on_editBestMinervaStudent(StudentLogic.java:149)
	
I still have the page in my browser history so I could give you the (HTML?)
source. But there is really nothing special there..

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 13 Jan 2005 09:58 UTC**
fixed in 0.5.13.4, get it with getMakumba

the problem comes from tomcat reusing threads. since the tag info is stored in
thread-local variables, when the thread is reused by tomcat, it may be that some
"residual" error information is left there from a previous usage of the thread.
so i added some cleanup, hopefully it's enough.
