### ISSUE TITLE
mak:input / mak:option fails in connection with subrecords

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#411]
**Reported by @rudolfmayer on 27 Jan 2005 14:26 UTC**
i did now a more tricky mak:input / mak:option example, more tricky meaning that
the mak:options are a subrecord having a ptr to another subrecord.

my MDD is like this:

ToolboxEntry.mdd: 

inCategory=set 
  inCategory->category=ptr best.internal.marketeam.ToolboxCategory.subCategory
  inCategory->position=int
(http://vtkbest.ugent.be:8080/rudi-k/dataDefinitions/best.internal.marketeam.ToolboxEntry)

while the ToolboxCategory looks like: 

subCategory=set;
  subCategory->name=char[255]
  subCategory->position=int
(http://vtkbest.ugent.be:8080/rudi-k/dataDefinitions/best.internal.marketeam.ToolboxCategory)

now, i wanted to make a

<mak:input field="category">
  <mak:list from="best.internal.marketeam.ToolboxCategory cat">
    <mak:list from="cat.subCategory choice">
      <mak:option value="choice"> 
       <mak:value expr="choice.name" /> 
      </mak:option>
    </mak:list>
  </mak:list>
</mak:input>

which results in a makumba error:

Makumba data definition parse error
During analysis of the following tag (and possibly tags inside it):
/home/parade/rudi/karamba/public_html/committees/marketeam/toolbox/admin/toolboxEntryEdit_new.jsp:128:18:128:45
128:
            	    <mak:option value="choice"> <mak:value expr="choice.name" />
</mak:option>
                 ^

Invalid character "-" in type name "best.internal.marketeam.ToolboxCategory-"

when changing the label of the subCategory to anything else than choice, and
using this mak:list & mak:values outside a mak:option, as can be seen at
ttp://vtkbest.ugent.be:8080/rudi-k/committees/marketeam/toolbox/admin/toolboxEntryEdit.jsp?entry=840i9l3,
works fine, so i am pretty sure it is a problem with mak:option / mak:input
implementation

Migrated-From: http://trac.makumba.org/ticket/797

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 27 Jan 2005 22:20 UTC**
Rudi I'd appreciate if you investigated a bit as getting everything on my
machine to test (+ lack of time & stress) seems a bit uncomfortable now

here's some guidance: relevant stacktrace lines

> 	at org.makumba.abstr.RecordParser.parse(RecordParser.java:82)
> 	at org.makumba.abstr.FieldInfo.getFieldInfo(FieldInfo.java:51)
> 	at org.makumba.MakumbaSystem.makeFieldDefinition(MakumbaSystem.java:127)
> 	at org.makumba.view.jsptaglib.OptionTag.getTypeFromContext(OptionTag.java:58)
> 	at org.makumba.view.jsptaglib.BasicValueTag.doEndAnalyze(BasicValueTag.java:87)


the probelm seems to be here
org.makumba.view.jsptaglib.OptionTag.getTypeFromContext(OptionTag.java:58)

the way OptionTag determines the type of the pointer doesn't seem to fit the
subset type.

in MakumbaSystem.makeFieldDefinition the type computation is done by making an
imaginary MDD. i think referring a subset is allowed MDDs and queries by the
construct type#subsetField or type.subsetField. but i don't remember exactly

maybe the getRelationType() called at OptionTag:58 is the problem. though as far
as i remember we're talking about the type of the <mak:input > not the type of
mak:option

i am a bit taken aback by this
> 111:	      <mak:list from="tbe.inCategory category">
> 112:	        <mak:editForm action="${actionPage}" object="category">
> 113:	        <tr>
> 114:	          <td>
> 115:	            <mak:input field="category">

maybe it would be an idea to change the name of the category label to not
collide with the category field. 

actually i can't really understand what you are doing because in
best.internal.marketeam.ToolboxEntry i see
20:	inCategory=set 
21:	  inCategory->;category=ptr
best.internal.marketeam.ToolboxCategory.subCategory ;
22:	  inCategory->;position=int ;

what's inCategory->;category supposed to mean??? probably you added that
afterwards but this tel me that this is really for you to investigate more.

this seems way too complicated anyway. why don't you use something like MIME types?

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 4 Apr 2016 12:33 UTC**
ITC tries to reproduce before downgrading the bug
