### ISSUE TITLE
NullPointerException  when no DBSV is specified in the db connection file

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#426]
**Reported by @cristianbogdan on 25 Feb 2005 12:50 UTC**
should be a ProgrammerError

Migrated-From: http://trac.makumba.org/ticket/815

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 25 Feb 2005 12:51 UTC**
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.<init>(Unknown Source)
	at org.makumba.db.Database.<init>(Database.java:280)
	at org.makumba.db.sql.Database.<init>(Database.java:95)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.makumba.db.Database$1.makeResource(Database.java:163)
	at org.makumba.util.NamedResourceFactory.makeResource(NamedResourceFactory.java:61)
	at org.makumba.util.ProducerReturner.getRes(NameValue.java:65)
	at org.makumba.util.NameValue.getResource(NameValue.java:51)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:140)
	at org.makumba.db.Database.getDatabase(Database.java:261)
	at org.makumba.MakumbaSystem.getConnectionTo(MakumbaSystem.java:66)

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 26 Jun 2010 16:53 UTC**
when no dbsv AND no autoIncrement is specified, makumba now complains with a ConfigurationError.
