### ISSUE TITLE
<mak:input dataType="set char{...}"/> not handled by 0.5.14

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#440]
**Reported by @gwenael-alizon on 29 Apr 2005 11:07 UTC**
During analysis of the following tag (and possibly tags inside it):
/home/parade/joao/karamba/public_html/minerva/student/find_acti.jsp:136:1:136:2
24
136:
<mak:input name="activityKinds" dataType="set char{\"conference\", 
\"contest\", \"cultural event\", \"internship\", \"job\", \"jobfair\", 
\"other\", \"project\", \"seminar\", \"master\", \"phd\", \"sch\"}" 
display="false"/>
^

Please report to the developers.

java.lang.NullPointerException
	at org.makumba.abstr.subtableParser.addPtr(subtableParser.java:42)
	at org.makumba.abstr.subtableParser.addPtrHere(subtableParser.java:65)
	at org.makumba.abstr.setEnumParser.parse(setEnumParser.java:33)
	at org.makumba.abstr.FieldParser.setType(FieldParser.java:100)
	at org.makumba.abstr.setParser.enumSet(setParser.java:90)
	at org.makumba.abstr.setParser.parse(setParser.java:49)
	at org.makumba.abstr.FieldParser.setType(FieldParser.java:100)
	at org.makumba.abstr.FieldParser.parse(FieldParser.java:73)
	at org.makumba.abstr.RecordParser.treatMyFields(RecordParser.java:307)
	at org.makumba.abstr.RecordParser.parse(RecordParser.java:130)
	at org.makumba.abstr.RecordParser.parse(RecordParser.java:101)
	at org.makumba.abstr.FieldInfo.getFieldInfo(FieldInfo.java:55)
	at org.makumba.MakumbaSystem.makeFieldDefinition
(MakumbaSystem.java:134)
	at org.makumba.view.jsptaglib.BasicValueTag.doEndAnalyze
(BasicValueTag.java:92)
	at org.makumba.view.jsptaglib.InputTag.doEndAnalyze(InputTag.java:95)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer$ParseStatus.endPage
(MakumbaJspAnalyzer.java:214)
	at org.makumba.view.jsptaglib.MakumbaJspAnalyzer.endPage
(MakumbaJspAnalyzer.java:269)
	at org.makumba.util.JspParseData.parse(JspParseData.java:196)
	at org.makumba.util.JspParseData.getAnalysisResult
(JspParseData.java:143)
	at org.makumba.view.jsptaglib.MakumbaTag.getPageCache
(MakumbaTag.java:117)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag
(MakumbaTag.java:191)
	at org.apache.jsp.minerva.student.find_005facti_jsp._jspService
(find_005facti_jsp.java:80)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:94)
	

-------------------------------------------------------------------------------
-
Makumba developer support, version: 0.5.14

Migrated-From: http://trac.makumba.org/ticket/838

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 29 Apr 2005 13:31 UTC**
i have a testcase that confirms the bug. will look into it and decide if it will
be fixed in the antwerpen branch (i.e. later) or in the main trunk

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 1 May 2005 22:23 UTC**
a small refactoring mistake was to blame
