### ISSUE TITLE
null duplicates checking

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#454]
**Reported by @cristianbogdan on 13 Nov 2005 14:35 UTC**
currently makumba can check which is the field that was duplicate from an 
inserted record. however, this doesn't work if the field value is null 
(duplicate null values seem to actually break unique constraints)

see org.makumba.db.sql.TableManager, line 1658

Migrated-From: http://trac.makumba.org/ticket/901

**Comment by ghost** [comment]
**Comment by @adlerscout on 13 Nov 2005 14:54 UTC**
Inserting a null value twice in a unique field can give an error or not
depending on the DB. If the DB considers that "null" is in fact a value 
it
doesn't allow you to insert 'null' twice in that field. This is the 
case of Hysqldb.

mySQL, allows you to have two entries with 'null' in a unique field.

maybe some other DB can be tested for this.

**Comment by ghost** [comment]
**Comment by @stefanb on 13 Nov 2005 14:54 UTC**
(In reply to comment #1)
> maybe some other DB can be tested for this.
Interesting:
MSSQL doesn't allow duplicate null values in a unique field (like 
hsqldb), but
Oracle does (like MySql).

**Comment by ghost** [comment]
**Comment by priit@best.eu.org on 13 Nov 2005 15:09 UTC**
Some more background info.

Actually, it's not MySQL that enforces the duplicate NULL constraint, 
but the
table type that we use (InnoDB, also MyISAM behaves the same). From
http://dev.mysql.com/doc/mysql/en/create-table.html:
In MySQL, a UNIQUE index is one in which all values in the index must 
be
distinct. /---/ The exception to this is that if a column in the index 
is
allowed to contain NULL values, it can contain multiple NULL values. 
This
exception does not apply to BDB tables, for which an indexed column 
allows only
a single NULL.

Also, for broader picture - postgres has this
(http://www.postgresql.org/docs/6.5/interactive/sql-createtable.htm):
Having more than one null value in a column without a NOT NULL 
constraint, does
not violate a UNIQUE constraint. (This deviates from the SQL92 
definition, but
is a more sensible convention. /---/).

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 13 Nov 2005 15:11 UTC**
if the db detects a null duplicate, makumba will now report it like 
below. i
don't know if there is much more makumba can do. 

i wonder if there are null duplicates in current production data, and 
how can
they be handled. but maybe a new karamba bug can be entered in that 
regard, as i
don't see what else can be done on this bug before closing

org.makumba.NotUniqueError: There is already a test.Person that has 
<uniqPtr>
set to 'null'.
There is already a test.Person that has <uniqDate> set to 'null'.
There is already a test.Person that has <extraData> set to 'null'.
	at 
org.makumba.db.sql.TableManager.findDuplicates(TableManager.java:685)
	at 
org.makumba.db.sql.TableManager.insertRecordImpl(TableManager.java:655)
	at org.makumba.db.Table.insertRecord(Table.java:235)
	at org.makumba.db.DataHolder.insert(DBConnection.java:430)
	at org.makumba.db.DBConnection.insert(DBConnection.java:183)
	at 
org.makumba.db.DBConnectionWrapper.insert(DBConnectionWrapper.java:47)
	at test.http.TestTags$Suite.insertPerson(TestTags.java:111)
...

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 13 Nov 2005 15:12 UTC**
i realized that, due to the null duplicate problems, "internal" 
pointers like

extraData=ptr
extraData->f=t

cannot be unique. makumba was declaring them unique internally, but 
obviously
many of them are null, so they are not unique. so makumba doesn't make 
them
unique any longer.

the pair (key, extraData) is on the other hand unique. but we don't 
have that in
makumba today (bug 513) and it probably doesn't make sense to add it 
before
passing to hibernate.

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 13:14 UTC**
