### ISSUE TITLE
innodb problems with mysql 4.1.14

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#455]
**Reported by @cristianbogdan on 13 Nov 2005 14:38 UTC**
when running the makumba table tests with mysql 4.1.14 everything works ok
except that all tables are altered to innodb everytime they are checked. this
hits the harddisk a lot and probably renders makumba unusable with big tables on
mysql 4.1.

i could determine the root for the problem, it's in
org.makumba.db.sql.MysqlTableManager line 43. 

    ResultSet rs=st.executeQuery("SHOW CREATE TABLE "+getDBName());
    rs.next();
    String def=rs.getString(2).trim();

    if(def.lastIndexOf(')') > def.lastIndexOf(" TYPE=InnoDB")

so the mak code expects to see "type= innodb" at the end of the create table
statement

in mysql 4.1.14 the show create table returns
...
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |

but if i changed the test to

    if(def.lastIndexOf(')') > def.lastIndexOf(" TYPE=InnoDB") &&
			def.lastIndexOf(')') > def.lastIndexOf(" ENGINE=InnoDB")){

then no tables are altered but one test (testQueryValidMdds) gives an error.
i haven't written that test and i don't have time to understand it now. maybe
someone wants to continue on this. the stacktrace is below. it seems to me that
table type can play a role in this but i don't know how, especially since the
table type (innodb) is correct... maybe the simple fact that alteration takes
time makes the test work in the existing version...

in db command Result for null
java.sql.SQLException: Cannot convert value '0000-00-00 00:00:00' from column 3
to TIMESTAMP.
	at com.mysql.jdbc.ResultSet.getTimestampFromString(ResultSet.java:5410)
	at com.mysql.jdbc.ResultSet.getTimestampInternal(ResultSet.java:5435)
	at com.mysql.jdbc.ResultSet.getTimestamp(ResultSet.java:2395)
	at org.makumba.db.sql.TableManager.get_timeStamp_Value(TableManager.java:925)
	at org.makumba.db.sql.TableManager.getValue(TableManager.java:820)
	at org.makumba.db.sql.TableManager.fillResult(TableManager.java:774)
	at org.makumba.db.sql.Query.goThru(Query.java:109)
	at org.makumba.db.sql.Query.execute(Query.java:95)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:210)
	at org.makumba.db.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:44)
	at org.makumba.db.DBConnection.executeQuery(DBConnection.java:213)
	at test.table.testQueryValidMdds(table.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at test.table.run(table.java:598)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:474)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:342)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:194)

Migrated-From: http://trac.makumba.org/ticket/902

**Comment by ghost** [comment]
**Comment by @stefanb on 13 Nov 2005 15:19 UTC**
This looks familiar for a reason ... 

I fixed the problem in
classes/org/makumba/db/sql/mysql/RecordManager.java
which was later (during merge of antwerpen branch to MAIN) removed
http://cvs.sf.net/viewcvs.py/makumba/makumba/classes/org/makumba/db/sql/mysql/At
tic/RecordManager.java?rev=1.9&view=log
and thus change disappeared from the MAIN, which only has.
http://cvs.sf.net/viewcvs.py/makumba/makumba/classes/org/makumba/db/sql/MysqlTab
leManager.java?rev=2.1&view=log

that MysqlTableManager.java was based on an older version of
mysql/RecordManager.java
