### ISSUE TITLE
MsSql requires hardcoded (non-parametrized) strings to be single quoted in queries

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#458]
**Reported by @stefanb on 13 Nov 2005 14:56 UTC**
A test
    db.delete("test.validMdds.CharWithLength t", "t.name LIKE \"www\"", null);
is failing with: 

in db command delete on type: <test.validMdds.CharWithLength	t>  where: <t.name
LIKE "www">
 generated SQL: DELETE FROM test_validMdds_CharWithLength_ WHERE ( name_ LIKE "www")
java.sql.SQLException: [2000 Driver for
JDBC](Microsoft][SQLServer)[SQLServer]Invalid column name 'www'.
	at com.microsoft.jdbc.base.BaseExceptions.createException(Unknown Source)
	at com.microsoft.jdbc.base.BaseExceptions.getException(Unknown Source)
	at com.microsoft.jdbc.sqlserver.tds.TDSRequest.processErrorToken(Unknown Source)
	at com.microsoft.jdbc.sqlserver.tds.TDSRequest.processReplyToken(Unknown Source)
	at com.microsoft.jdbc.sqlserver.tds.TDSExecuteRequest.processReplyToken(Unknown
Source)
	at com.microsoft.jdbc.sqlserver.tds.TDSRequest.processReply(Unknown Source)
	at
com.microsoft.jdbc.sqlserver.SQLServerImplStatement.getNextResultType(Unknown
Source)
	at com.microsoft.jdbc.base.BaseStatement.commonTransitionToState(Unknown Source)
	at com.microsoft.jdbc.base.BaseStatement.postImplExecute(Unknown Source)
	at com.microsoft.jdbc.base.BasePreparedStatement.postImplExecute(Unknown Source)
	at com.microsoft.jdbc.base.BaseStatement.commonExecute(Unknown Source)
	at com.microsoft.jdbc.base.BaseStatement.executeUpdateInternal(Unknown Source)
	at com.microsoft.jdbc.base.BasePreparedStatement.executeUpdate(Unknown Source)
	at org.makumba.db.sql.SQLUpdate.execute(SQLUpdate.java:172)
	at org.makumba.db.DBConnection.executeUpdate(DBConnection.java:222)
	at org.makumba.db.DBConnection.delete(DBConnection.java:331)
	at org.makumba.db.DBConnectionWrapper.delete(DBConnectionWrapper.java:62)
	at test.table.testDelete(table.java:474)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at test.table.run(table.java:598)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:478)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:344)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)

similar tests work fine:
 db.delete("test.validMdds.CharWithLength t", "5=5", null);
 db.delete("test.validMdds.CharWithLength bla", "'x'=bla.name", null);

Not sure how this could be resolved generically. Any ideas?
Workaround would be to use 'single quotes' if parameters need to be hardcoded
into queries.

Migrated-From: http://trac.makumba.org/ticket/905

**Comment by ghost** [comment]
**Comment by @stefanb on 13 Nov 2005 15:02 UTC**
The answer seems to be at:
http://msdn.microsoft.com/library/default.asp?url=/library/en-us/tsqlref/ts_set-set_0bjo.asp

and a bit more general:
http://msdn.microsoft.com/library/default.asp?url=/library/en-us/tsqlref/ts_set-set_0bjo.asp

**Comment by ghost** [comment]
**Comment by @stefanb on 13 Nov 2005 15:03 UTC**
(In reply to comment #1)
aaargh, i got framed....

>> The answer seems to be at:

http://msdn.microsoft.com/library/en-us/tsqlref/ts_set-set_9jxu.asp
 

>> and a bit more general:

http://msdn.microsoft.com/library/en-us/tsqlref/ts_set-set_1vqe.asp

**Comment by ghost** [comment]
**Comment by @stefanb on 13 Nov 2005 15:06 UTC**
On each new connection makumba first executes "SET QUOTED_IDENTIFIER OFF"
