### ISSUE TITLE
hibernate cannot create foreign key constraints due to makumba not declaring primary keys

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#503]
**Reported by @cristianbogdan on 2 Aug 2006 13:53 UTC**
running the test.http.TestHibernateTags with an empty database and
autoIncrement=true (no dbsv) works ok, but at tearDown the error below is produced. 

the first guess is that the way hibernate adds indexes somehow interfeers with
the fact that makumba has already declared primary keys by the time hibernate
does its schema update. primary keys are not declared in the old (dbsv)
mechanism. actually the test works with autoIncrement if the tables were
generated without autoIncrement.

in db command delete on type: <test.Person this>  where: <this.Person=$1>
 generated SQL: DELETE FROM test_Person_ WHERE ( Person_ = ?)
java.sql.SQLException: Cannot delete or update a parent row: a foreign key
constraint fails
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2851)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1531)
	at
com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1366)
	at
com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:952)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1974)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1897)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1758)
	at org.makumba.db.sql.SQLUpdate.execute(SQLUpdate.java:172)
	at org.makumba.db.DBConnection.executeUpdate(DBConnection.java:222)
	at org.makumba.db.DBConnection.delete1(DBConnection.java:285)
	at org.makumba.db.DBConnection.delete(DBConnection.java:250)
	at org.makumba.db.DBConnectionWrapper.delete(DBConnectionWrapper.java:60)
	at test.http.TestHibernateTags$Suite.deletePerson(TestHibernateTags.java:133)
	at test.http.TestHibernateTags$Suite.tearDown(TestHibernateTags.java:155)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:20)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.extensions.TestSetup.run(TestSetup.java:23)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:478)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:344)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)

Migrated-From: http://trac.makumba.org/ticket/955

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 2 Aug 2006 13:57 UTC**
more mysql error info

SQL state: 23000 error code :1217

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 2 Aug 2006 14:14 UTC**
i guess a simple workaround is:
1. run ant checkDb with dbsv (no auto increment)
2. run hibernate schema update
3. set auto increment (and maybe run checkDb)

for an existing db, you can most probably start at step 2

checkDb (schema update for the whole db) seems to be more and mroe needed before
makumba can run properly, see also bug 254

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 2 Aug 2006 16:46 UTC**
ok, the problem is rather different. the error code (1217=ER_ROW_IS_REFERENCED)
revealed a problem in the test code

            db.delete(brother);
            db.delete(person);

since the brother record is referenced by the person record, it is actually
correct that brother deletion fails, since its referrent must be deleted first.

why was this not detected before? the reason is that creation of hibernate
foreign keys failed, because because makumba creates the tables without making
indexes (since it waits for hibernate to make indexes). if no autoIncrement is
used (so no primary keys are declared), the test log is full of this type of
messages

alter table test_Person_ add index FKEE11A0DDABBEF3F0 (brother_), add constraint
FKEE11A0DDABBEF3F0 foreign key (brother_) references test_Person_ (Person_)
02-Aug-2006 17:55:25 org.hibernate.tool.hbm2ddl.SchemaUpdate execute
SEVERE: Unsuccessful: alter table test_Person_ add index FKEE11A0DDABBEF3F0
(brother_), add constraint FKEE11A0DDABBEF3F0 foreign key (brother_) references
test_Person_ (Person_)
02-Aug-2006 17:55:25 org.hibernate.tool.hbm2ddl.SchemaUpdate execute
SEVERE: Can't create table '.\makumba\#sql-31c_186.frm' (errno: 150)

errno 150 is a foreign key error. altering the table by hand to declare Person_
as a key in test_Person_ removes the problem. 

to fix this problem, i decided that using hibernate with the present makumba db
layer will automatically mean using auto_increment. that means that when makumba
sees that hibernate is used, it will alter its tables to "auto_increment primary
key", even if dbsv will still be used to insert records.
