### ISSUE TITLE
Mak crashes on most two-level included jsp files that contain mak tags

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#511]
**Reported by e teeselink on 11 Jan 2007 19:40 UTC**
(sorry if i picked the wrong mak version - this bugzilla thing is a bit new for 
me)

Assumed setup:
A main page "page A" which <%@include>s another page, "page B"
Page B has a mak:list tag, and an <%@include>d page called "page C"
Page C has one or more <mak:value> tags and some text.

Problem: Makumba crashes with an odd error message on *some* variations of page 
C. I did some testing, and it seems that if page C contains words like "value" 
more than once (even "alue" seems to do the trick), then it crashes. If page C 
is a very simple and short page, however, possibly with just one <mak:value> 
tag, then it works.

Test at http://tequila.best.eu.org/egbert-k/test/includeTest.jsp
Inside http://tequila.best.eu.org/egbert-k/test/includeTestInclude.jsp, replace

<%@ include file="includeTestIncludeInclude.jsp"%>

by

<%@ include file="includeTestIncludeIncludeWORKS.jsp"%>

To see a version that does not cause mak to crash. I guess the mak jsp analyzer 
makes some assumptions that it shouldn't make, or something. Any fixes would be 
wildly appreciated for I'm trying to make the BAS eventList.jsp not suck. 
Thanks!

-egbert

Migrated-From: http://trac.makumba.org/ticket/963

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 12 Jan 2007 09:34 UTC**
i think i saw another problem with multiple-level @includes recently

@include was not supported by page analysis in the begining to what i remember.
maybe we focused on only 2-level include when we started to support it. so a
code review ay be in order.

can you paste here the error message, no matter how odd?

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 14 Aug 2007 16:48 UTC**
Apparently that's the error message appearing (when following the link):

While executing page <a href="/egbert-k/test/includeTest.jspx">/test/includeTest.jsp</a>

Please report to the developers.
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.get(ArrayList.java:326)
	at org.makumba.util.SourceSyntaxPoints.setLineAndColumn(SourceSyntaxPoints.java:281)
	at org.makumba.util.SourceSyntaxPoints.addSyntaxPoints1(SourceSyntaxPoints.java:268)
	at org.makumba.util.SourceSyntaxPoints.addSyntaxPoints(SourceSyntaxPoints.java:262)
	at org.makumba.util.JspParseData.treatTag(JspParseData.java:351)
	at org.makumba.util.JspParseData.treatTags(JspParseData.java:325)
	at org.makumba.util.JspParseData.parse(JspParseData.java:219)
	at org.makumba.util.JspParseData.getAnalysisResult(JspParseData.java:150)
	at org.makumba.view.jsptaglib.MakumbaTag.getPageCache(MakumbaTag.java:122)
	at org.makumba.view.jsptaglib.MakumbaTag.doStartTag(MakumbaTag.java:191)
	at <a href="/egbert-k/classes/org.apache.jsp.test.includeTest_jsp#97">org.apache.jsp.test.includeTest_jsp._jspx_meth_mak_list_0</a>(includeTest_jsp.java:97)
	at <a href="/egbert-k/classes/org.apache.jsp.test.includeTest_jsp#71">org.apache.jsp.test.includeTest_jsp._jspService</a>(includeTest_jsp.java:71)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:94)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 30 Oct 2007 08:58 UTC**
i fixed two-level includes last night.

i had exactly the same stacktrace so this problem should be fixed too.
