### ISSUE TITLE
from="type label" where="label.id=:arg" fails

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#530]
**Reported by @cristianbogdan on 18 Sep 2007 08:29 UTC**
the typical makumba object identification which in OQL looks like 
     from="type label" where="label=$arg" 

fails in HQL in both these forms:
1)    from="type label" where="label.id=:arg"

I think the first one is the right form... It gives a binding problem, since hibernate expects an integer and we pass a string

ava.lang.ClassCastException: java.lang.String
	at org.hibernate.type.IntegerType.set(IntegerType.java:41)
	at org.hibernate.type.NullableType.nullSafeSet(NullableType.java:136)
	at org.hibernate.type.NullableType.nullSafeSet(NullableType.java:116)
	at org.hibernate.param.NamedParameterSpecification.bind(NamedParameterSpecification.java:38)
	at org.hibernate.loader.hql.QueryLoader.bindParameterValues(QueryLoader.java:491)

---------
2)          from="type label" where="label=:arg" 

org.hibernate.PropertyAccessException: IllegalArgumentException occurred calling getter of projman.Message.primaryKey
	at org.hibernate.property.BasicPropertyAccessor$BasicGetter.get(BasicPropertyAccessor.java:171)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.getIdentifier(AbstractEntityTuplizer.java:183)
	at org.hibernate.persister.entity.AbstractEntityPersister.getIdentifier(AbstractEntityPersister.java:3591)
	at org.hibernate.persister.entity.AbstractEntityPersister.isTransient(AbstractEntityPersister.java:3307)

Migrated-From: http://trac.makumba.org/ticket/982

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 26 Sep 2007 10:05 UTC**
ok, both forms work now (label.id=:param, label=param). actually i only fixed label.id but label seems to have been fixed as a collateral effect.

what was missing is parameter type analysis. for that, i needed to add a bit more type analysis overall, as we are not interested any more just in the projection types but in the types of all expressions... i left a number of FIXMEs as i only completed what i was interested in, i.e. pointer params.
