### ISSUE TITLE
Problems with query when label of same type is used several times

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#540]
**Reported by @rudolfmayer on 25 Oct 2007 14:43 UTC**
Makumba generates wrong OQL when the same type is used (manually) in a variableFrom and (automatically) in a nested list/value.

Using test.Person in the sample app (which has as most important property for this test 'speaks=set test.Language'), this fails (committed as webapps/test/testBug993.jsp to the makumba source)

<c:set var="searchArchiveVariableFrom" value="o.speaks speaks" />
<c:set var="searchArchiveWhere" value="speaks IN SET ($speaks)" />
<% pageContext.setAttribute("speaks", new Vector(Arrays.asList(new String[] {"3vyr0id", "5uzv2hj"})) ); %>

<mak:list from="test.Person o" variableFrom="#{searchArchiveVariableFrom}" where="#{searchArchiveWhere}">
  <mak:value expr="o.indiv.name" />:<mak:value expr="o.uniqPtr.name" />,<mak:value expr="o.speaks" /><br/>
</mak:list>

the error: 
java.lang.RuntimeException: nullable query with more than one result ??? 2
	at org.makumba.list.engine.valuecomputer.NullableValueComputer.getValue(NullableValueComputer.java:52)
	at org.makumba.list.engine.valuecomputer.ValueComputer.print(ValueComputer.java:178)
	at org.makumba.list.tags.ValueTag.doAnalyzedStartTag(ValueTag.java:115)
	at org.makumba.analyser.AnalysableTag.doStartTag(AnalysableTag.java:239)
	at org.makumba.commons.tags.GenericMakumbaTag.doStartTag(GenericMakumbaTag.java:48)
	at org.apache.jsp.testBug993_jsp._jspx_meth_mak_005fvalue_005f1(testBug993_jsp.java:203)
	at org.apache.jsp.testBug993_jsp._jspx_meth_mak_005flist_005f0(testBug993_jsp.java:156)

the queries produced are (OQL, then translated SQL)

SELECT o AS col1,o.indiv.name AS col2 FROM test.Person o,o.speaks speaks WHERE speaks IN SET ($2,$1)
SELECT  o.Person_  AS  col1 , oxx.name_  AS  col2 FROM test_Person__speaks_ ox,test_Individual_ oxx,test_Person_ o,test_Language_ speaks WHERE o.Person_= ox.Person_ AND ox.Language_= speaks.Language_ AND o.indiv_= oxx.Individual_ AND ( speaks.Language_ IN  ( 1 , 3 )) LIMIT 0, 2147483647

SELECT o AS col1,o.uniqPtr.name AS col2 FROM test.Person o,o.speaks speaks WHERE speaks IN SET ($2,$1)

SELECT  o.Person_  AS  col1 , oxx.name_  AS  col2 FROM test_Person__speaks_ ox,test_Language_ oxx,test_Person_ o,test_Language_ speaks WHERE o.Person_= ox.Person_ AND ox.Language_= speaks.Language_ AND o.uniqPtr_= oxx.Language_ AND ( speaks.Language_ IN  ( 1 , 3 )) LIMIT 0, 2147483647

SELECT o AS col1,o_speaks AS col2,o_speaks.name AS col3 FROM test.Person o,o.speaks o_speaks,o.speaks speaks WHERE speaks IN SET ($2,$1) ORDER BY col3

SELECT  o.Person_  AS  col1 , o_speaks.Language_  AS  col2 , o_speaks.name_  AS  col3 FROM test_Person__speaks_ ox,test_Person__speaks_ oxx,test_Language_ o_speaks,test_Person_ o,test_Language_ speaks WHERE o.Person_= ox.Person_ AND ox.Language_= o_speaks.Language_ AND o.Person_= oxx.Person_ AND oxx.Language_= speaks.Language_ AND ( speaks.Language_ IN  ( 1 , 3 )) ORDER BY col3 LIMIT 0, 2147483647

changing the indiv.uniqPtr.name to just indiv.uniq.Ptr works, cause it does not do the extra from part anymore. queries then are:

SELECT o AS col1,o.indiv.name AS col2,o.uniqPtr AS col3 FROM test.Person o,o.speaks speaks WHERE speaks IN SET ($2,$1)
SELECT  o.Person_  AS  col1 , oxx.name_  AS  col2 , o.uniqPtr_  AS  col3 FROM test_Person__speaks_ ox,test_Individual_ oxx,test_Person_ o,test_Language_ speaks WHERE o.Person_= ox.Person_ AND ox.Language_= speaks.Language_ AND o.indiv_= oxx.Individual_ AND ( speaks.Language_ IN  ( 1 , 3 )) LIMIT 0, 2147483647

SELECT o AS col1,o_speaks AS col2,o_speaks.name AS col3 FROM test.Person o,o.speaks o_speaks,o.speaks speaks WHERE speaks IN SET ($2,$1) ORDER BY col3
SELECT  o.Person_  AS  col1 , o_speaks.Language_  AS  col2 , o_speaks.name_  AS  col3 FROM test_Person__speaks_ ox,test_Person__speaks_ oxx,test_Language_ o_speaks,test_Person_ o,test_Language_ speaks WHERE o.Person_= ox.Person_ AND ox.Language_= o_speaks.Language_ AND o.Person_= oxx.Person_ AND oxx.Language_= speaks.Language_ AND ( speaks.Language_ IN  ( 1 , 3 )) ORDER BY col3 LIMIT 0, 2147483647

also, removing the variableFrom condition works.

the assumption here would be that the composed subquery should check if a label of that type is not already selected, and if so, don't add it any more.

Migrated-From: http://trac.makumba.org/ticket/993

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 25 Oct 2007 16:14 UTC**
Even if the query does not cause the problem mentioned in comment 0, the query seems to generate too many results by selecting the same type twice, e.g.

SELECT o AS col1,o_speaks AS col2,o_speaks.name AS col3 FROM test.Person o,o.speaks o_speaks,o.speaks o_speaks WHERE  ( o_speaks IN SET ($3,$2,$1) )  ORDER BY col3

tanslates to 
SELECT  o.Person_  AS  col1 , o_speaks.Language_  AS  col2 , o_speaks.name_  AS  col3 FROM test_Language_ o_speaksx,test_Person__speaks_ ox,test_Person__speaks_ oxx,test_Language_ o_speaks,test_Person_ o WHERE o.Person_= ox.Person_ AND ox.Language_= o_speaks.Language_ AND o.Person_= oxx.Person_ AND oxx.Language_= o_speaksx.Language_ AND ( ( o_speaks.Language_ IN  ( 1 , 3 , 2 ) )) ORDER BY col3 LIMIT 0, 2147483647

which generates duplicate entries.

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 26 Oct 2007 01:04 UTC**
maybe it's time to use left join and drop nullable value queries... they're actually a replacement of left join, are they not?

but it seems that there's some need for a DISTINCT somewhere (i guess duplicates are also the cause of the error at comment 0?)

this doesn't seem to be an oql problem; the queries are correct OQL and generate correct SQL, but seem to be wrong for the purpose, or?

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 26 Oct 2007 19:19 UTC**
One more problem is that in the generated query, mak:value from the sub-set has the correct count of elements, but all the sub sets have the same value.

e.g. one gets

Name   	Category  	 Minimum players  	 Maximum players  	 Duration  	 Materials   	  Date   	Details
As Little Feet as Possible 	Afterparty,Afterparty,Afterparty,Afterparty,Afterparty,Afterparty 	20 	40 	10 minutes 	

instead of 

Name   	Category  	 Minimum players  	 Maximum players  	 Duration  	 Materials   	  Date   	Details
As Little Feet as Possible 	Afterparty,Indoor,LBG Weekend,Physical Activity,Teambuilding,Welcome Party 	20 	40 	10 minutes 		07 November 2005 	Details

(see:
http://tequila.best.eu.org/rudi-k/games/search.jsp?nameMatch=contains&name=&minPlayers=&maxPlayers=&durationMatch=betweenInclusive&duration=&durationRangeEnd=&materials=&description=&category=bqpp5em&__makumba__responder__=294707848
vs.
http://tequila.best.eu.org/rudi-k/games/searchResults.jsp?name=&minPl=&maxPl=&minTime=&maxTime=&materials=&description=&category=bqpp5em&__makumba__originatingPage__=%2Frudi-k%2Fgames%2FgamesSearch.jsp&__makumba__responder__=1246407542 
)

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 14 Jan 2009 19:24 UTC**
is this still relevant with MQL?

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 27 Jun 2010 13:16 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 21 Mar 2013 23:50 UTC**
testBug993.jsp works, but the query is wrong, should be 

<c:set var="searchArchiveWhere" value="exists(FROM o.speaks s WHERE s IN SET ($speaks))" />

and no variable From is needed

in the original form, the results are repeated as indicated in subsequent comments
