### ISSUE TITLE
NoClassDefFoundError not displayed correctly in browser

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#550]
**Reported by @manuelbernhardt on 22 Nov 2007 16:47 UTC**
when a NoClassDefFoundError is thrown (e.g. because a JAR file is missing in the classpath), instead of getting the cause in the browser, the result is like:

type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Filter execution threw an exception
	org.eu.best.tools.SessionDomainFilter.doFilter(Unknown Source)
	org.eu.best.tools.WelcomeFilter.doFilter(Unknown Source)
	org.eu.best.tools.UriRewriteFilter.doFilter(Unknown Source)
	org.eu.best.tools.VHostFilter.doFilter(Unknown Source)
	org.eu.best.tools.TriggerFilter.doFilter(TriggerFilter.java:58)

root cause

org.makumba.MakumbaError: javax.servlet.ServletException: Invoker service() exception
	org.makumba.devel.ErrorControllerHandler.treatException(ErrorControllerHandler.java:97)
	org.makumba.devel.ErrorControllerHandler.onError(ErrorControllerHandler.java:49)
	org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:97)
	org.eu.best.tools.SessionDomainFilter.doFilter(Unknown Source)
	org.eu.best.tools.WelcomeFilter.doFilter(Unknown Source)
	org.eu.best.tools.UriRewriteFilter.doFilter(Unknown Source)
	org.eu.best.tools.VHostFilter.doFilter(Unknown Source)
	org.eu.best.tools.TriggerFilter.doFilter(TriggerFilter.java:58)

the full stacktrace in the logs is more descriptive. it would be good to identify the root cause directly.

full trace in logs:

manuel@demo-new-k: java.lang.NoClassDefFoundError: org/apache/commons/collections/map/MultiValueMap
manuel@demo-new-k:      at org.makumba.CompositeValidationException.<init>(CompositeValidationException.java:42)
manuel@demo-new-k:      at org.makumba.db.makumba.sql.TableManager.checkMultiFieldMultiTableUniqueness(TableManager.java:2057)
manuel@demo-new-k:      at org.makumba.db.makumba.sql.TableManager.checkInsert(TableManager.java:2002)
manuel@demo-new-k:      at org.makumba.db.makumba.MakumbaCRUDOperationProvider.checkInsert(MakumbaCRUDOperationProvider.java:28)
manuel@demo-new-k:      at org.makumba.db.DataHolder.checkInsert(DataHolder.java:142)
manuel@demo-new-k:      at org.makumba.db.TransactionImplementation.insert(TransactionImplementation.java:112)
manuel@demo-new-k:      at org.makumba.db.makumba.DBConnection.insert(DBConnection.java:160)
manuel@demo-new-k:      at org.makumba.db.makumba.DBConnectionWrapper.insert(DBConnectionWrapper.java:81)
manuel@demo-new-k:      at org.makumba.devel.ErrorFormatter.logError(ErrorFormatter.java:193)
manuel@demo-new-k:      at org.makumba.devel.ErrorFormatter.<init>(ErrorFormatter.java:106)
manuel@demo-new-k:      at org.makumba.devel.TagExceptionServlet.service(TagExceptionServlet.java:51)
manuel@demo-new-k:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
manuel@demo-new-k:      at org.apache.catalina.servlets.InvokerServlet.serveRequest(InvokerServlet.java:419)
manuel@demo-new-k:      at org.apache.catalina.servlets.InvokerServlet.doPost(InvokerServlet.java:169)
manuel@demo-new-k:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:709)
manuel@demo-new-k:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:704)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:474)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:409)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
manuel@demo-new-k:      at org.makumba.devel.ErrorControllerHandler.treatException(ErrorControllerHandler.java:89)
manuel@demo-new-k:      at org.makumba.devel.ErrorControllerHandler.onError(ErrorControllerHandler.java:49)
manuel@demo-new-k:      at org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:97)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.SessionDomainFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.WelcomeFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.UriRewriteFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.VHostFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.TriggerFilter.doFilter(TriggerFilter.java:58)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:214)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.StandardContextValve.invokeInternal(StandardContextValve.java:198)
manuel@demo-new-k:      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:152)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:118)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:929)
manuel@demo-new-k:      at org.apache.coyote.tomcat5.CoyoteAdapter.service(CoyoteAdapter.java:160)
manuel@demo-new-k:      at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:799)
manuel@demo-new-k:      at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:705)
manuel@demo-new-k:      at org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:577)
manuel@demo-new-k:      at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:683)
manuel@demo-new-k:      at java.lang.Thread.run(Thread.java:619)
manuel@demo-new-k:
manuel@demo-new-k: javax.servlet.ServletException: Invoker service() exception
manuel@demo-new-k:      at org.apache.catalina.servlets.InvokerServlet.serveRequest(InvokerServlet.java:477)
manuel@demo-new-k:      at org.apache.catalina.servlets.InvokerServlet.doPost(InvokerServlet.java:169)
manuel@demo-new-k:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:709)
manuel@demo-new-k:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:704)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:474)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:409)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
manuel@demo-new-k:      at org.makumba.devel.ErrorControllerHandler.treatException(ErrorControllerHandler.java:89)
manuel@demo-new-k:      at org.makumba.devel.ErrorControllerHandler.onError(ErrorControllerHandler.java:49)
manuel@demo-new-k:      at org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:97)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.SessionDomainFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.WelcomeFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.UriRewriteFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.VHostFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.TriggerFilter.doFilter(TriggerFilter.java:58)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:214)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.StandardContextValve.invokeInternal(StandardContextValve.java:198)
manuel@demo-new-k:      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:152)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:118)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:929)
manuel@demo-new-k:      at org.apache.coyote.tomcat5.CoyoteAdapter.service(CoyoteAdapter.java:160)
manuel@demo-new-k:      at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:799)
manuel@demo-new-k:      at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:705)
manuel@demo-new-k:      at org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:577)
manuel@demo-new-k:      at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:683)
manuel@demo-new-k:      at java.lang.Thread.run(Thread.java:619)
manuel@demo-new-k: StandardWrapperValve[jsp]: Servlet.service() for servlet jsp threw exception
manuel@demo-new-k: org.makumba.MakumbaError: javax.servlet.ServletException: Invoker service() exception
manuel@demo-new-k:      at org.makumba.devel.ErrorControllerHandler.treatException(ErrorControllerHandler.java:97)
manuel@demo-new-k:      at org.makumba.devel.ErrorControllerHandler.onError(ErrorControllerHandler.java:49)
manuel@demo-new-k:      at org.makumba.controller.http.ControllerFilter.doFilter(ControllerFilter.java:97)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.SessionDomainFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.WelcomeFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.UriRewriteFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.VHostFilter.doFilter(Unknown Source)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.eu.best.tools.TriggerFilter.doFilter(TriggerFilter.java:58)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:186)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:214)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.StandardContextValve.invokeInternal(StandardContextValve.java:198)
manuel@demo-new-k:      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:152)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:118)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:102)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
manuel@demo-new-k:      at org.apache.catalina.core.StandardValveContext.invokeNext(StandardValveContext.java:104)
manuel@demo-new-k:      at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:520)
manuel@demo-new-k:      at org.apache.catalina.core.ContainerBase.invoke(ContainerBase.java:929)
manuel@demo-new-k:      at org.apache.coyote.tomcat5.CoyoteAdapter.service(CoyoteAdapter.java:160)
manuel@demo-new-k:      at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:799)
manuel@demo-new-k:      at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.processConnection(Http11Protocol.java:705)
manuel@demo-new-k:      at org.apache.tomcat.util.net.TcpWorkerThread.runIt(PoolTcpEndpoint.java:577)
manuel@demo-new-k:      at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:683)
manuel@demo-new-k:      at java.lang.Thread.run(Thread.java:619)
manuel@demo-new-k: Caused by: javax.servlet.ServletException: Invoker service() exception
manuel@demo-new-k:      at org.apache.catalina.servlets.InvokerServlet.serveRequest(InvokerServlet.java:477)
manuel@demo-new-k:      at org.apache.catalina.servlets.InvokerServlet.doPost(InvokerServlet.java:169)
manuel@demo-new-k:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:709)
manuel@demo-new-k:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:237)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:157)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:704)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:474)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:409)
manuel@demo-new-k:      at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
manuel@demo-new-k:      at org.makumba.devel.ErrorControllerHandler.treatException(ErrorControllerHandler.java:89)
manuel@demo-new-k:      ... 41 more
manuel@demo-new-k:

Migrated-From: http://trac.makumba.org/ticket/1004

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 1 Jul 2010 13:48 UTC**
