### ISSUE TITLE
reserved keyword error messages are displayed several times and not very descriptive

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#551]
**Reported by @manuelbernhardt on 22 Nov 2007 16:52 UTC**
when a reserved keyword is used in a MDD (or used in a query?), a Makumba query error is shown:

Makumba query error
/home/projects/parade/demo-new/karamba/public_html

While executing page /welcome.jsp

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

 
in query:
SELECT bis.student.authentication.karamba_username as karambaUsername, bis as bis, bis.paTheme as paTheme, bis.welcomePageView as welcomePageView, bis.personalProfileView as personalProfileView, bis.isAlumnus as isAlumnus, bis.actuallogin as actuallogin, student as student, student.hasBAS AS hasBAS, student.hasBCC AS hasBCC, student.hasPA AS hasPA, person as person, person.name as personName, person.surname as personSurname, lbg as lbg, lbg.name as lbgName, lbg.id as lbgId, lbg.guideRights as guideRights, university as university FROM best.internal.Student bis, bis.student student, student.person person, bis.lbg lbg, lbg.university university WHERE (bis.student.authentication.n_username=$3 OR bis.student.authentication.username=$3 OR bis.student.authentication.shortname=$3 OR bis.student.person.surname=$1 OR bis.student.person.name=$1 OR bis.student.authentication.karamba_username=$3) AND bis.student.authentication.password=$2 AND bis.account_active<>0

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

 
in query:
SELECT bis.student.authentication.karamba_username as karambaUsername, bis as bis, bis.paTheme as paTheme, bis.welcomePageView as welcomePageView, bis.personalProfileView as personalProfileView, bis.isAlumnus as isAlumnus, bis.actuallogin as actuallogin, student as student, student.hasBAS AS hasBAS, student.hasBCC AS hasBCC, student.hasPA AS hasPA, person as person, person.name as personName, person.surname as personSurname, lbg as lbg, lbg.name as lbgName, lbg.id as lbgId, lbg.guideRights as guideRights, university as university FROM best.internal.Student bis, bis.student student, student.person person, bis.lbg lbg, lbg.university university WHERE (bis.student.authentication.n_username=$3 OR bis.student.authentication.username=$3 OR bis.student.authentication.shortname=$3 OR bis.student.person.surname=$1 OR bis.student.person.name=$1 OR bis.student.authentication.karamba_username=$3) AND bis.student.authentication.password=$2 AND bis.account_active<>0
org.makumba.OQLParseError:  

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

general.Topic:Error: field name cannot be one of the reserved keywords count, for, char, package, long, float, distinct, break, byte, import, boolean, avg, else, volatile, final, static, synchronized, extends, int, throws, transient, class, enum, double, default, native, instanceof, case, this, try, const, catch, sum, switch, goto, finally, while, private, short, super, throw, protected, order, if, do, strictfp, abstract, return, void, interface, new, continue, implements, assert, group, public
super
     ^

	at org.makumba.providers.query.oql.OQLQueryAnalysisProvider.getQueryAnalysis(OQLQueryAnalysisProvider.java:33)
	at org.makumba.db.makumba.sql.Query.<init>(Query.java:84)
	at org.makumba.db.makumba.sql.Database.prepareQueryImpl(Database.java:281)
	at org.makumba.db.makumba.Database$2.makeResource(Database.java:239)
	at org.makumba.commons.NamedResourceFactory.makeResource(NamedResourceFactory.java:79)
	at org.makumba.commons.ProducerReturner.getRes(NameValue.java:70)
	at org.makumba.commons.NameValue.getResource(NameValue.java:53)
	at org.makumba.commons.NamedResources.getResource(NamedResources.java:192)
	at org.makumba.db.makumba.DBConnection.executeQuery(DBConnection.java:195)
	at org.makumba.db.makumba.DBConnectionWrapper.executeQuery(DBConnectionWrapper.java:77)
	at org.makumba.db.makumba.DBConnection.executeQuery(DBConnection.java:215)
	at org.eu.best.general.AccessControlLogic.find_sessPtr_BestInternalStudent(Unknown Source)
	

instead of this iterative message with a stacktrace at the end, it would be more appropriate to display the error message only once and pin-point the exact origin (part of query, or part of the MDD)

Migrated-From: http://trac.makumba.org/ticket/1005

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 1 Jul 2010 13:49 UTC**

**Comment by ghost** [comment]
**Modified by @cristianbogdan on 4 Apr 2016 13:03 UTC**
