### ISSUE TITLE
Null pointer exception when using forceInputStyle="multiple" in search forms

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#648]
**Reported by orel on 23 Aug 2009 09:52 UTC**
# Makumba version: 0.8.1.9.1

Hi,

when selecting several items from a field using the forceInputStyle="multiple" option, you get this kind of error:

Invalid value for Form responder#col6: Only java.lang.String and org.makumba.Pointer (or a java.util.Vector containing elements of those types) are assignable to makumba pointers, given value <[6znfn3t, 8wqmje7, 8wqmje4, avrqld9, 8wqmje2, avrqld7, avrqld4, avrqlct](6xpihf2,)> is of type java.util.Vector

In case of troubles, please go to our Helpdesk, copy the following error message and tell what you were trying to do when you encountered this error.

While executing page http://parade.best.eu.org/trainees-k/website/company/private/cvSearch.jsp

Please report to the developers.

java.lang.NullPointerException
	at org.makumba.forms.responder.ResponseControllerHandler$2.getServletPath(ResponseControllerHandler.java:123)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:239)
	

Makumba developer support, version: 0.8.1.9.1; using database localhost_mysql_TESTkaramba

If you select only 1 item, the search is done correctly.

Migrated-From: http://trac.makumba.org/ticket/1103

**Comment by ghost** [comment]
**Modified by @rudolfmayer on 27 Apr 2010 22:53 UTC**

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 27 Apr 2010 22:54 UTC**
This should be fixed by http://makumba.svn.sourceforge.net/makumba/?rev=4871&view=rev; a new makumba release still has to be made
