### ISSUE TITLE
<mak:input ... value="$attr"> fails if attr is computed via <mak:value var="attr" />

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#655]
**Reported by @gwenael-alizon on 8 Oct 2009 21:09 UTC**
[Cristi]
code:

<mak:object ...>
<mak:value expr="Ex" var="x" />
<mak:newForm ....>
   <mak:input ... value="$x" />
</mak:form>
</mak:object>

will fail with the stacktrace below. sorry i can't make a proper test
case now simply because i spent huge amounts of time finding a solution
for this, as i found a number of other bugs in the process (see mails to
come) and i think it's more valuable to report these.

You might wonder why I don't do directly <mak:input ... value="Ex" />. I
need to do it like this because I only want the respective value in
certain conditions, that is:

<c:if test=...>
   <c:set var="x">something else</c:set>
</c:if>
<mak:input ... value="$x" />

the workaround i could find is to copy the attribute into another

<c:if test="Test">
<c:set var="x1">something else</c:set>
</c:if>
<c:if test="not Test">
<%pageContext.setAttribute("x1", pageContext.getAttribute("x")); %>
<%-- btw can the above be done with c:set? --%>
</c:if>
<mak:input ... value="$x1" />

The stacktrace is below

Please report to the developers.
java.lang.ClassCastException: [Ljava.lang.Object;

Stacktrace:
       at
org.makumba.forms.tags.BasicValueTag.doEndAnalyze(BasicValueTag.java:164)
       at org.makumba.forms.tags.InputTag.doEndAnalyze(InputTag.java:239)
       at org.makumba.commons.ParseStatus.endPage(ParseStatus.java:223)
       at
org.makumba.commons.MakumbaJspAnalyzer.endPage(MakumbaJspAnalyzer.java:310)
       at org.makumba.analyser.engine.JspParseData.parse(JspParseData.java:238)
       at
org.makumba.analyser.engine.JspParseData.getSyntaxPointArray(JspParseData.java:167)
       at
org.makumba.analyser.engine.JspParseData.getAnalysisResult(JspParseData.java:155)
       at org.makumba.analyser.AnalysableTag.getPageCache(AnalysableTag.java:111)
       at org.makumba.analyser.AnalysableTag.doStartTag(AnalysableTag.java:265)
       at
org.makumba.commons.tags.GenericMakumbaTag.doStartTag(GenericMakumbaTag.java:44)
       at org.apache.jsp.admin.request.test_jsp._jspService(test_jsp.java:70)
       at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:98)

Migrated-From: http://trac.makumba.org/ticket/1110

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 8 Oct 2009 21:11 UTC**
[Cristi]
To be fair, this also works:

<c:if test="Test">
<mak:input ... value="something else" />
</c:if>
<c:if test="not Test">
<mak:input ... value="Ex" />
</c:if>
(i.e. use only expressions, no $attr stuff)

but this bug prevented me from investigating this solution earlier as I
tried value="$x" first and then ran into this bug which was damn hard to
isolate.

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 8 Oct 2009 21:13 UTC**
[Rudi]
ok, the code is

    if (isAttribute())
        type = (FieldDefinition) pageCache.retrieve(AnalysableTag.TYPES, expr.substring(1));

and from the exception, it seems that we get an object for the pageCache.retrieve
=> that would suggest that something goes seriously wrong when creating the cache...

**Comment by ghost** [comment]
**Comment by @gwenael-alizon on 8 Oct 2009 21:16 UTC**
[i debugged for 3 min and indeed there is a Object[](Cristi]
yes) in the cache. it
contains a FieldDefinition and (i think) the correct value

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:24 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**
