### ISSUE TITLE
NullPointerException on mak:delete

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#658]
**Reported by kristian liibert on 17 Oct 2009 19:52 UTC**
Using makumba version  devel-20090217213509 (0.8.2.1 from sourceforge). 

Whenever I write a <mak:delete tag in the page executing the page fails and i get an error:

Please report to the developers.

java.lang.NullPointerException: null

Exception in JSP: /p/admin.jsp:7

4: <mak:version/>
5: 
6: <mak:list from="sec.Test k">
7: <mak:value expr="k.vali1" /> | <mak:value expr="k.vali2" /> - <mak:delete object="k" action="admin.jsp">DELETE</mak:delete>  <br />
8: </mak:list><br/>
9: <div class="addbox">
10:

Stacktrace:
	at org.makumba.forms.tags.FormTagBase.setBodyContent(FormTagBase.java:140)
	at org.apache.jsp.p.admin_jsp._jspx_meth_mak_005fdelete_005f0(admin_jsp.java:239)
	at org.apache.jsp.p.admin_jsp._jspx_meth_mak_005flist_005f0(admin_jsp.java:173)
	at org.apache.jsp.p.admin_jsp._jspService(admin_jsp.java:75)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:98)

Also occurrs whith mak:object.

It doesn't matter if I try to delete a object that is in realtion with other tables or not it still gives the same error.

I also tested on 2 machines and produced similar errors.

Migrated-From: http://trac.makumba.org/ticket/1113

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 25 Jun 2010 07:32 UTC**
works on trunk, probably also in 0.8.2.4
