### ISSUE TITLE
NPE in HttpParameters:17

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#70]
**Reported by @cristianbogdan on 28 Oct 2002 17:29 UTC**
http://18080.makumba.org/0.5.4-test-k/johnny/lbg/seasonView.jsp?season=summer02
produces

java.lang.NullPointerException
	at org.makumba.view.jsptaglib.HttpParameters.getParameter(HttpParameters.java:17)
	at org.makumba.view.jsptaglib.HttpAttributes.getAttribute(HttpAttributes.java:112)
	at
org.makumba.view.MultipleAttributeParametrizer$1.getHashObject(MultipleAttributeParametrizer.java:62)
	at org.makumba.util.NamedResources.getResource(NamedResources.java:34)
	at
org.makumba.view.MultipleAttributeParametrizer.getAttributeParametrizer(MultipleAttributeParametrizer.java:41)
	at
org.makumba.view.MultipleAttributeParametrizer.<init>(MultipleAttributeParametrizer.java:33)
	at org.makumba.view.ComposedQuery.prepare(ComposedQuery.java:316)
	at org.makumba.view.ComposedQuery.execute(ComposedQuery.java:301)
	at org.makumba.view.jsptaglib.QueryStrategy.doQuery(QueryStrategy.java:418)
	at
org.makumba.view.jsptaglib.RootQueryStrategy.doQueries(RootQueryStrategy.java:134)
	at org.makumba.view.jsptaglib.QueryStrategy.doRootAfter(QueryStrategy.java:164)
	at org.makumba.view.jsptaglib.RootQueryStrategy.doAfter(RootQueryStrategy.java:85)
	at org.makumba.view.jsptaglib.MakumbaBodyTag.doAfterBody(MakumbaBodyTag.java:34)
	at org.apache.jsp.seasonView$jsp._jspService(seasonView$jsp.java:340)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:107)

Migrated-From: http://trac.makumba.org/ticket/78

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 28 Oct 2002 19:00 UTC**
fixed in 0.5.4.1
i had forgotten to join the latest developments in the main trunk
(0.5.3.35->05.3.36)
