### ISSUE TITLE
text type doesn't work with HSQLDB

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#720]
**Reported by @manuelbernhardt on 8 Mar 2010 23:23 UTC**
using the text type in a HSQLDB-based setup as the one generated by the maven archetype yields following stacktrace:

The problem is related to SQL:
    SQLstate: 22003
  ErrorCode: -95
     Message: Type Conversion not supported

Refer to your SQL server's documentation for error explanation.
Please check the configuration of your webapp and SQL server.
Please report to the developers.
java.sql.SQLException: Type Conversion not supported
	at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
	at org.hsqldb.jdbc.jdbcPreparedStatement.setParameter(Unknown Source)
	at org.hsqldb.jdbc.jdbcPreparedStatement.setString(Unknown Source)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setString(NewProxyPreparedStatement.java:963)
	at org.makumba.db.makumba.sql.TableManager.set_text_Argument(TableManager.java:1097)
	at org.makumba.db.makumba.sql.TableManager.setArgument(TableManager.java:1081)
	at org.makumba.db.makumba.sql.TableManager.base_setInsertArgument(TableManager.java:1408)
	at org.makumba.db.makumba.sql.TableManager.setInsertArgument(TableManager.java:1397)
	at org.makumba.db.makumba.sql.TableManager.insertRecordImpl(TableManager.java:654)
	at org.makumba.db.makumba.Table.insertRecord(Table.java:258)
	at org.makumba.db.makumba.MakumbaCRUDOperationProvider.insert(MakumbaCRUDOperationProvider.java:22)
	at org.makumba.db.DataHolder.insert(DataHolder.java:174)
	at org.makumba.db.TransactionImplementation.insert(TransactionImplementation.java:157)
	at org.makumba.db.makumba.DBConnection.insert(DBConnection.java:159)
	at org.makumba.db.makumba.DBConnectionWrapper.insert(DBConnectionWrapper.java:83)

most likely, the HSQLDB type for text needs to be adjusted in the driver configuration.

Migrated-From: http://trac.makumba.org/ticket/1175

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 8 Mar 2010 23:32 UTC**
after some googling this thread seems to be quite sensible:

https://forum.hibernate.org/viewtopic.php?f=1&t=993020&view=next

at least, it tells that we should make sure strings are escaped. I will make a test-case and see if that is the case.

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:22 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:24 UTC**

**Comment by ghost** [comment]
**Modified by @manuelbernhardt on 28 Jun 2010 07:36 UTC**
