### ISSUE TITLE
MQL Parser doesn't accept simple form of case-when statements.

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#723]
**Reported by @rudolfmayer on 8 Apr 2010 10:59 UTC**
The following works for the MQL parser (in test.Person in the makumba project)

scoreMatch(char term, char value) { case when value=term then 1.0 else case when value like concat(term, '%') then 0.8 else case when value like concat('%', term) then 0.6 else case when value like concat('%', term, '%') then 0.5 else 0 end end end end }

i.e. using the case-when as a simple if-else

however, at least in mysql, the case-when is also usable as a kind-of switch statement, and the following should work:

scoreMatchSimple(char term, char value) { case when value=term then 1.0 when value like concat(term, '%') then 0.8 when value like concat('%', term) then 0.6 when value like concat('%', term, '%') then 0.5 else 0 end }

at least, the corresponding SQL works:
select px.name_, case when px.name_='a' then 1.0 when px.name_ like concat('a', '%') then 0.8 when px.name_ like concat('%', 'a') then 0.6 when px.name_ like concat('%', 'a', '%') then 0.5 else 0 end from test_Person_ p JOIN test_Individual_ px ON p.indiv_= px.Individual_;

The exception provided is:

no type set for projection col2  ( case ( when ( = ( px.name_ ( p.indiv_ p.Person_ indiv ) name ) 'a' ) 1.0 ) ( when ( like ( px.name_ ( p.indiv_ p.Person_ indiv ) name ) ( ( concat ( exprList 'a' '%' ) ) ) 0.8 ) ( when ( like ( px.name_ ( p.indiv_ p.Person_ indiv ) name ) ( ( concat ( exprList '%' 'a' ) ) ) 0.6 ) ( when ( like ( px.name_ ( p.indiv_ p.Person_ indiv ) name ) ( ( concat ( exprList '%' 'a' '%' ) ) ) 0.5 ) ( else 0 ) )
	at org.makumba.providers.query.mql.MqlSqlWalker.setProjectionTypes(MqlSqlWalker.java:473)
	at org.makumba.providers.query.mql.MqlQueryAnalysis.init(MqlQueryAnalysis.java:141)
	at org.makumba.providers.query.mql.MqlQueryAnalysis.<init>(MqlQueryAnalysis.java:118)
	at org.makumba.providers.query.mql.MqlQueryAnalysisProvider$1.makeResource(MqlQueryAnalysisProvider.java:21)

Migrated-From: http://trac.makumba.org/ticket/1178

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 27 Apr 2010 10:26 UTC**
this was probably fixed by allowing more complex grammars in case-when

the test function works now.

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 27 Apr 2010 10:40 UTC**
(In reply to comment #1)
> this was probably fixed by allowing more complex grammars in case-when


it was fixed when fixing the type analysis. previously, it operated on the "ELSE" part, and set the type of the THEN to that of the ELSE. as in this case there was no ELSE, it didn't work.
We changed this to work on the THEN part in http://makumba.svn.sourceforge.net/makumba/?rev=4755&view=rev
