### ISSUE TITLE
DB update causes OQLParseError

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#73]
**Reported by @stefanb on 29 Oct 2002 14:22 UTC**
editing personal info with makumba 0.5.3.35 on
http://mlk18080.makumba.org/demo-k/lbg/member/memberView.jsp?person=bkesswj
works perfectly,
but with makumba 0.5.4.1 on
http://mlk18080.makumba.org/0.5.4-test-k/lbg/member/memberView.jsp?person=bk
esswj
throws:

Internal Makumba error
Please report to the developers
org.makumba.OQLParseError: expecting "from", found '.'
in update on type: <general.Person this> setting:
<this.specialDiet=$2this.allergies=$3,this.birthdate=$4,this.citizenship=$5,
this.icq=$6,this.webpage=$7,this.email=$8,this.gender=$9,this.passportno=$10
,this.T_shirt=$11,> where: <this.Person=$1>
SELECT
this.specialDiet=$2this.allergies=$3,this.birthdate=$4,this.citizenship=$5,t
his.icq=$6,this.webpage=$7,this.email=$8,this.gender=$9,this.passportno=$10,
this.T_shirt=$11, FROM general.Person this WHERE this.Person=$1
at org.makumba.db.sql.SQLUpdate.<init>(SQLUpdate.java:47)
at org.makumba.db.sql.Database.prepareUpdateImpl(Database.java:153)
at org.makumba.db.DBConnection$2.makeResource(DBConnection.java:149)
at
org.makumba.util.NamedResourceFactory.makeResource(NamedResourceFactory.java
:36)
at org.makumba.util.ProducerReturner.getRes(NamedResources.java:87)
at org.makumba.util.NameValue.getResource(NamedResources.java:73)
at org.makumba.util.NamedResources.getResource(NamedResources.java:44)
at org.makumba.db.DBConnection.executeUpdate(DBConnection.java:141)
at org.makumba.db.DataHolder.update(DBConnection.java:423)
at org.makumba.db.DataHolder.update(DBConnection.java:402)
at org.makumba.db.DataHolder.update(DBConnection.java:402)
at org.makumba.db.DBConnection.update(DBConnection.java:27)

which looks like a DBConnection.update() finally generates a weird and
invalid query to be sent further.

Migrated-From: http://trac.makumba.org/ticket/82

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 29 Oct 2002 23:20 UTC**
a small bug (missing comma) in new code. fixed in 0.5.4.2

**Comment by ghost** [comment]
**Comment by @stefanb on 30 Oct 2002 03:25 UTC**
tested again in the same environment with makumba 0.5.4.2 and WORKS!
