### ISSUE TITLE
Tests should also be run on HSQLDB

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#745]
**Reported by @rudolfmayer on 27 Apr 2010 13:19 UTC**
The currently available tests should not run only on MySQL, to enforce at least partially that the features we develop are a bit SQL-engine independent.

In a first step, we should always have them run on HSQLDB, as we ship e.g. the maven project with that database, and it would be a pitty if features don't work there..

Most likely this implies
- running the test webapp with a different Makumba.conf
- or somehow altering the content of the Configuration object to have a DB source pointing to a HSQLDB location

Migrated-From: http://trac.makumba.org/ticket/1200

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 14 May 2010 22:30 UTC**
i prepared scaffolding for this and the table test already runs (some not-so-important tests fail)

ant test.hsqldb will make the hsqldb datasource be default in tests/WEB-INF/classes/Makumba.conf, then run the table test

however, the jsp tests are a different story because they require two processes to use the same hsqldb database. currently the datasource uses this URL
jdbc:hsqldb:hsqldata/makumba

but we would need a localhost-like URL and start a hsqldb server, according to

http://hsqldb.org/doc/guide/guide.html#N10148

i tried but any attempt led to the error below, and then the who le process hangs. 

before i fixed the setup data so it uses hsqldb, i happened to run the test client with mysql and test server with hsqldb. of course a lot of things failed, but for the rest it was pretty hopeful, in the sense that hsqldb only complained about 2-3 CASE WHEN queries.

so it would be nice to crack this hsqldb server business, cause then we are "done" in that we have another db to test with. then we can maybe set some more advanced tests as "known to fail" (or disabled) when running with hsql.  

     [VARNING: An Exception occurred while registering/reregistering mbean com.mchange.v2.c3p0:type=PooledDataSource[1hge0xz8816ckg411ef83pq|7eb05acd](java]). MBean may not be registered, or may not work properly.
     [java.security.AccessControlException: access denied (javax.management.MBeanTrustPermission register)
     [java](java]) 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:323)
     [	at java.lang.SecurityManager.checkPermission(SecurityManager.java:568)
     [java](java]) 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1824)
     [	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:310)
     [java](java]) 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:482)
     [	at com.mchange.v2.c3p0.management.DynamicPooledDataSourceManagerMBean.reinitialize(DynamicPooledDataSourceManagerMBean.java:233)
     [java](java]) 	at com.mchange.v2.c3p0.management.DynamicPooledDataSourceManagerMBean.<init>(DynamicPooledDataSourceManagerMBean.java:158)
     [	at com.mchange.v2.c3p0.management.ActiveManagementCoordinator.attemptManagePooledDataSource(ActiveManagementCoordinator.java:110)
     [java](java]) 	at com.mchange.v2.c3p0.C3P0Registry.incorporate(C3P0Registry.java:233)
     [	at com.mchange.v2.c3p0.C3P0Registry.reregister(C3P0Registry.java:251)
     [java](java]) 	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.<init>(PoolBackedDataSourceBase.java:228)
     [	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.<init>(AbstractPoolBackedDataSource.java:62)
     [java](java]) 	at com.mchange.v2.c3p0.ComboPooledDataSource.<init>(ComboPooledDataSource.java:108)
     [	at com.mchange.v2.c3p0.ComboPooledDataSource.<init>(ComboPooledDataSource.java:104)
     [java](java]) 	at org.makumba.db.makumba.sql.Database.<init>(Database.java:215)
     [	at org.makumba.db.makumba.sql.HsqldbDatabase.<init>(HsqldbDatabase.java:48)
     [java](java]) 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
     [java](java]) 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
     [	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
     [java](java]) 	at org.makumba.db.makumba.MakumbaTransactionProvider$1.makeResource(MakumbaTransactionProvider.java:212)
     [	at org.makumba.commons.NamedResourceFactory.makeResource(NamedResourceFactory.java:81)
     [java](java]) 	at org.makumba.commons.ProducerReturner.getRes(NameValue.java:70)
     [	at org.makumba.commons.NameValue.getResource(NameValue.java:53)
     [java](java]) 	at org.makumba.commons.NamedResources.getResource(NamedResources.java:260)
     [	at org.makumba.db.makumba.MakumbaTransactionProvider.getDatabase(MakumbaTransactionProvider.java:122)
     [java](java]) 	at org.makumba.db.makumba.MakumbaTransactionProvider.getTransaction(MakumbaTransactionProvider.java:282)
     [	at org.makumba.providers.TransactionProvider.getConnectionTo(TransactionProvider.java:88)
     [java](java]) 	at org.makumba.db.makumba.MakumbaTransactionProvider.getConnectionTo(MakumbaTransactionProvider.java:230)
     [java] 	at test.table.setUp(table.java:70)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 15 May 2010 11:48 UTC**
this is working now

to prepare the hsqldb server
- ant hsqldb.cleandb
- ant hsqldb.server

to stop it
- hsqldb.stop

in eclipse: 
- set testHsqldb as default data source
- run the tests you want to run
- set the default data source back..


in ant, the above is done by 
ant test.hsqldb
it will run list-oql, form-oql, table

many tests fail but that's another topic. will file some bugs or fix them
