### ISSUE TITLE
MakumbaJspFactory fails with jetty 7.0.0.pre5

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#792]
**Reported by @manuelbernhardt on 10 Jul 2010 19:30 UTC**
makumba fails with following stacktrace:

```
java.lang.NullPointerException
	at org.makumba.controller.http.MakumbaJspFactory.getPageContext(MakumbaJspFactory.java:139)
	at org.makumba.list.tags.QueryTag.setNumberOfIterations(QueryTag.java:471)
	at org.makumba.list.tags.QueryTag.doTagExecution(QueryTag.java:366)
	at org.makumba.list.tags.QueryTag.doAnalyzedStartTag(QueryTag.java:313)
	at org.makumba.analyser.AnalysableTag.doStartTag(AnalysableTag.java:225)
	at org.makumba.commons.tags.GenericMakumbaTag.doStartTag(GenericMakumbaTag.java:47)
	at org.apache.jsp.index_jsp._jspx_meth_mak_list_0(org.apache.jsp.index_jsp:206)
	at org.apache.jsp.index_jsp._jspService(org.apache.jsp.index_jsp:79)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:389)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:365)
	at org.mortbay.jetty.security.ConstraintsSecurityHandler.handle(ConstraintsSecurityHandler.java:220)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:822)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:305)
	at org.mortbay.jetty.Dispatcher.forward(Dispatcher.java:345)
	at org.mortbay.jetty.Dispatcher.forward(Dispatcher.java:137)
	at org.mortbay.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:472)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:693)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:502)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:365)
	at org.mortbay.jetty.security.ConstraintsSecurityHandler.handle(ConstraintsSecurityHandler.java:220)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:822)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:305)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:229)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:113)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:324)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:550)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:876)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:535)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:209)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:407)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:421)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:520)
```

how to reproduce:
 * follow the instructions for creating a new project on http://www.makumba.org/page/QuickStart
 * create a new maven build (similar to the tomcat one) and choose as goal ```org.mortbay.jetty:jetty-maven-plugin:run```

we really should aim at fixing this for 1.0 since jetty is a wildly spread servlet container used a lot during development (and is the only viable option for developing rapidly in eclipse with maven & without WTP)

Migrated-From: http://trac.makumba.org/ticket/1247

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 11 Jul 2010 15:22 UTC**
the issue is that jetty does not load the controller filter without explicit mapping of 

```
<dispatcher>REQUEST</dispatcher>
<dispatcher>FORWARD</dispatcher>
```

in each ```<filter-mapping>``` element.

this is now done so in the makumba archetype and documented on the site.

however a better warning than a NPE is necessary.

**Comment by ghost** [comment]
**Comment by @manuelbernhardt on 11 Jul 2010 15:44 UTC**
ConfigurationException now thrown instead of NPE
