### ISSUE TITLE
Comparison validation with two fields and pointed types

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#799]
**Reported by @rudolfmayer on 29 Sep 2010 16:19 UTC**
Currently, using test.Person and test.Individual, a comparison of two fields, where one is from a pointed type, doesn't work, e.g. in 

compare(birthday, indiv.someDate= { birthdate > someDate } : "Birthdate must be before someDate!"

throws: 

java.lang.NullPointerException
	at org.makumba.providers.datadefinition.mdd.MDDExpressionParser.assignPart(MDDExpressionParser.java:38)
	at org.makumba.providers.datadefinition.mdd.MDDExpressionBaseParser.comparisonExpression(MDDExpressionBaseParser.java:233)
	at org.makumba.providers.datadefinition.mdd.MDDExpressionBaseParser.expression(MDDExpressionBaseParser.java:103)
	at org.makumba.providers.datadefinition.mdd.MDDParser.parseExpression(MDDParser.java:160)
	at org.makumba.providers.datadefinition.mdd.MDDBaseParser.parsedExpression(MDDBaseParser.java:1612)
	at org.makumba.providers.datadefinition.mdd.MDDBaseParser.comparisonValidationRuleDeclaration(MDDBaseParser.java:1787)
	at org.makumba.providers.datadefinition.mdd.MDDBaseParser.validationRuleDeclaration(MDDBaseParser.java:612)
	at org.makumba.providers.datadefinition.mdd.MDDBaseParser.declaration(MDDBaseParser.java:238)
	at org.makumba.providers.datadefinition.mdd.MDDBaseParser.dataDefinition(MDDBaseParser.java:123)
	at org.makumba.providers.datadefinition.mdd.MDDFactory.parse(MDDFactory.java:218)
	at org.makumba.providers.datadefinition.mdd.MDDFactory.parse(MDDFactory.java:193)

Migrated-From: http://trac.makumba.org/ticket/1254

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 30 Nov 2010 13:34 UTC**
Covered in general in #1263
