### ISSUE TITLE
colission between form name and label leads to NPE

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#805]
**Reported by @cristianbogdan on 20 Oct 2010 13:16 UTC**
i had this

<mak:editForm object="x"  action="..." name="x">
...

<mak:input  ... value="x" >

this lead to a NPE with the stacktrace below. i didn't actually need the name for the form, it was copied by accident, but given the NPE, it was pretty hard to figure out. at first i simply used value="$x" instead, and went further. then i thought i'd report this.

<mak:input type="hidden" ... value="x" />
^

Please report to the developers.

java.lang.NullPointerException: null
Stacktrace:
	at org.makumba.forms.tags.InputTag.doEndAnalyze(InputTag.java:218)
	at org.makumba.commons.ParseStatus.endPage(ParseStatus.java:258)
	at org.makumba.commons.MakumbaJspAnalyzer.endPage(MakumbaJspAnalyzer.java:384)
	at org.makumba.analyser.engine.JspParseData.parse(JspParseData.java:258)
	at org.makumba.analyser.engine.JspParseData.getSyntaxPointArray(JspParseData.java:189)
	at org.makumba.analyser.engine.JspParseData.getAnalysisResult(JspParseData.java:182)
	at org.makumba.analyser.AnalysableElement.getPageCache(AnalysableElement.java:180)
	at org.makumba.analyser.AnalysableElement.getPageCache(AnalysableElement.java:210)
	at org.makumba.analyser.AnalysableTag.doStartTag(AnalysableTag.java:216)
	at org.makumba.commons.tags.GenericMakumbaTag.doStartTag(GenericMakumbaTag.java:47)

Migrated-From: http://trac.makumba.org/ticket/1260

**Comment by ghost** [comment]
**Modified by @cristianbogdan on 20 Oct 2010 13:17 UTC**
