### ISSUE TITLE
Multi-field unique indices over subfields don't work when mixing fields from a subfield and the containing MDD

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#813]
**Reported by @rudolfmayer on 10 Dec 2010 15:18 UTC**
Given a unique constraint over subfields, such as

unique(generalEvent.name, generalEvent.start, organiser): "..."

which is evaluated by a query (as it can't be transformed into a DB unique index) seem to fail for constraints with 3 (and most likely more) arguments, with:

The problem is related to SQL:
    SQLstate: S1009
  ErrorCode: 0
     Message: Parameter index out of range (3 > number of parameters, which is 2).

Refer to your SQL server's documentation for error explanation.
Please check the configuration of your webapp and SQL server.
Please report to the developers.
java.sql.SQLException: Parameter index out of range (3 > number of parameters, which is 2).
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
	at com.mysql.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3657)
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3641)
	at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3683)
	at com.mysql.jdbc.PreparedStatement.setTimestampInternal(PreparedStatement.java:4715)
	at com.mysql.jdbc.PreparedStatement.setTimestamp(PreparedStatement.java:4658)
	at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3916)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setObject(NewProxyPreparedStatement.java:365)
	at org.makumba.db.makumba.sql.TableManager.setArgument(TableManager.java:1171)
	at org.makumba.db.makumba.sql.TableManager.setUpdateArgument(TableManager.java:1121)
	at org.makumba.db.makumba.sql.TableManager.findMultiFieldMultiTableDuplicates(TableManager.java:2072)
	at org.makumba.db.makumba.sql.TableManager.checkMultiFieldMultiTableUniqueness(TableManager.java:2315)
	at org.makumba.db.makumba.sql.TableManager.checkInsert(TableManager.java:2247)
	at org.makumba.db.makumba.MakumbaCRUDOperationProvider.checkInsert(MakumbaCRUDOperationProvider.java:31)
	at org.makumba.db.DataHolder.checkInsert(DataHolder.java:140)
	at org.makumba.db.TransactionImplementation.insert(TransactionImplementation.java:165)
	at org.makumba.db.makumba.DBConnection.insert(DBConnection.java:161)
	at org.makumba.db.makumba.DBConnectionWrapper.insert(DBConnectionWrapper.java:90)

Migrated-From: http://trac.makumba.org/ticket/1268

**Comment by ghost** [comment]
**Modified by @rudolfmayer on 10 Dec 2010 15:29 UTC**

**Comment by ghost** [comment]
**Comment by rosso_nero on 10 Dec 2010 16:15 UTC**
(In [5784]) fixing multi-field uniqueness checks that contain fields from the MDD and subfields (fixes #1268)
