### ISSUE TITLE
New MDD parser does not accept unique(..) in nested sub-subset

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#817]
**Reported by @rudolfmayer on 15 Dec 2010 13:03 UTC**
While the new MDD parser now works fine with unique() in subsets (see #1271), it doesn't work with nested sets in a subset, e.g. in test.Person:

address->sth->unique(aaa, bbb) : "aaa and bbb must be unique!"
yields a 

java.lang.RuntimeException: could not retrieve field definition for validation rule unique([bbb](aaa,)) : aaa and bbb must be unique! (line 94)
	at org.makumba.providers.datadefinition.mdd.DataDefinitionImpl.addValidationRules(DataDefinitionImpl.java:222)
	at org.makumba.providers.datadefinition.mdd.DataDefinitionImpl.build(DataDefinitionImpl.java:143)

the problem is that in DataDefinitionImpl.addValidationRules, the code

if (n.field != null
        && (n.field.mdd.fieldNameInParent.length() > 0 || n.field.subfield != null
                && n.field.subfield.fieldNameInParent.length() > 0)) {

    // we are in a subfield
    FieldDefinition subFd = this.getFieldDefinition(n.field.mdd.fieldNameInParent);

returns "address" as subFd, not "something".

thus, subsequently,
fd = subFd.getSubtable().getFieldDefinition(field);
fails (field is 'aaa' in this example)

Migrated-From: http://trac.makumba.org/ticket/1272

**Comment by ghost** [comment]
**Comment by rosso_nero on 15 Dec 2010 13:05 UTC**
(In [5787]) example for bug 1272 (re #1272)

**Comment by ghost** [comment]
**Comment by manuelbernhardt on 15 Dec 2010 15:40 UTC**
(In [5788]) handling validation rules in nested sets, fixes #1272
