### ISSUE TITLE
QueryTag not behaving correctly inside a for loop

### ISSUE THREAD

**Issue by ghost** [makumba/makumba#836]
**Reported by @rudolfmayer on 8 Apr 2011 20:16 UTC**
on http://private.best.eu.org/calendar/availabilityView.jsp?person=ta0uxj8 

```
java.lang.NullPointerException
    at org.makumba.list.engine.QueryExecution.currentListData(QueryExecution.java:306)
    at org.makumba.list.engine.valuecomputer.ValueComputer.getValue(ValueComputer.java:155)
    at org.makumba.list.engine.valuecomputer.ValueComputer.print(ValueComputer.java:170)
    at org.makumba.list.tags.ValueTag.doAnalyzedStartTag(ValueTag.java:151)
    at org.makumba.analyser.AnalysableTag.doStartTag(AnalysableTag.java:225)
    at org.makumba.commons.tags.GenericMakumbaTag.doStartTag(GenericMakumbaTag.java:47)
    at org.apache.jsp.calendar.availabilityView_jsp._jspService(availabilityView_jsp.java:805)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:98) 
```

Migrated-From: http://trac.makumba.org/ticket/1291

**Comment by ghost** [comment]
**Comment by @rudolfmayer on 8 Apr 2011 20:16 UTC**
cristi:

inside a java for(), first there is a root mak:object
```
<mak:object from="best.internal.Student bis, bis.student student, student.person person" where="person=$person" >
```

then in the mak:object there is the mak:list

```
<mak:list from="general.Availability availability" where="availability.student=bis AND ...
```

on the for() iteration after the mak:list ran once, the mak:list is not propertly initialized , it does not properly start a query execution, but because it believes it is properly started (variable wasStarted which basically is the presence of  pageContext.getAttribute(listKey)), it executes its body

then this mak:value

```
    <mak:value expr="availability.startDate" var="startDateDB"/>
```

assumes that there is a properly initialized QueryExecution and that's not the case.

the problem is this cleanup code  in QueryTag, line 523.

```
    if (getParentList(this) == null) {
            QueryExecution.endListGroup(pageContext);


        // also remove the attribute saying that this page was pre-started
        // this is important if a mak:list is repeated inside a loop for example
        // then the mak:list keys are equal, but we need to start a new iteration group
        String listKey = getListKey(pageContext);
        pageContext.removeAttribute(listKey);

    }
```

this pageContext cleanup is currently done only for root queries (if (getParentList(this) == null) ) but not removing the listKey from the context leads to the improper startup of the non-root mak:list. at the next iteration of the enclosing for loop, the mak:list believes that it was properly started but initializes no QueryExecution. the mak:value inside it executes but blows.

if the listKey removal is taken outside the if(), everything works well (and tests pass)

**Comment by ghost** [comment]
**Comment by @cristianbogdan on 8 Apr 2011 20:44 UTC**
This has nothing to do with QueryExecution. QueryTag uses QueryExecution wrong inside a loop.

In initiateQueryExecution (QueryTag line 331) it says

```
        if (!wasStarted) {
...
            // mark this list (iteration) to be run
            pageContext.setAttribute(listKey, Boolean.TRUE);
        }
```

while in doAnalyzedEndTag (line 523) it says

```
        if (getParentList(this) == null) {
            QueryExecution.endListGroup(pageContext);
....
            String listKey = getListKey(pageContext);
            pageContext.removeAttribute(listKey);
        }
```

that is, the listKey attribute is added for _all_ mak:lists, while it is only removed for _root_ mak:lists. 

That's asymmetric and it pollutes the pageContext with zombie mak:lists. Due to that, if a non-root mak:list is in a for() loop, it will mis-use its QueryExecution at the next iteration of that for() loop because it will believe it was started.

fixed in [5907]
